"use client";

import { useRef, useState } from "react";
import { DraggableTile } from "./draggable-tile";
import { playInteractionSound } from "./sound";

export interface SortItem { id: string; text: string; destination: string }
export interface SortBin { id: string; label: string; description?: string }

export function BinSort(props: { items: SortItem[]; bins: SortBin[]; instruction?: string; feedbackPolicy?: "immediate" | "end_of_round"; muted?: boolean; incorrectMessage?: string; repeatedIncorrectMessage?: string; onComplete?: (placements: Record<string, string>) => void }) {
  const [index, setIndex] = useState(0); const [placements, setPlacements] = useState<Record<string, string>>({}); const [message, setMessage] = useState(""); const [misses, setMisses] = useState(0); const item = props.items[index]; const binElements = useRef<Record<string, HTMLButtonElement | null>>({});
  function place(bin: string) { if (!item) return; playInteractionSound("select", props.muted); if (bin !== item.destination) { const nextMisses = misses + 1; setMisses(nextMisses); playInteractionSound("resist", props.muted); setMessage(nextMisses > 1 ? props.repeatedIncorrectMessage ?? props.incorrectMessage ?? "That choice shows a different job. Try again." : props.incorrectMessage ?? "That choice shows a different job. Look at the word's meaning and try again."); return; } const next = { ...placements, [item.id]: bin }; setPlacements(next); setMisses(0); playInteractionSound(index + 1 === props.items.length ? "complete" : "snap", props.muted); setMessage(props.feedbackPolicy === "end_of_round" ? "Placed" : `${item.text} belongs with ${props.bins.find((candidate) => candidate.id === bin)?.label}.`); if (index + 1 === props.items.length) props.onComplete?.(next); else setIndex(index + 1); }
  if (!item) return <p className="text-center font-semibold text-cyan-50">All words placed.</p>;
  return <div className="grid gap-5"><p className="mx-auto max-w-xl text-center text-base font-semibold text-cyan-50">{props.instruction ?? "Read the word. Think about what the prefix means. Then choose the meaning label that fits."}</p><div className="flex justify-center"><DraggableTile id={item.id} text={item.text} role="base" onDrop={(_, point) => { const destination = props.bins.find((bin) => { const rect = binElements.current[bin.id]?.getBoundingClientRect(); return rect && point.x >= rect.left && point.x <= rect.right && point.y >= rect.top && point.y <= rect.bottom; }); if (destination) place(destination.id); }} /></div><div role="group" aria-label={`Choose the meaning pattern for ${item.text}`} className="grid gap-3 sm:grid-cols-2">{props.bins.map((bin) => <button ref={(element) => { binElements.current[bin.id] = element; }} type="button" key={bin.id} onClick={() => place(bin.id)} className="min-h-24 rounded-3xl border border-cyan-300/40 bg-cyan-300/10 p-4 text-left text-white hover:bg-cyan-300/20 focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-cyan-300/40"><span className="block text-lg font-black">{bin.label}</span></button>)}</div><p aria-live="polite" className="min-h-6 text-center text-sm font-semibold text-cyan-100">{message}</p></div>;
}
