"use client";

import { useEffect, useRef, useState, type PointerEvent } from "react";
import { DiffReveal } from "./diff-reveal";
import { playInteractionSound } from "./sound";
import { useReducedMotion } from "./motion";

export type ShutterState = "look" | "cover" | "write" | "check";

export function CoverShutter(props: { word: string; splitPoints: number[]; initialState?: ShutterState; initialAttempt?: string; muted?: boolean; onStateChange?: (state: ShutterState, attempt: string) => void; onComplete?: (attempt: string) => void }) {
  const [state, setState] = useState<ShutterState>(props.initialState ?? "look");
  const [attempt, setAttempt] = useState(props.initialAttempt ?? "");
  const [slideDistance, setSlideDistance] = useState(0);
  const [showCoverFallback, setShowCoverFallback] = useState(false);
  const slideStartX = useRef<number | null>(null);
  const slideDistanceRef = useRef(0);
  const reducedMotion = useReducedMotion();
  useEffect(() => { if (state !== "look") { setShowCoverFallback(false); return; } const timer = window.setTimeout(() => setShowCoverFallback(true), 3000); return () => window.clearTimeout(timer); }, [state]);
  function change(next: ShutterState) { setState(next); props.onStateChange?.(next, attempt); }
  function closeShutter() { slideStartX.current = null; slideDistanceRef.current = 0; setSlideDistance(0); change("cover"); playInteractionSound("shutter", props.muted); window.setTimeout(() => change("write"), reducedMotion ? 0 : 300); }
  function beginSlide(event: PointerEvent<HTMLButtonElement>) { if (state !== "look") return; slideStartX.current = event.clientX; slideDistanceRef.current = 0; event.currentTarget.setPointerCapture(event.pointerId); }
  function moveSlide(event: PointerEvent<HTMLButtonElement>) { if (slideStartX.current === null) return; const distance = Math.max(0, event.clientX - slideStartX.current); slideDistanceRef.current = distance; setSlideDistance(distance); }
  function endSlide(event: PointerEvent<HTMLButtonElement>) { if (slideStartX.current === null) return; const distance = Math.max(slideDistanceRef.current, Math.max(0, event.clientX - slideStartX.current)); slideStartX.current = null; slideDistanceRef.current = 0; setSlideDistance(0); if (distance >= 80) closeShutter(); }
  const coverTransform = state === "look" ? `translateX(calc(-100% + ${64 + slideDistance}px))` : state === "check" ? "translateX(-100%)" : "translateX(0)";
  const displayWord = props.splitPoints.length === 0 ? props.word : <>{props.word.slice(0, props.splitPoints[0])}<span className="mx-1 text-cyan-300">|</span>{props.word.slice(props.splitPoints[0])}</>;
  return <div className="grid gap-4 rounded-3xl border border-white/15 bg-slate-950/50 p-5"><div className="relative min-h-28 overflow-hidden rounded-2xl bg-white/5 p-6 text-center">{state === "look" || state === "check" ? <p className="text-4xl font-black tracking-wide text-white">{displayWord}</p> : null}<button type="button" disabled={state !== "look"} aria-hidden={state !== "look"} aria-label="Slide the cover from left to right to hide the word. Press Enter, Space, or Right Arrow to hide it with the keyboard." onPointerDown={beginSlide} onPointerMove={moveSlide} onPointerUp={endSlide} onPointerCancel={() => { slideStartX.current = null; slideDistanceRef.current = 0; setSlideDistance(0); }} onKeyDown={(event) => { if (event.key === "Enter" || event.key === " " || event.key === "ArrowRight") { event.preventDefault(); closeShutter(); } }} className={`absolute inset-y-0 left-0 grid w-full touch-none select-none place-items-center bg-gradient-to-r from-slate-700 to-slate-900 text-sm font-bold uppercase tracking-[0.3em] text-cyan-100 focus:outline-none focus-visible:ring-4 focus-visible:ring-cyan-300 disabled:opacity-100 ${reducedMotion ? "" : "transition-transform duration-300"}`} style={{ transform: coverTransform }}><span aria-hidden="true">word covered</span><span aria-hidden="true" className="absolute inset-y-0 right-0 flex w-16 flex-col items-center justify-center gap-1 rounded-r-2xl bg-cyan-300 px-1 text-[10px] font-black tracking-normal text-cyan-950"><span className="text-lg leading-none">→</span><span>SLIDE</span></span></button></div>{state === "look" ? <><p className="text-center text-sm font-semibold text-cyan-100">Drag the bright <strong>SLIDE →</strong> handle across the word, then let go.</p>{showCoverFallback ? <button type="button" onClick={closeShutter} className="min-h-12 rounded-full bg-cyan-300 px-5 font-black text-slate-950">Cover the word</button> : null}</> : null}{state === "write" ? <div><label className="text-sm font-semibold text-cyan-50">Type the whole word<input autoFocus autoComplete="off" spellCheck={false} value={attempt} onChange={(event) => { setAttempt(event.target.value); props.onStateChange?.("write", event.target.value); }} className="mt-2 w-full rounded-2xl border border-cyan-300/40 bg-white p-4 text-xl text-slate-950 focus:outline-none focus:ring-4 focus-visible:ring-cyan-300/30" /></label><button type="button" disabled={!attempt.trim()} onClick={() => { change("check"); playInteractionSound("reveal", props.muted); props.onComplete?.(attempt); }} className="mt-3 min-h-12 w-full rounded-full bg-cyan-300 font-black text-slate-950 disabled:opacity-40">Check</button></div> : null}{state === "check" ? <DiffReveal attempt={attempt} expected={props.word} splitPoints={props.splitPoints} /> : null}</div>;
}
