import { fingerprintSnapshotValue } from "./canonical-fingerprint";
import { validateCompiledSpecialistSnapshotV3 } from "./specialist-snapshot-v3-validator";
import {
  SPECIALIST_SNAPSHOT_V3_COMPILER_VERSION, SPECIALIST_SNAPSHOT_V3_REGISTRY_VERSION, SPECIALIST_SNAPSHOT_V3_VALIDATOR_VERSION,
  type CompileBaseWordSpecialistSnapshotV3Input, type CompileDynamicPrefixSpecialistSnapshotV3Input,
  type CompiledBaseWordSpecialistSnapshotV3, type CompiledDynamicPrefixSpecialistSnapshotV3,
  type SpecialistCanonicalActivitySnapshotV3, type SpecialistSnapshotAuthorityV3, type SpecialistSnapshotItemBindingV3,
} from "./specialist-snapshot-v3-contracts";

function bind(items: CompileDynamicPrefixSpecialistSnapshotV3Input["items"], field: string, id: string): SpecialistSnapshotItemBindingV3 {
  const item = items.find((candidate) => candidate.promptData[field] === id);
  if (!item) throw new Error(`compileSpecialistSnapshotV3:missing_item:${id}`);
  return { sourceEntityId: item.sourceEntityId, position: item.position, inputSource: "assignment_items.prompt_data" };
}
function sha(value: string | undefined, detail: string): string {
  if (!value || !/^[a-f0-9]{64}$/u.test(value)) throw new Error(`compileSpecialistSnapshotV3:missing_governed_hash:${detail}`);
  return value;
}
function validationContext(input: { header: CompileDynamicPrefixSpecialistSnapshotV3Input["header"]; items: CompileDynamicPrefixSpecialistSnapshotV3Input["items"] }) {
  return { lessonRouteMetadata: input.header.lessonRouteMetadata, assignmentGenerationSource: input.header.assignmentGenerationSource, items: input.items.map((item) => ({ sourceEntityId: item.sourceEntityId, position: item.position, sectionKey: item.metadata.sectionKey, canonicalWordId: item.metadata.canonicalWordId, templateKey: item.templateKey, targetWord: item.targetWord, promptData: item.promptData })) };
}
function activityBuilder() {
  let order = 0;
  return (value: Omit<SpecialistCanonicalActivitySnapshotV3, "contractVersion" | "order">): SpecialistCanonicalActivitySnapshotV3 => ({ contractVersion: 3, order: ++order, ...value });
}

export function compileDynamicPrefixSpecialistSnapshotV3(input: CompileDynamicPrefixSpecialistSnapshotV3Input): CompiledDynamicPrefixSpecialistSnapshotV3 {
  const source = input.payload.sourcePayload, runtime = input.payload.runtimePayload;
  const words = source.words.lesson, wordIds = words.map((word) => word.canonicalWordId), make = activityBuilder();
  const get = (type: string) => { const found = runtime.activities.find((candidate) => candidate.type === type); if (!found) throw new Error(`compileDynamicPrefixSpecialistSnapshotV3:missing_activity:${type}`); return found; };
  const discovery = get("discovery"), split = get("strip_build"), meaning = runtime.activities.find((entry) => entry.type === "meaning_sort"), build = get("prefix_choice"), cover = get("look_cover_write_check"), dictation = get("sentence_dictation"), reflection = get("reflection");
  const b = (id: string) => bind(input.items, "dynamicPrefixActivityId", id);
  const activities: SpecialistCanonicalActivitySnapshotV3[] = [
    make({ activityId: "teaching-pages", label: "Teaching Pages", sectionKey: "lesson_intro", canonical: { concept: "INTRODUCTION", mode: "teaching_page", contractVersion: 1 }, payload: { config: input.payload.teaching }, itemBindings: [b("intro-root"), b("intro-words")], wordSnapshotIds: wordIds, ownership: "assignment_items" }),
    make({ activityId: "discover", label: "Discover", sectionKey: "guided_practice", canonical: { concept: "MEANING_DISCOVERY", mode: "prefix", contractVersion: 1 }, payload: { cards: discovery.discoveryCards ?? [], affixLabel: discovery.prefixLabel }, itemBindings: [], wordSnapshotIds: wordIds, ownership: "route_owned" }),
    make({ activityId: "split", label: "Split", sectionKey: "guided_practice", canonical: { concept: "CLEAVER", mode: "find_boundaries", contractVersion: 1 }, payload: { targets: (split.wordIds ?? []).map((id) => words.find((word) => word.canonicalWordId === id)) }, itemBindings: split.assignmentBindings.map(b), wordSnapshotIds: split.wordIds ?? [], ownership: "assignment_items" }),
    ...(meaning ? [make({ activityId: "meaning", label: "Meaning", sectionKey: "guided_practice", canonical: { concept: "MEANING_SORT", mode: meaning.meaningCheckKind === "prefix_form" ? "prefix_form" : "meaning", contractVersion: 1 }, payload: { wordIds: meaning.wordIds ?? wordIds, bins: meaning.meaningBins ?? [], affixPosition: "before" }, itemBindings: meaning.assignmentBindings.map(b), wordSnapshotIds: meaning.wordIds ?? wordIds, ownership: "assignment_items" })] : []),
    make({ activityId: "build", label: "Build", sectionKey: "guided_practice", canonical: { concept: "WORD_ASSEMBLY", mode: "definition_word_builder", contractVersion: 1 }, payload: { builds: build.builds ?? [] }, itemBindings: build.assignmentBindings.map(b), wordSnapshotIds: (build.builds ?? []).map((entry) => entry.canonicalWordId), ownership: "assignment_items" }),
    make({ activityId: "cover", label: "Cover", sectionKey: "lesson_production", canonical: { concept: "COVER_CHECK", mode: cover.coverClosePolicy ? "ratio_close_policy" : "component_marked", contractVersion: 1 }, payload: { targets: words.map((word) => ({ canonicalWordId: word.canonicalWordId, word: word.displayWord, splitPoints: word.splitPoints, parts: word.parts })), ...(cover.coverClosePolicy ? { coverClosePolicy: cover.coverClosePolicy } : {}) }, itemBindings: cover.assignmentBindings.map(b), wordSnapshotIds: wordIds, ownership: "assignment_items" }),
    make({ activityId: "dictation", label: "Dictate", sectionKey: "lesson_dictation", canonical: { concept: "DICTATION", mode: "target_token", contractVersion: 1 }, payload: { sentences: (dictation.sentences ?? []).map((sentence) => ({ ...sentence, audioText: words.find((word) => word.canonicalWordId === sentence.canonicalWordId)?.audioText })) }, itemBindings: dictation.assignmentBindings.map(b), wordSnapshotIds: wordIds, ownership: "assignment_items" }),
    make({ activityId: "lesson-reflection", label: "Lesson Reflection", sectionKey: "lesson_reflection", canonical: { concept: "LESSON_REFLECTION", mode: "standard_lesson_reflection", contractVersion: 1 }, payload: { promptKey: reflection.promptKey, promptText: reflection.promptText, promptSource: { kind: "resolved_dynamic_prefix_runtime", contentVersion: runtime.contentVersion } }, itemBindings: [], wordSnapshotIds: wordIds, ownership: "route_owned" }),
  ];
  const profile = input.selection.profile;
  if (!profile.governance) throw new Error("compileDynamicPrefixSpecialistSnapshotV3:missing_profile_governance");
  const contentVersions: SpecialistSnapshotAuthorityV3[] = [
    { authorityType: "affix_profile_content", authorityId: profile.governance.profileId, version: `${source.contentVersion}:import:${profile.governance.importBatchId}`, sourceHash: sha(profile.governance.sourceRowHash, "profile") },
    { authorityType: "shared_affix_source", authorityId: profile.microSkillKey, version: String(input.compilerDecision.compilerVersion), sourceHash: input.compilerDecision.sourceFingerprint ?? fingerprintSnapshotValue(source) },
    { authorityType: "shared_affix_lesson", authorityId: `${profile.microSkillKey}:resolved`, version: String(input.compilerDecision.compilerVersion), sourceHash: input.compilerDecision.outputFingerprint ?? fingerprintSnapshotValue(runtime) },
    { authorityType: "public_payload", authorityId: `${profile.microSkillKey}:dynamic_prefix_lesson_v2`, version: "2", sourceHash: fingerprintSnapshotValue(source) },
    { authorityType: "recipe_content", authorityId: `${profile.microSkillKey}:dynamic_prefix_word_lab:v2`, version: source.contentVersion, sourceHash: fingerprintSnapshotValue({ recipe: source.experienceProfile, resolvedRuntime: runtime }) },
  ];
  for (const word of words) { const governed = profile.wordsByCanonicalId.get(word.canonicalWordId)?.governance; if (!governed) throw new Error(`compileDynamicPrefixSpecialistSnapshotV3:missing_word_governance:${word.canonicalWordId}`); contentVersions.push({ authorityType: "affix_member_content", authorityId: governed.memberId, version: source.contentVersion, sourceHash: sha(governed.memberSourceRowHash, "member") }, { authorityType: "teaching_dictionary_word", authorityId: word.canonicalWordId, version: source.contentVersion, sourceHash: sha(governed.dictionaryWordSourceRowHash, "word") }, { authorityType: "dictation_content", authorityId: governed.dictationId, version: source.contentVersion, sourceHash: sha(governed.dictationSourceRowHash, "dictation") }); }
  const authentic = new Map(input.selection.authenticTargets.map((entry) => [entry.canonicalWordId, entry]));
  const base = { snapshotSchemaVersion: 3 as const, compilerVersion: SPECIALIST_SNAPSHOT_V3_COMPILER_VERSION, validatorVersion: SPECIALIST_SNAPSHOT_V3_VALIDATOR_VERSION, canonicalContractRegistryVersion: SPECIALIST_SNAPSHOT_V3_REGISTRY_VERSION, route: { routeId: "dynamic_prefix_word_lab" as const, routeVersion: "v2" as const }, recipe: { recipeKey: "dynamic_prefix_word_lab" as const, recipeVersion: "v2" as const }, payload: { kind: "dynamic_prefix_lesson_v2" as const, version: 2 as const, resolvedLesson: input.payload }, runtime: { adapterKey: "dynamic_prefix_v2" as const, rendererKey: "morphology_guided" as const }, assignment: { generationSource: "adle_composer_v1" as const, itemCount: input.items.length as 16 | 18 }, taxonomy: { microSkillKey: source.microSkillId }, words: words.map((word, index) => ({ wordSnapshotId: word.canonicalWordId, order: index + 1, canonicalWordId: word.canonicalWordId, displayWord: word.displayWord, learningItemId: authentic.get(word.canonicalWordId)?.learningItemId ?? null, lineageKind: authentic.has(word.canonicalWordId) ? "authentic_target" as const : "transfer" as const })), activities, segments: [{ segmentId: "lesson" as const, wordSnapshotIds: wordIds, activityIds: activities.map((entry) => entry.activityId) }] as const, contentVersions };
  const provenance = { sourceKind: "compiled_specialist_assignment" as const, fingerprintAlgorithm: "sha256" as const, fingerprintVersion: 1 as const };
  const snapshot: CompiledDynamicPrefixSpecialistSnapshotV3 = { ...base, provenance: { ...provenance, sourceFingerprint: fingerprintSnapshotValue({ ...base, provenance }) } };
  const valid = validateCompiledSpecialistSnapshotV3(snapshot, validationContext(input)); if (!valid.ok) throw new Error(`compileDynamicPrefixSpecialistSnapshotV3:${valid.blockers.map((x) => x.code).join(",")}`); return snapshot;
}

export function compileBaseWordSpecialistSnapshotV3(input: CompileBaseWordSpecialistSnapshotV3Input): CompiledBaseWordSpecialistSnapshotV3 {
  const source = input.payload.sourcePayload, words = source.independentWords, wordIds = words.map((word) => word.canonicalWordId), make = activityBuilder(), b = (id: string) => bind(input.items, "pilotActivityId", id);
  const activities: SpecialistCanonicalActivitySnapshotV3[] = [
    make({ activityId: "teaching-pages", label: "Teaching Pages", sectionKey: "lesson_intro", canonical: { concept: "INTRODUCTION", mode: "teaching_page", contractVersion: 1 }, payload: { config: input.payload.teaching }, itemBindings: [b("strategy-intro")], wordSnapshotIds: wordIds, ownership: "assignment_items" }),
    ...source.familySections.map((section) => make({ activityId: `family-${section.baseFamilyKey}`, label: "Family Reveal", sectionKey: "guided_practice", canonical: { concept: "WORD_FAMILY_REVEAL", mode: "base_led_family", contractVersion: 1 }, payload: { section }, itemBindings: [b(`family-reveal-${section.baseFamilyKey}`)], wordSnapshotIds: section.guidedWords.map((word) => word.canonicalWordId), ownership: "assignment_items" })),
    ...source.authenticTargets.map((target) => make({ activityId: `cleave-${target.canonicalWordId}`, label: "Split", sectionKey: "guided_practice", canonical: { concept: "CLEAVER", mode: "isolate_component", contractVersion: 1 }, payload: { target: source.independentWords.find((word) => word.canonicalWordId === target.canonicalWordId) }, itemBindings: [b(`cleave-${target.canonicalWordId}`)], wordSnapshotIds: [target.canonicalWordId], ownership: "assignment_items" })),
    make({ activityId: "word-sums", label: "Build", sectionKey: "guided_practice", canonical: { concept: "WORD_ASSEMBLY", mode: "definition_word_builder", contractVersion: 1 }, payload: { targets: source.familySections.flatMap((section) => section.guidedWords) }, itemBindings: [b("word-sum-builder")], wordSnapshotIds: source.familySections.flatMap((section) => section.guidedWords.map((word) => word.canonicalWordId)), ownership: "assignment_items" }),
    make({ activityId: "cover", label: "Cover", sectionKey: "lesson_production", canonical: { concept: "COVER_CHECK", mode: "whole_word", contractVersion: 1 }, payload: { targets: words.map((word) => ({ canonicalWordId: word.canonicalWordId, word: word.displayWord, splitPoints: [] })) }, itemBindings: words.map((word) => b(`controlled-${word.canonicalWordId}`)), wordSnapshotIds: wordIds, ownership: "assignment_items" }),
    make({ activityId: "dictation", label: "Dictate", sectionKey: "lesson_dictation", canonical: { concept: "DICTATION", mode: "target_token", contractVersion: 1 }, payload: { sentences: words.map((word) => ({ canonicalWordId: word.canonicalWordId, targetWord: word.displayWord, sentence: word.dictationSentence, audioText: word.audioText, targetTokenIndex: word.dictationTargetTokenIndex })) }, itemBindings: words.map((word) => b(`dictation-${word.canonicalWordId}`)), wordSnapshotIds: wordIds, ownership: "assignment_items" }),
    make({ activityId: "lesson-reflection", label: "Lesson Reflection", sectionKey: "lesson_reflection", canonical: { concept: "LESSON_REFLECTION", mode: "standard_lesson_reflection", contractVersion: 1 }, payload: input.payload.reflection, itemBindings: [], wordSnapshotIds: wordIds, ownership: "route_owned" }),
  ];
  const release = input.releaseAuthority;
  const contentVersions: SpecialistSnapshotAuthorityV3[] = [
    { authorityType: "release_manifest", authorityId: release.releaseManifestId, version: release.releaseKey, sourceHash: release.releaseManifestSha256 }, { authorityType: "activation_revision", authorityId: release.activationRevisionId, version: "1", sourceHash: release.releaseManifestSha256 }, { authorityType: "dependency_set", authorityId: release.releaseManifestId, version: "1", sourceHash: release.dependencyFingerprint }, { authorityType: "compound_structure", authorityId: release.familyAuthorityId, version: String(release.family.schemaVersion), sourceHash: release.familyAuthorityFingerprint }, { authorityType: "teaching_content", authorityId: release.teachingContentAuthorityId, version: source.contentVersion, sourceHash: release.teachingContentAuthorityFingerprint }, { authorityType: "teaching_dictionary_closure", authorityId: release.dictionaryClosureAuthorityId, version: "1", sourceHash: release.dictionaryClosureAuthorityFingerprint }, { authorityType: "recipe_content", authorityId: `${source.microSkillKey}:base_word_family:v1`, version: source.contentVersion, sourceHash: fingerprintSnapshotValue(input.payload) },
  ];
  const slots = new Map(source.independentSlots.map((slot) => [slot.canonicalWordId, slot]));
  const base = { snapshotSchemaVersion: 3 as const, compilerVersion: SPECIALIST_SNAPSHOT_V3_COMPILER_VERSION, validatorVersion: SPECIALIST_SNAPSHOT_V3_VALIDATOR_VERSION, canonicalContractRegistryVersion: SPECIALIST_SNAPSHOT_V3_REGISTRY_VERSION, route: { routeId: "base_word_lab" as const, routeVersion: "v2" as const }, recipe: { recipeKey: "base_word_family" as const, recipeVersion: "v1" as const }, payload: { kind: "base_word_family_snapshot_v1" as const, version: 1 as const, resolvedLesson: input.payload }, runtime: { adapterKey: "base_word_family_v1" as const, rendererKey: "base_word_family_guided" as const }, assignment: { generationSource: "adle_base_word_family_pilot_v1" as const, itemCount: 18 as const }, taxonomy: { microSkillKey: source.microSkillKey }, words: words.map((word, index) => ({ wordSnapshotId: word.canonicalWordId, order: index + 1, canonicalWordId: word.canonicalWordId, displayWord: word.displayWord, learningItemId: slots.get(word.canonicalWordId)?.learningItemId ?? null, lineageKind: slots.get(word.canonicalWordId)?.provenance === "authentic_target" ? "authentic_target" as const : "transfer" as const })), activities, segments: [{ segmentId: "lesson" as const, wordSnapshotIds: wordIds, activityIds: activities.map((entry) => entry.activityId) }] as const, contentVersions };
  const provenance = { sourceKind: "compiled_specialist_assignment" as const, fingerprintAlgorithm: "sha256" as const, fingerprintVersion: 1 as const }; const snapshot: CompiledBaseWordSpecialistSnapshotV3 = { ...base, provenance: { ...provenance, sourceFingerprint: fingerprintSnapshotValue({ ...base, provenance }) } };
  const valid = validateCompiledSpecialistSnapshotV3(snapshot, validationContext(input)); if (!valid.ok) throw new Error(`compileBaseWordSpecialistSnapshotV3:${valid.blockers.map((x) => x.code).join(",")}`); return snapshot;
}
