import type {
  StructuredLessonDocument,
  StructuredLessonBlock,
} from "@/lib/lessons/schema";

export type StructuredLessonPreset = {
  id: string;
  label: string;
  description: string;
  lesson: StructuredLessonDocument;
};

function cloneBlocks<T extends StructuredLessonBlock[]>(blocks: T): T {
  return JSON.parse(JSON.stringify(blocks)) as T;
}

const problemLessonBlocks: StructuredLessonBlock[] = [
  {
    block_id: "problem-heading",
    block_type: "heading",
    eyebrow: "Phase One · Module 1",
    heading: "What Problem Do I Want To Solve?",
  },
  {
    block_id: "problem-intro",
    block_type: "section_intro",
    eyebrow: "Start here",
    title: "Great businesses start with a real problem",
    body: "Use this lesson to spot problems, dig deeper, and turn your ideas into the beginning of a founder story.",
  },
  {
    block_id: "problem-part-1",
    block_type: "titled_divider",
    title: "Part 1 — My Three Problems",
  },
  {
    block_id: "problem-part-1-intro",
    block_type: "section_intro",
    eyebrow: "Notice",
    title: "Start by spotting real problems",
    body: "Think of three problems you have noticed in real life. Each one should be specific enough that you could imagine making something to solve it.",
  },
  {
    block_id: "problem-part-1-cards",
    block_type: "info_cards",
    title: "What makes a good problem to explore?",
    body: "Use these reminders to choose problems that feel real rather than invented.",
    cards: [
      {
        card_id: "problem-card-1",
        icon: "🔍",
        title: "Look for frustration",
        body: "Notice things that feel annoying, missing, boring, or badly designed in everyday life.",
      },
      {
        card_id: "problem-card-2",
        icon: "💬",
        title: "Think about real people",
        body: "A strong founder problem usually affects real people in a repeated way, not just once.",
      },
      {
        card_id: "problem-card-3",
        icon: "✨",
        title: "Imagine the solution",
        body: "A good problem also makes you want to imagine what could exist instead.",
      },
    ],
  },
  {
    block_id: "problem-1",
    block_type: "question_text",
    label: "Problem 1",
    placeholder: "e.g. Healthy snacks are really boring...",
    required: false,
    exclude_from_spelling: false,
    save_affordance: "auto",
  },
  {
    block_id: "idea-1",
    block_type: "question_text",
    label: "Possible product idea 1",
    placeholder: "e.g. Exciting date ball boxes...",
    required: false,
    exclude_from_spelling: false,
    save_affordance: "auto",
  },
  {
    block_id: "problem-2",
    block_type: "question_text",
    label: "Problem 2",
    placeholder: "e.g. Gifts feel impersonal...",
    required: false,
    exclude_from_spelling: false,
    save_affordance: "auto",
  },
  {
    block_id: "idea-2",
    block_type: "question_text",
    label: "Possible product idea 2",
    placeholder: "e.g. Handmade luxury gift boxes...",
    required: false,
    exclude_from_spelling: false,
    save_affordance: "auto",
  },
  {
    block_id: "problem-3",
    block_type: "question_text",
    label: "Problem 3",
    placeholder: "e.g. Party bags are full of sweets...",
    required: false,
    exclude_from_spelling: false,
    save_affordance: "auto",
  },
  {
    block_id: "idea-3",
    block_type: "question_text",
    label: "Possible product idea 3",
    placeholder: "e.g. Better party treat boxes...",
    required: false,
    exclude_from_spelling: false,
    save_affordance: "auto",
  },
  {
    block_id: "problem-divider-1",
    block_type: "titled_divider",
    title: "Part 2 — Research",
  },
  {
    block_id: "problem-research-intro",
    block_type: "section_intro",
    eyebrow: "Dig deeper",
    title: "Pick one problem and find out who else has it",
    body: "Use AI as a helper, but keep your own thinking in the centre. Your job is to understand real people properly.",
  },
  {
    block_id: "chosen-problem",
    block_type: "question_textarea",
    label: "My chosen problem",
    placeholder:
      "e.g. Parents want to give their children exciting treats, but most healthy snacks are too boring for children to actually want...",
    rows: 4,
    required: false,
    exclude_from_spelling: false,
    save_affordance: "auto",
  },
  {
    block_id: "problem-type",
    block_type: "question_choice_multi",
    label: "What type of problem is this?",
    options: [
      { value: "frustration", label: "Frustration" },
      { value: "need", label: "Need" },
      { value: "interest", label: "Interest" },
      { value: "value", label: "Value" },
    ],
    exclude_from_spelling: true,
    save_affordance: "auto",
  },
  {
    block_id: "ai-prompt-cards",
    block_type: "info_cards",
    title: "What your prompt needs to include",
    body: "A strong prompt tells the AI exactly what you want to find out.",
    cards: [
      {
        card_id: "prompt-card-1",
        icon: "🎯",
        title: "State the problem clearly",
        body: "Tell the AI exactly what your problem is, in clear and specific language.",
      },
      {
        card_id: "prompt-card-2",
        icon: "🌍",
        title: "Ask where to search",
        body: "Ask it to search forums, Reddit, Facebook groups, and news sources.",
      },
      {
        card_id: "prompt-card-3",
        icon: "🧠",
        title: "Ask for patterns",
        body: "Ask who has the problem, what they do now, what they wish existed, and the key patterns it notices.",
      },
    ],
  },
  {
    block_id: "ai-prompt-example",
    block_type: "callout",
    title: "Example prompt shape",
    content:
      "<p>Search forums, Reddit, and Facebook groups about my problem. Tell me who has this problem, how old they are, what they say in their own words, what they currently buy instead, what they wish existed, and the key patterns you notice.</p>",
    tone: "tip",
  },
  {
    block_id: "ai-prompt",
    block_type: "question_textarea",
    label: "My AI research prompt",
    placeholder: "Write your AI research prompt here in your own words...",
    rows: 6,
    required: false,
    exclude_from_spelling: false,
    save_affordance: "auto",
  },
  {
    block_id: "ai-report",
    block_type: "question_textarea",
    label: "AI research report",
    placeholder: "Paste the AI's full report here...",
    rows: 8,
    required: false,
    exclude_from_spelling: true,
    save_affordance: "auto",
  },
  {
    block_id: "my-summary",
    block_type: "question_textarea",
    label: "My summary — who I'm going to help and what problems they face",
    placeholder:
      "The people I want to help are... They struggle with... They currently... What they really wish for is...",
    rows: 6,
    required: false,
    exclude_from_spelling: false,
    save_affordance: "auto",
  },
  {
    block_id: "summary-guidance",
    block_type: "callout",
    title: "How to write a strong summary",
    content:
      "<p>Do not copy from the report. Read it, close it, then write from memory. Ask yourself: who are these people, what frustrates them, what do they currently do, and what do they really wish existed?</p>",
    tone: "tip",
  },
  {
    block_id: "summary-prompt",
    block_type: "question_textarea",
    label: "Prompt to ask AI for a summary check",
    placeholder: "Write a prompt asking the AI to summarise the report...",
    rows: 4,
    required: false,
    exclude_from_spelling: false,
    save_affordance: "auto",
  },
  {
    block_id: "ai-summary-paste",
    block_type: "question_textarea",
    label: "Paste the AI's summary paragraph here to compare with yours",
    placeholder: "Paste the AI's summary paragraph here...",
    rows: 4,
    required: false,
    exclude_from_spelling: true,
    save_affordance: "auto",
  },
  {
    block_id: "problem-divider-2",
    block_type: "titled_divider",
    title: "Part 3 — Product Ideas",
  },
  {
    block_id: "products-intro",
    block_type: "section_intro",
    eyebrow: "Create",
    title: "List 3 product ideas you love",
    body: "Based on your research, what could you actually make? Write three ideas that genuinely excite you.",
  },
  {
    block_id: "product-1",
    block_type: "question_text",
    label: "Product idea 1",
    placeholder: "e.g. Luxury date balls in a handmade gift box...",
    required: false,
    exclude_from_spelling: false,
    save_affordance: "auto",
  },
  {
    block_id: "product-2",
    block_type: "question_text",
    label: "Product idea 2",
    placeholder: "e.g. A monthly healthy treat subscription box for families...",
    required: false,
    exclude_from_spelling: false,
    save_affordance: "auto",
  },
  {
    block_id: "product-3",
    block_type: "question_text",
    label: "Product idea 3",
    placeholder: "e.g. Better party treat bags with natural sweets...",
    required: false,
    exclude_from_spelling: false,
    save_affordance: "auto",
  },
  {
    block_id: "problem-divider-3",
    block_type: "titled_divider",
    title: "Part 4 — My Why",
  },
  {
    block_id: "why-ladder-intro",
    block_type: "section_intro",
    eyebrow: "Go deeper",
    title: "The Why Ladder",
    body: "Keep asking why this problem matters. Each answer should go a little deeper than the one before.",
  },
  {
    block_id: "why-ladder-example",
    block_type: "callout",
    title: "Example",
    content:
      "<p>Problem: Healthy snacks are boring. Why? Children will not eat them. Why? Parents buy sweets instead. Why does that matter? Parents want treats children enjoy but also feel good about. Deeper reason: food should make people happy without making parents feel guilty.</p>",
    tone: "success",
  },
  {
    block_id: "why-0",
    block_type: "question_textarea",
    label: "Problem I noticed",
    placeholder: "Write your chosen problem...",
    rows: 2,
    required: false,
    exclude_from_spelling: false,
    save_affordance: "auto",
  },
  {
    block_id: "why-1",
    block_type: "question_textarea",
    label: "Why does this matter?",
    placeholder: "Because...",
    rows: 2,
    required: false,
    exclude_from_spelling: false,
    save_affordance: "auto",
  },
  {
    block_id: "why-2",
    block_type: "question_textarea",
    label: "Why does that matter?",
    placeholder: "Because...",
    rows: 2,
    required: false,
    exclude_from_spelling: false,
    save_affordance: "auto",
  },
  {
    block_id: "why-3",
    block_type: "question_textarea",
    label: "Why does that matter next?",
    placeholder: "Because...",
    rows: 2,
    required: false,
    exclude_from_spelling: false,
    save_affordance: "auto",
  },
  {
    block_id: "why-4",
    block_type: "question_textarea",
    label: "Why does that matter even more?",
    placeholder: "Because...",
    rows: 2,
    required: false,
    exclude_from_spelling: false,
    save_affordance: "auto",
  },
  {
    block_id: "why-5",
    block_type: "question_textarea",
    label: "My deeper reason — this problem matters to me because...",
    placeholder: "At the deepest level, I care about this because...",
    rows: 3,
    required: false,
    exclude_from_spelling: false,
    save_affordance: "auto",
  },
  {
    block_id: "problem-divider-4",
    block_type: "titled_divider",
    title: "Part 5 — Founder Statement",
  },
  {
    block_id: "founder-statement-intro",
    block_type: "section_intro",
    eyebrow: "Bring it together",
    title: "Write your first founder statement",
    body: "Bring it all together into a first honest founder statement. It does not need to be perfect — it needs to be true.",
  },
  {
    block_id: "founder-statement-example",
    block_type: "callout",
    title: "Example founder statement",
    content:
      "<p>I noticed that healthy snacks are boring and children do not want to eat them. I care about this because children should enjoy treats that parents trust. I want to help families who want better snacks without losing the fun. I could create colourful chocolate date balls with simple ingredients. I want customers to feel excited, happy, and confident about what they are eating.</p>",
    tone: "tip",
  },
  {
    block_id: "fs-1",
    block_type: "question_text",
    label: "I noticed that...",
    placeholder: "...",
    required: false,
    exclude_from_spelling: false,
    save_affordance: "auto",
  },
  {
    block_id: "fs-2",
    block_type: "question_text",
    label: "I care about this because...",
    placeholder: "...",
    required: false,
    exclude_from_spelling: false,
    save_affordance: "auto",
  },
  {
    block_id: "fs-3",
    block_type: "question_text",
    label: "I want to help...",
    placeholder: "...",
    required: false,
    exclude_from_spelling: false,
    save_affordance: "auto",
  },
  {
    block_id: "fs-4",
    block_type: "question_text",
    label: "I could create...",
    placeholder: "...",
    required: false,
    exclude_from_spelling: false,
    save_affordance: "auto",
  },
  {
    block_id: "fs-5",
    block_type: "question_text",
    label: "I want customers to feel...",
    placeholder: "...",
    required: false,
    exclude_from_spelling: false,
    save_affordance: "auto",
  },
];

const kindLessonBlocks: StructuredLessonBlock[] = [
  {
    block_id: "kind-heading",
    block_type: "heading",
    eyebrow: "Founder Story",
    heading: "Daniel's Big Snack Idea!",
  },
  {
    block_id: "kind-intro",
    block_type: "section_intro",
    eyebrow: "Founder Story",
    title: "Read Daniel's story, then test what you learned",
    body: "Think about Daniel Lubetzky, the founder of KIND Snacks, and what his journey means for your own ideas.",
  },
  {
    block_id: "kind-link",
    block_type: "action_link",
    label: "Read the article",
    url: "https://fortune.com/2024/10/20/kind-daniel-lubetzky-secrets-to-success/",
    style: "primary",
  },
  {
    block_id: "kind-callout",
    block_type: "callout",
    title: "Story summary",
    content:
      "<p>Daniel noticed there were plenty of snacks, but not many he felt good about eating. He started small, made the first bars by hand, stayed focused, and built KIND around honesty, quality, and integrity.</p>",
    tone: "tip",
  },
  {
    block_id: "kind-journey",
    block_type: "rich_text",
    content:
      "<p>Daniel's story is really about noticing a gap, starting resourcefully, learning from mistakes, staying focused, and building a business people can trust.</p>",
  },
  {
    block_id: "kind-quiz",
    block_type: "comprehension_quiz_group",
    label: "Comprehension quiz",
    help_text: "Choose the best answer for each question.",
    secure_threshold_percent: 80,
    developing_threshold_percent: 50,
    exclude_from_spelling: true,
    questions: [
      {
        question_id: "kind-q1",
        prompt:
          "What did Daniel notice when he was working long days in New York City?",
        options: [
          { option_id: "kind-q1-a", label: "There were too many unhealthy snacks everywhere." },
          { option_id: "kind-q1-b", label: "He couldn't find a healthy snack he felt good about eating." },
          { option_id: "kind-q1-c", label: "He wanted to open a restaurant instead of a bar company." },
          { option_id: "kind-q1-d", label: "He was too tired to eat anything at all." },
        ],
        correct_option_id: "kind-q1-b",
        explanation:
          "Daniel's idea for KIND began because he could not find a healthy snack he actually felt good about eating during long work days.",
      },
      {
        question_id: "kind-q2",
        prompt: "How did Daniel make the very first KIND bars?",
        options: [
          { option_id: "kind-q2-a", label: "In a big, modern factory with machines." },
          { option_id: "kind-q2-b", label: "He bought them from another company and repackaged them." },
          { option_id: "kind-q2-c", label: "He made them completely by hand." },
          { option_id: "kind-q2-d", label: "He hired 100 workers to make them in a kitchen." },
        ],
        correct_option_id: "kind-q2-c",
        explanation:
          "At the beginning there was no big factory. Daniel made the first bars by hand and delivered them himself.",
      },
      {
        question_id: "kind-q3",
        prompt: "What does Daniel say is the difference between being nice and being kind?",
        options: [
          { option_id: "kind-q3-a", label: "Being kind means giving away free products; being nice means charging for them." },
          { option_id: "kind-q3-b", label: "They mean exactly the same thing." },
          { option_id: "kind-q3-c", label: "Being nice avoids saying hard truths; being kind takes courage to say what needs to be said." },
          { option_id: "kind-q3-d", label: "Being kind is easier because you do not need to spend any money." },
        ],
        correct_option_id: "kind-q3-c",
        explanation:
          "Daniel says being kind takes courage. It means saying what needs to be said, not just avoiding discomfort.",
      },
      {
        question_id: "kind-q4",
        prompt:
          "What was the smartest thing Daniel said he did when KIND first started doing well?",
        options: [
          { option_id: "kind-q4-a", label: "He immediately launched lots of new products." },
          { option_id: "kind-q4-b", label: "He hired hundreds of staff straightaway." },
          { option_id: "kind-q4-c", label: "He sold the company as quickly as possible." },
          { option_id: "kind-q4-d", label: "He said no to launching other products and stayed focused on one thing." },
        ],
        correct_option_id: "kind-q4-d",
        explanation:
          "When KIND first started doing well, Daniel said the smartest thing he did was stay focused on one thing rather than launching too many products.",
      },
      {
        question_id: "kind-q5",
        prompt:
          "What is the most important thing Daniel looks for in entrepreneurs on Shark Tank?",
        options: [
          { option_id: "kind-q5-a", label: "That they have already made lots of money." },
          { option_id: "kind-q5-b", label: "That they have integrity and are good human beings." },
          { option_id: "kind-q5-c", label: "That they have a very flashy pitch and a fancy office." },
          { option_id: "kind-q5-d", label: "That they are already famous." },
        ],
        correct_option_id: "kind-q5-b",
        explanation:
          "For Daniel, integrity matters most. He looks first for entrepreneurs who are good human beings and tell the truth.",
      },
    ],
  },
  {
    block_id: "kind-lessons-callout",
    block_type: "info_cards",
    title: "Big lessons from Daniel",
    body: "Here are the most important lessons Daniel's story teaches us.",
    cards: [
      { card_id: "kind-lesson-1", icon: "🔍", title: "Spot a gap", body: "Daniel noticed a problem and created the solution. Look around you for what people need that does not exist yet." },
      { card_id: "kind-lesson-2", icon: "🎯", title: "Stay focused", body: "Do one thing brilliantly before you do many things badly." },
      { card_id: "kind-lesson-3", icon: "🌱", title: "Learn from mistakes", body: "Mistakes are not failures — they are lessons in disguise." },
      { card_id: "kind-lesson-4", icon: "⭐", title: "Quality matters", body: "Customers notice when your standards stay high." },
      { card_id: "kind-lesson-5", icon: "💬", title: "Be kind, not just nice", body: "Kindness takes courage and honesty." },
      { card_id: "kind-lesson-6", icon: "💰", title: "Be resourceful", body: "You do not need to be rich to start — you need to be creative." },
    ],
  },
  {
    block_id: "kind-r1",
    block_type: "question_textarea",
    label: "Which lesson from Daniel inspires you the most, and why?",
    placeholder: "Write your thoughts here...",
    rows: 5,
    required: false,
    exclude_from_spelling: false,
    save_affordance: "auto",
  },
  {
    block_id: "kind-r2",
    block_type: "question_textarea",
    label: "What inspired the name of your snack bar, and what makes it different?",
    placeholder: "I named my bar... because... and what makes it special is...",
    rows: 5,
    required: false,
    exclude_from_spelling: false,
    save_affordance: "auto",
  },
  {
    block_id: "kind-r3",
    block_type: "question_textarea",
    label: "Daniel made lots of mistakes before he succeeded. How do you feel about making mistakes in your own life?",
    placeholder: "I think mistakes are... because...",
    rows: 5,
    required: false,
    exclude_from_spelling: false,
    save_affordance: "auto",
  },
  {
    block_id: "kind-r4",
    block_type: "question_textarea",
    label: "Can you think of a gap in the world? What do people everywhere struggle to find or get?",
    placeholder: "I think a gap in the world is... because people cannot easily find...",
    rows: 5,
    required: false,
    exclude_from_spelling: false,
    save_affordance: "auto",
  },
];

const founderStoryLessonBlocks: StructuredLessonBlock[] = [
  {
    block_id: "founder-story-heading",
    block_type: "heading",
    eyebrow: "Lesson Two · Founder Stories",
    heading: "What's Your Story?",
  },
  {
    block_id: "founder-story-intro",
    block_type: "section_intro",
    eyebrow: "Entrepreneur Studio",
    title: "What's Your Story?",
    body: "Every great founder has a story. Daniel told his. Now it is your turn to discover and tell yours.",
  },
  {
    block_id: "founder-story-link",
    block_type: "action_link",
    label: "Re-read Daniel's interview",
    url: "https://fortune.com/2024/10/20/kind-daniel-lubetzky-secrets-to-success/",
    style: "secondary",
  },
  {
    block_id: "founder-story-note",
    block_type: "callout",
    title: "How to save this lesson",
    content:
      "<p>Type in the answer boxes here, then use the main save button underneath the lesson in Scarlett's Spells. If it is sent back, your answers stay in the boxes and parent feedback can appear beside the matching question.</p>",
    tone: "tip",
  },
  {
    block_id: "founder-story-part-1",
    block_type: "section_intro",
    eyebrow: "Part One · Writing",
    title: "Build your founder story, question by question",
    body: "Daniel was asked seven questions that revealed who he is as a founder. Answer the same questions for yourself.",
  },
  {
    block_id: "founder-story-q1-context",
    block_type: "callout",
    title: "Daniel said...",
    content:
      "<p>\"My dad arrived in Mexico with a third-grade education and no money. By the time he passed away he spoke nine languages. He worked two or three factory shifts in a row. He was my greatest inspiration.\"</p>",
    tone: "tip",
  },
  {
    block_id: "founder-story-q1",
    block_type: "question_textarea",
    label: "Where did you grow up, and who has shaped the way you think?",
    placeholder:
      "Where did you grow up? Is there someone — a parent, grandparent, friend — who has inspired or shaped the way you think? What did they teach you without even knowing it?",
    rows: 6,
    save_affordance: "auto",
    exclude_from_spelling: false,
  },
  {
    block_id: "founder-story-q2-context",
    block_type: "callout",
    title: "Daniel said...",
    content:
      "<p>\"Even when I was 8 years old I was already doing magic shows, trying to force people into letting me perform. I also sold watches at flea markets and eventually built a whole network of students selling for me.\"</p>",
    tone: "tip",
  },
  {
    block_id: "founder-story-q2",
    block_type: "question_textarea",
    label: "What were your very first business ideas?",
    placeholder:
      "Have you ever made, sold, or created something — even just for fun? What was it? When did you first get the feeling you wanted to build something of your own?",
    rows: 6,
    save_affordance: "auto",
    exclude_from_spelling: false,
  },
  {
    block_id: "founder-story-q3-context",
    block_type: "callout",
    title: "Daniel said...",
    content:
      "<p>\"On those long days when I was skipping lunch I could not find anything good to eat. I was spending all my time in grocery stores and I couldn't find something that was wholesome but also convenient, healthy but also tasty. And I thought — if I can't find it, I'm sure others have that need too.\"</p>",
    tone: "success",
  },
  {
    block_id: "founder-story-q3",
    block_type: "question_textarea",
    label: "What problem did you notice that nobody was solving?",
    placeholder:
      "What made you want to create your snack? Was there a moment when you thought 'I wish this existed'? What gap in the world are you trying to fill?",
    rows: 6,
    save_affordance: "auto",
    exclude_from_spelling: false,
  },
  {
    block_id: "founder-story-q4-context",
    block_type: "callout",
    title: "Daniel said...",
    content:
      "<p>\"Every competitor takes a bunch of ingredients, macerates them beyond recognition — you don't know what you're eating. With KIND we wanted to celebrate nature. Use whole nuts, whole fruits, whole grains, preserved so you can see exactly what's inside.\"</p>",
    tone: "success",
  },
  {
    block_id: "founder-story-q4",
    block_type: "question_textarea",
    label: "What makes your product different from everything else out there?",
    placeholder:
      "What makes your snack bar different? Think about your ingredients, your values, your name, your promise. Why would someone choose yours over everything else on the shelf?",
    rows: 6,
    save_affordance: "auto",
    exclude_from_spelling: false,
  },
  {
    block_id: "founder-story-q5-context",
    block_type: "callout",
    title: "Daniel said...",
    content:
      "<p>\"The life of an entrepreneur can be very romantic, but it can also be sleepless. I was terrified of selling and losing my baby. I was terrified of not selling and choking on debt. I didn't sleep well for many years. But right now I can be nostalgic and proud — back then I was frankly just scared.\"</p>",
    tone: "warning",
  },
  {
    block_id: "founder-story-q5",
    block_type: "question_textarea",
    label: "What has been the hardest part so far, and how have you faced it?",
    placeholder:
      "Has anything felt difficult, scary or uncertain as you've worked on your snack bar? Maybe a moment of self-doubt? How did you push through it — or how are you pushing through it now?",
    rows: 6,
    save_affordance: "auto",
    exclude_from_spelling: false,
  },
  {
    block_id: "founder-story-q6-context",
    block_type: "callout",
    title: "Daniel said...",
    content:
      "<p>\"A brand is a promise, and a great brand is a promise well-kept. If you do not know what you are here to do — and what you are here NOT to do — you might become everything to everyone and end up being nothing to no one.\"</p>",
    tone: "warning",
  },
  {
    block_id: "founder-story-q6",
    block_type: "question_textarea",
    label: "What do you stand for, and what are the values behind your brand?",
    placeholder:
      "What does your snack bar stand for? What three words describe your brand? What will you always do — and what will you never do?",
    rows: 6,
    save_affordance: "auto",
    exclude_from_spelling: false,
  },
  {
    block_id: "founder-story-q7-context",
    block_type: "callout",
    title: "Daniel said...",
    content:
      "<p>\"We reached the heights we did — a multibillion-dollar valuation — with only a $5.2 million lifetime investment. I really try not to lose that grit and authenticity. And I get scared that the day I lose it, it will mark that I've changed who I am.\"</p>",
    tone: "default",
  },
  {
    block_id: "founder-story-q7",
    block_type: "question_textarea",
    label: "Where do you want to take this, and what is the dream?",
    placeholder:
      "If your snack bar became as big as KIND one day — what would that look like? What impact do you want it to have on the world? And what do you never want to lose along the way?",
    rows: 6,
    save_affordance: "auto",
    exclude_from_spelling: false,
  },
  {
    block_id: "founder-story-divider-speaking",
    block_type: "titled_divider",
    title: "Part Two — Speaking",
  },
  {
    block_id: "founder-story-speaking",
    block_type: "info_cards",
    title: "Now say it out loud",
    body: "Writing your story is only half the job. Now rehearse it so it sounds alive.",
    cards: [
      { card_id: "speak-1", icon: "📖", title: "Read", body: "Read your story to yourself and change any parts that do not sound like you." },
      { card_id: "speak-2", icon: "🪞", title: "Speak", body: "Say it to a mirror and notice where you rush or go quiet." },
      { card_id: "speak-3", icon: "⏱️", title: "Shrink it", body: "Tell the whole story in 60 seconds. Keep only what really matters." },
      { card_id: "speak-4", icon: "🎙️", title: "Rehearse", body: "Use pauses, energy, and expression so your story feels real, not recited." },
    ],
  },
  {
    block_id: "founder-story-divider-interview",
    block_type: "titled_divider",
    title: "Part Three — The Interview",
  },
  {
    block_id: "founder-story-interview",
    block_type: "info_cards",
    title: "Get ready — these questions are coming",
    body: "You do not need to memorise a script. You need to know your story well enough that it flows naturally.",
    cards: [
      { card_id: "interview-1", icon: "🌍", title: "Opening question", body: "Tell me about yourself — who are you and where did you grow up?" },
      { card_id: "interview-2", icon: "💡", title: "The spark", body: "Where did the idea for your snack bar come from?" },
      { card_id: "interview-3", icon: "🌰", title: "The product", body: "What is in your snack bar and why is it different?" },
      { card_id: "interview-4", icon: "🛡️", title: "The challenge", body: "What has been hardest, and what kept you going?" },
      { card_id: "interview-5", icon: "⭐", title: "Your values", body: "What does your brand stand for?" },
      { card_id: "interview-6", icon: "🚀", title: "The dream", body: "If this became huge one day, what would that mean to you?" },
    ],
  },
];

const customerLessonBlocks: StructuredLessonBlock[] = [
  {
    block_id: "customer-heading",
    block_type: "heading",
    eyebrow: "Phase One · Module 1",
    heading: "The Customer",
  },
  {
    block_id: "customer-intro",
    block_type: "section_intro",
    eyebrow: "Entrepreneur Studio",
    title: "Customer Research",
    body: "Before you can sell anything, you need to know exactly who you are selling to. Today you will find your customer, understand them deeply, and write a statement that puts them at the centre of everything.",
  },
  {
    block_id: "customer-divider-1",
    block_type: "titled_divider",
    title: "Part 1 — The Problem",
  },
  {
    block_id: "customer-problem-intro",
    block_type: "section_intro",
    eyebrow: "Start here",
    title: "What problem am I solving?",
    body: "Carry your best thinking forward from your earlier lesson. Write the problem clearly and the product idea that goes with it.",
  },
  {
    block_id: "customer-problem",
    block_type: "question_textarea",
    label: "The problem I am solving",
    placeholder: "Write the problem your product solves...",
    rows: 4,
    exclude_from_spelling: false,
  },
  {
    block_id: "customer-product-idea",
    block_type: "question_text",
    label: "My product idea",
    placeholder: "Write the product idea from your earlier work...",
    exclude_from_spelling: false,
  },
  {
    block_id: "customer-divider-2",
    block_type: "titled_divider",
    title: "Part 2 — Five Customers",
  },
  {
    block_id: "customer-five-intro",
    block_type: "section_intro",
    eyebrow: "Explore",
    title: "Who could buy this product?",
    body: "Think broadly. Who could the buyer be? Who would eat or use it? List five different customer types below.",
  },
  {
    block_id: "customer-five-cards",
    block_type: "info_cards",
    title: "Think about...",
    body: "Use these prompts to help you think of real kinds of customers.",
    cards: [
      { card_id: "customer-card-1", icon: "👩", title: "Parents", body: "People buying for their children often care about trust, ease, and excitement." },
      { card_id: "customer-card-2", icon: "🎁", title: "Gift-givers", body: "Some people may buy because they want something thoughtful and special." },
      { card_id: "customer-card-3", icon: "🏋️", title: "Health-focused adults", body: "Think about people who want convenience without junk ingredients." },
      { card_id: "customer-card-4", icon: "🎉", title: "Event buyers", body: "Parties, offices, and celebrations can create a different reason to buy." },
    ],
  },
  {
    block_id: "customer-five-table",
    block_type: "question_table",
    label: "My five customer types",
    row_count: 5,
    columns: [
      { column_id: "customer_type", label: "Customer type", input_type: "text", placeholder: "e.g. Health-conscious mum" },
      { column_id: "why_like_it", label: "Why they would like it", input_type: "text", placeholder: "e.g. Wants better treats for her children" },
      {
        column_id: "role",
        label: "Eater / Buyer / Both",
        input_type: "select",
        options: [
          { value: "buyer", label: "Buyer" },
          { value: "eater", label: "Eater" },
          { value: "both", label: "Both" },
        ],
      },
    ],
  },
  {
    block_id: "customer-divider-3",
    block_type: "titled_divider",
    title: "Part 3 — Customer Choice Test",
  },
  {
    block_id: "customer-choice-intro",
    block_type: "section_intro",
    eyebrow: "Choose",
    title: "Now choose your best customer",
    body: "For each question, choose one of your five customer types, then explain why.",
  },
  {
    block_id: "customer-choice-1",
    block_type: "question_choice_single",
    label: "Which customer has the strongest reason to buy?",
    options: [
      { value: "customer-1", label: "Customer 1" },
      { value: "customer-2", label: "Customer 2" },
      { value: "customer-3", label: "Customer 3" },
      { value: "customer-4", label: "Customer 4" },
      { value: "customer-5", label: "Customer 5" },
    ],
    exclude_from_spelling: true,
  },
  {
    block_id: "customer-choice-1-why",
    block_type: "question_textarea",
    label: "Why?",
    placeholder: "Explain your thinking...",
    rows: 3,
  },
  {
    block_id: "customer-choice-2",
    block_type: "question_choice_single",
    label: "Which customer would understand the product fastest?",
    options: [
      { value: "customer-1", label: "Customer 1" },
      { value: "customer-2", label: "Customer 2" },
      { value: "customer-3", label: "Customer 3" },
      { value: "customer-4", label: "Customer 4" },
      { value: "customer-5", label: "Customer 5" },
    ],
    exclude_from_spelling: true,
  },
  {
    block_id: "customer-choice-2-why",
    block_type: "question_textarea",
    label: "Why?",
    placeholder: "Explain your thinking...",
    rows: 3,
  },
  {
    block_id: "customer-choice-3",
    block_type: "question_choice_single",
    label: "Which customer is easiest to reach?",
    options: [
      { value: "customer-1", label: "Customer 1" },
      { value: "customer-2", label: "Customer 2" },
      { value: "customer-3", label: "Customer 3" },
      { value: "customer-4", label: "Customer 4" },
      { value: "customer-5", label: "Customer 5" },
    ],
    exclude_from_spelling: true,
  },
  {
    block_id: "customer-choice-3-why",
    block_type: "question_textarea",
    label: "Why?",
    placeholder: "Explain your thinking...",
    rows: 3,
  },
  {
    block_id: "customer-choice-4",
    block_type: "question_choice_single",
    label: "Which customer might buy again?",
    options: [
      { value: "customer-1", label: "Customer 1" },
      { value: "customer-2", label: "Customer 2" },
      { value: "customer-3", label: "Customer 3" },
      { value: "customer-4", label: "Customer 4" },
      { value: "customer-5", label: "Customer 5" },
    ],
    exclude_from_spelling: true,
  },
  {
    block_id: "customer-choice-4-why",
    block_type: "question_textarea",
    label: "Why?",
    placeholder: "Explain your thinking...",
    rows: 3,
  },
  {
    block_id: "customer-choice-5",
    block_type: "question_choice_single",
    label: "Which customer would pay enough for a profit?",
    options: [
      { value: "customer-1", label: "Customer 1" },
      { value: "customer-2", label: "Customer 2" },
      { value: "customer-3", label: "Customer 3" },
      { value: "customer-4", label: "Customer 4" },
      { value: "customer-5", label: "Customer 5" },
    ],
    exclude_from_spelling: true,
  },
  {
    block_id: "customer-choice-5-why",
    block_type: "question_textarea",
    label: "Why?",
    placeholder: "Explain your thinking...",
    rows: 3,
  },
  {
    block_id: "customer-choice-6",
    block_type: "question_choice_single",
    label: "Which customer fits the product best?",
    options: [
      { value: "customer-1", label: "Customer 1" },
      { value: "customer-2", label: "Customer 2" },
      { value: "customer-3", label: "Customer 3" },
      { value: "customer-4", label: "Customer 4" },
      { value: "customer-5", label: "Customer 5" },
    ],
    exclude_from_spelling: true,
  },
  {
    block_id: "customer-choice-6-why",
    block_type: "question_textarea",
    label: "Why?",
    placeholder: "Explain your thinking...",
    rows: 3,
  },
  {
    block_id: "customer-best",
    block_type: "question_textarea",
    label: "My best customer is...",
    placeholder: "Explain who appeared most often and why...",
    rows: 4,
  },
  {
    block_id: "customer-divider-4",
    block_type: "titled_divider",
    title: "Part 4 — Customer Profile",
  },
  {
    block_id: "customer-profile-intro",
    block_type: "section_intro",
    eyebrow: "Know them",
    title: "Who is my ideal customer?",
    body: "Build a real profile of the one person who would love your product most.",
  },
  {
    block_id: "customer-profile-example",
    block_type: "info_cards",
    title: "Example profile",
    body: "Healthy Hannah — Age 35",
    cards: [
      { card_id: "profile-card-1", title: "Buys already", body: "Fruit bars, yoghurt, oat bars, healthier snacks" },
      { card_id: "profile-card-2", title: "Problem", body: "Wants treats for her children that feel better than sweets" },
      { card_id: "profile-card-3", title: "Wants", body: "Something tasty, natural, and easy" },
      { card_id: "profile-card-4", title: "Trust needs", body: "Clear ingredients, allergen info, hygiene, reviews" },
    ],
  },
  {
    block_id: "customer-profile-name",
    block_type: "question_text",
    label: "Name",
    placeholder: "e.g. Healthy Hannah",
  },
  {
    block_id: "customer-profile-age",
    block_type: "question_text",
    label: "Age",
    placeholder: "e.g. 35",
  },
  {
    block_id: "customer-profile-hobbies",
    block_type: "question_text",
    label: "Hobbies and interests",
    placeholder: "e.g. Yoga, cooking, reading...",
  },
  {
    block_id: "customer-profile-where",
    block_type: "question_text",
    label: "Where do they spend time?",
    placeholder: "e.g. Instagram, markets, local cafes...",
  },
  {
    block_id: "customer-profile-buys",
    block_type: "question_text",
    label: "What do they buy already?",
    placeholder: "e.g. Fruit bars, yoghurt, oat bars...",
  },
  {
    block_id: "customer-profile-problem",
    block_type: "question_textarea",
    label: "What problem do they have?",
    placeholder: "Describe the problem from their point of view...",
    rows: 4,
  },
  {
    block_id: "customer-profile-want",
    block_type: "question_textarea",
    label: "What do they want?",
    placeholder: "Describe what they are really hoping for...",
    rows: 4,
  },
  {
    block_id: "customer-profile-stop",
    block_type: "question_textarea",
    label: "What would stop them buying?",
    placeholder: "What worries or objections might they have?",
    rows: 4,
  },
  {
    block_id: "customer-profile-pay",
    block_type: "question_textarea",
    label: "How much might they pay?",
    placeholder: "Estimate what feels reasonable to them...",
    rows: 3,
  },
  {
    block_id: "customer-profile-discover",
    block_type: "question_choice_multi",
    label: "Where would they discover the product?",
    options: [
      { value: "instagram", label: "Instagram" },
      { value: "tiktok", label: "TikTok" },
      { value: "gym", label: "Gym" },
      { value: "market", label: "Market" },
      { value: "cafe", label: "Cafe" },
      { value: "website", label: "Website" },
      { value: "friend", label: "Friend" },
      { value: "shop", label: "Shop" },
      { value: "event", label: "Event" },
      { value: "other", label: "Other" },
    ],
    exclude_from_spelling: true,
  },
  {
    block_id: "customer-profile-message",
    block_type: "question_text",
    label: "Best product message for this customer",
    placeholder: "Write the message that would make them lean in...",
  },
  {
    block_id: "customer-divider-5",
    block_type: "titled_divider",
    title: "Part 5 — Customer Statement",
  },
  {
    block_id: "customer-statement-intro",
    block_type: "section_intro",
    eyebrow: "Bring it together",
    title: "The one-sentence customer statement",
    body: "Complete the sentence using everything you discovered today.",
  },
  {
    block_id: "customer-statement-example",
    block_type: "callout",
    title: "Example",
    content: "<p>My product is for <strong>parents who want healthier treats for their children</strong> who want <strong>something tasty and natural</strong> because <strong>they want to feel good about what their children are eating without losing the excitement of a treat.</strong></p>",
    tone: "success",
  },
  {
    block_id: "customer-statement-for",
    block_type: "question_text",
    label: "My product is for...",
    placeholder: "Who is it for?",
  },
  {
    block_id: "customer-statement-want",
    block_type: "question_text",
    label: "...who want...",
    placeholder: "What do they want?",
  },
  {
    block_id: "customer-statement-because",
    block_type: "question_textarea",
    label: "...because...",
    placeholder: "Why does this matter to them?",
    rows: 4,
  },
];

const customerResearchLessonBlocks: StructuredLessonBlock[] = [
  {
    block_id: "research-heading",
    block_type: "heading",
    eyebrow: "Entrepreneur Studio",
    heading: "Customer Research",
  },
  {
    block_id: "research-intro",
    block_type: "section_intro",
    eyebrow: "Interview",
    title: "Ask, listen carefully, and notice patterns",
    body: "Use this page to interview five possible customers and record what they really say.",
  },
  {
    block_id: "research-rule",
    block_type: "callout",
    title: "Rule",
    content: "<p>Do not argue with their answers. The entrepreneur's job is to listen.</p>",
    tone: "warning",
  },
  {
    block_id: "research-interview-well",
    block_type: "info_cards",
    title: "How to interview well",
    body: "These reminders help you collect useful answers instead of trying to get people to agree with you.",
    cards: [
      { card_id: "research-tip-1", icon: "🎧", title: "Ask exactly what they already do", body: "Start with what they buy now, not what you hope they might buy later." },
      { card_id: "research-tip-2", icon: "⏳", title: "Let silence do some work", body: "If they pause, wait. People often give the most honest answer second." },
      { card_id: "research-tip-3", icon: "💭", title: "Notice emotion", body: "If they sound excited, doubtful, confused, or uninterested, write that down too." },
    ],
  },
  {
    block_id: "research-divider-1",
    block_type: "titled_divider",
    title: "Part 1 — Interviews",
  },
  {
    block_id: "research-interview-intro",
    block_type: "section_intro",
    eyebrow: "Your task",
    title: "Interview five people who might be customers",
    body: "Ask each person the same questions so you can compare their answers fairly.",
  },
  {
    block_id: "research-interviews",
    block_type: "question_repeatable_interview",
    label: "Customer interviews",
    repeat_count: 5,
    questions: [
      { question_id: "person-name", prompt: "Who did you speak to?", placeholder: "e.g. Parent at the park" },
      { question_id: "buy-now", prompt: "What snacks or treats do you buy now?", placeholder: "Write what they said..." },
      { question_id: "when-buy", prompt: "When do you buy them?", placeholder: "Write what they said..." },
      { question_id: "like", prompt: "What do you like about them?", placeholder: "Write what they said..." },
      { question_id: "dislike", prompt: "What do you dislike about them?", placeholder: "Write what they said..." },
      { question_id: "buy-this", prompt: "Would you buy this product? Why or why not?", placeholder: "Write what they said..." },
      { question_id: "pay", prompt: "How much would you expect to pay?", placeholder: "Write what they said..." },
      { question_id: "trust", prompt: "What would make you trust it?", placeholder: "Write what they said..." },
      { question_id: "regular", prompt: "Would you buy it once, or regularly?", placeholder: "Write what they said..." },
      { question_id: "gift", prompt: "Would you buy it as a gift?", placeholder: "Write what they said..." },
      { question_id: "stop", prompt: "What would stop you buying it?", placeholder: "Write what they said..." },
    ],
  },
  {
    block_id: "research-divider-2",
    block_type: "titled_divider",
    title: "Part 2 — Patterns",
  },
  {
    block_id: "research-patterns-intro",
    block_type: "section_intro",
    eyebrow: "Notice",
    title: "What patterns did you hear?",
    body: "Step back and compare the answers. What came up again and again?",
  },
  {
    block_id: "research-patterns-table",
    block_type: "question_table",
    label: "Pattern finder",
    row_count: 4,
    columns: [
      { column_id: "pattern", label: "Pattern", input_type: "text", placeholder: "e.g. People want healthier treats" },
      { column_id: "evidence", label: "Evidence from interviews", input_type: "textarea", placeholder: "What did people actually say?" },
      { column_id: "what-it-means", label: "What this means for my product", input_type: "textarea", placeholder: "How should this shape your product idea?" },
    ],
  },
  {
    block_id: "research-best-insight",
    block_type: "question_textarea",
    label: "My most important customer insight",
    placeholder: "What is the biggest thing you learned from these interviews?",
    rows: 5,
  },
];

export const STRUCTURED_LESSON_PRESETS: StructuredLessonPreset[] = [
  {
    id: "problem-lesson",
    label: "Problem lesson",
    description: "A full writing-led founder lesson based on What Problem Do I Want To Solve?",
    lesson: {
      version: 1,
      theme: "scarlett-default",
      title: "What Problem Do I Want To Solve?",
      blocks: cloneBlocks(problemLessonBlocks),
    },
  },
  {
    id: "kind-comprehension",
    label: "Daniel / KIND comprehension",
    description: "A structured founder-story comprehension lesson with quiz scoring and reflection questions.",
    lesson: {
      version: 1,
      theme: "scarlett-default",
      title: "Daniel's Big Snack Idea!",
      blocks: cloneBlocks(kindLessonBlocks),
    },
  },
  {
    id: "founder-story",
    label: "Founder story",
    description: "A structured writing lesson based on Daniel's founder interview, with seven story-building questions.",
    lesson: {
      version: 1,
      theme: "scarlett-default",
      title: "What's Your Story?",
      blocks: cloneBlocks(founderStoryLessonBlocks),
    },
  },
  {
    id: "customer-lesson",
    label: "The Customer",
    description: "A structured customer-definition lesson covering customer types, customer choice, profile building, and a final customer statement.",
    lesson: {
      version: 1,
      theme: "scarlett-default",
      title: "The Customer",
      blocks: cloneBlocks(customerLessonBlocks),
    },
  },
  {
    id: "customer-research",
    label: "Customer Research",
    description: "A structured interview lesson for gathering five customer conversations and finding patterns.",
    lesson: {
      version: 1,
      theme: "scarlett-default",
      title: "Customer Research",
      blocks: cloneBlocks(customerResearchLessonBlocks),
    },
  },
];

export function getStructuredLessonPreset(
  presetId: string,
): StructuredLessonPreset | null {
  return STRUCTURED_LESSON_PRESETS.find((preset) => preset.id === presetId) ?? null;
}

export function cloneStructuredLessonDocument(
  document: StructuredLessonDocument,
): StructuredLessonDocument {
  return JSON.parse(JSON.stringify(document)) as StructuredLessonDocument;
}
