"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.TRICKY_WORD_SET = exports.TRICKY_WORDS = void 0;
exports.TRICKY_WORDS = [
    "again",
    "answer",
    "beautiful",
    "because",
    "busy",
    "children",
    "clothes",
    "could",
    "does",
    "done",
    "door",
    "every",
    "eye",
    "father",
    "friend",
    "favourite",
    "floor",
    "four",
    "great",
    "half",
    "heard",
    "heart",
    "hour",
    "house",
    "laugh",
    "move",
    "money",
    "most",
    "mother",
    "one",
    "once",
    "only",
    "people",
    "pretty",
    "prove",
    "parents",
    "school",
    "should",
    "steak",
    "sugar",
    "their",
    "there",
    "they",
    "through",
    "two",
    "water",
    "were",
    "whole",
    "would",
    "who",
    "young",
];
exports.TRICKY_WORD_SET = new Set(exports.TRICKY_WORDS);
