import { compileDynamicPrefixWordLabPayload, selectDynamicPrefixWordLab, validateDynamicPrefixWordLabPayload, type DynamicPrefixProfile, type DynamicPrefixWord } from "../lib/adle/morphology/dynamic-prefix-word-lab";
import type { LearningItemFact } from "../lib/adle/learning-items";

function assert(value: unknown, message: string): asserts value { if (!value) throw new Error(`FAIL: ${message}`); }
function word(id: string, displayWord: string, transfer = false): DynamicPrefixWord { const base = displayWord.slice(2); const dictationSentence = `Please write ${displayWord}.`; return { canonicalWordId: id, displayWord, audioText: dictationSentence, baseWord: base, baseMeaning: `to ${base}`, derivedMeaning: `not ${base}`, effect: "not", parts: [{ id: `${id}-prefix`, text: "un", sourceText: "un", role: "prefix", start: 0, end: 2 }, { id: `${id}-base`, text: base, sourceText: base, role: "base", start: 2, end: displayWord.length }], joins: [{ afterPartId: `${id}-prefix`, beforePartId: `${id}-base`, joinType: "none" }], splitPoints: [2], dictationSentence, dictationTargetTokenIndex: 2, approvedTransfer: transfer }; }
function profile(key = "D4_MOR_PREFIXES_UN", enabled = true): DynamicPrefixProfile { const words = [word("a", "unfair"), word("b", "unkind"), word("c", "untidy"), word("d", "unwell"), word("t1", "unhappy", true), word("t2", "unwise", true), word("t3", "unpack", true)]; return { microSkillKey: key, productionEnabled: enabled, prefixText: "un", prefixLabel: "un-", prefixMeaning: "not or reverse", meaningBins: [{ id: "not", label: "NOT", description: "not" }, { id: "reverse", label: "REVERSE", description: "reverse" }], wordsByCanonicalId: new Map(words.map((entry) => [entry.canonicalWordId, entry])), transferCanonicalWordIds: ["t1", "t2", "t3"], prefixChoices: [{ text: "un", label: "un-", outcome: "unfair", meaning: "not fair", status: "target" }], reflection: { promptKey: "prefix-notice-v2", promptText: "What did the prefix change?" } }; }
function item(id: string, skill: string, intakeOn: string, reteach = false, sourceKind: LearningItemFact["sourceKind"] = "verified_misspelling"): LearningItemFact { return { learningItemId: `li-${id}-${intakeOn}`, childId: "child", canonicalWordId: id, microSkillKey: skill, itemStatus: reteach ? "pending_reteach" : "pending", sourceKind, sourceRef: `verified:${id}`, sourceAttemptText: "private", reteachPriority: reteach, ejectedOn: reteach ? intakeOn : null, intakeOn, rowStatus: "active" }; }
const un = profile(); const re = profile("D4_MOR_PREFIXES_RE_PRE");
for (const count of [1, 2, 3, 4, 5]) { const selection = selectDynamicPrefixWordLab({ profiles: [un], learningItems: ["a", "b", "c", "d", "a"].slice(0, count).map((id, index) => item(id, un.microSkillKey, `2026-07-0${index + 1}`)) }); assert(selection, `${count} authentic targets select with approved transfers`); const payload = compileDynamicPrefixWordLabPayload(selection); assert(payload && validateDynamicPrefixWordLabPayload(payload), `${count} snapshot compiles`); assert(payload.authenticCanonicalWordIds.length === Math.min(count, 4), `overflow stays pending at ${count}`); }
const tied = selectDynamicPrefixWordLab({ profiles: [re, un], learningItems: [item("a", un.microSkillKey, "2026-07-03"), item("b", re.microSkillKey, "2026-07-04", true)] }); assert(tied?.profile.microSkillKey === re.microSkillKey, "reteach wins target-count tie");
const old = selectDynamicPrefixWordLab({ profiles: [re, un], learningItems: [item("a", un.microSkillKey, "2026-07-02"), item("b", re.microSkillKey, "2026-07-03")] }); assert(old?.profile.microSkillKey === un.microSkillKey, "oldest target wins after reteach tie");
const stable = selectDynamicPrefixWordLab({ profiles: [profile("D4_MOR_PREFIXES_RE_PRE"), profile("D4_MOR_PREFIXES_DIS_MIS")], learningItems: [item("a", "D4_MOR_PREFIXES_RE_PRE", "2026-07-02"), item("a", "D4_MOR_PREFIXES_DIS_MIS", "2026-07-02")] }); assert(stable?.profile.microSkillKey === "D4_MOR_PREFIXES_DIS_MIS", "stable micro-skill key settles a full tie");
assert(selectDynamicPrefixWordLab({ profiles: [profile("D4_MOR_PREFIXES_UN", false)], learningItems: [item("a", un.microSkillKey, "2026-07-01")] }) === null, "non-production profile cannot select");
assert(selectDynamicPrefixWordLab({ profiles: [{ ...un, transferCanonicalWordIds: [] }], learningItems: [item("a", un.microSkillKey, "2026-07-01")] }) === null, "insufficient reviewed transfers fail closed");
assert(selectDynamicPrefixWordLab({ profiles: [un], learningItems: [item("a", un.microSkillKey, "2026-07-01", false, "probe_miss")] }) === null, "non-authentic sources cannot select");
const missingDictation = selectDynamicPrefixWordLab({ profiles: [un], learningItems: [item("a", un.microSkillKey, "2026-07-01")] })!; missingDictation.profile.wordsByCanonicalId.get("a")!.dictationSentence = ""; assert(compileDynamicPrefixWordLabPayload(missingDictation) === null, "missing reviewed dictation fails closed");
const audioProfile = profile(); const mismatchedAudio = selectDynamicPrefixWordLab({ profiles: [audioProfile], learningItems: [item("a", audioProfile.microSkillKey, "2026-07-01")] })!; mismatchedAudio.profile.wordsByCanonicalId.get("a")!.audioText = "Different audio text."; assert(compileDynamicPrefixWordLabPayload(mismatchedAudio) === null, "non-matching sentence/audio fails closed");
const mixedWords = [
  ["disagree", "dis", "agree"], ["mislead", "mis", "lead"], ["disappear", "dis", "appear"], ["misspell", "mis", "spell"],
].map(([id, prefix, base]) => { const dictationSentence = `Please write ${id}.`; return { canonicalWordId: id, displayWord: id, audioText: dictationSentence, baseWord: base, baseMeaning: `the meaning of ${base}`, derivedMeaning: `the meaning of ${id}`, effect: "not" as const, parts: [{ id: `${id}-prefix`, text: prefix, sourceText: prefix, role: "prefix" as const, start: 0, end: prefix.length }, { id: `${id}-base`, text: base, sourceText: base, role: "base" as const, start: prefix.length, end: id.length }], joins: [{ afterPartId: `${id}-prefix`, beforePartId: `${id}-base`, joinType: "none" as const }], splitPoints: [prefix.length], prefixText: prefix, prefixLabel: `${prefix}-`, dictationSentence, dictationTargetTokenIndex: 2, approvedTransfer: true }; });
const mixed: DynamicPrefixProfile = { microSkillKey: "D4_MOR_PREFIXES_DIS_MIS", productionEnabled: true, meaningBins: [{ id: "not", label: "NOT", description: "not" }, { id: "wrong", label: "WRONG", description: "wrongly" }], wordsByCanonicalId: new Map(mixedWords.map((entry) => [entry.canonicalWordId, entry])), transferCanonicalWordIds: mixedWords.map((entry) => entry.canonicalWordId), prefixChoices: [{ text: "dis", label: "dis-", outcome: null, meaning: "opposite", status: "target" }, { text: "mis", label: "mis-", outcome: null, meaning: "wrongly", status: "target" }], reflection: { promptKey: "mixed-prefix", promptText: "What did the prefix change?" } };
const mixedSelection = selectDynamicPrefixWordLab({ profiles: [mixed], learningItems: [item("disagree", mixed.microSkillKey, "2026-07-01")] });
assert(mixedSelection, "mixed prefix profile selects with its own transfers");
const mixedPayload = compileDynamicPrefixWordLabPayload(mixedSelection);
assert(mixedPayload && validateDynamicPrefixWordLabPayload(mixedPayload), "mixed prefix snapshot compiles");
assert(mixedPayload.activities.discovery.map((card) => card.prefixLabel).join(",") === "dis-,mis-,dis-,mis-", "each discovery card carries its own approved prefix");
assert(mixedPayload.activities.build.canonicalWordId === "mislead" && mixedPayload.activities.build.baseWord === "lead" && mixedPayload.activities.build.choices.find((choice) => choice.status === "target")?.text === "mis" && mixedPayload.activities.build.choices.find((choice) => choice.text === "dis")?.status === "valid_alternative", "mixed profiles use a different approved prefix form for build while retaining valid alternatives");
console.log("PASS: dynamic Prefix Word Lab selector, transfer fill, overflow, and fail-closed regressions");
