#!/usr/bin/env node
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";

const root = resolve(import.meta.dirname, "..");
const guardedMigration = readFileSync(resolve(root, "supabase/migrations/20260808093000_fix_dynamic_affix_canonical_intake_persistence.sql"), "utf8");
const migration = readFileSync(resolve(root, "supabase/migrations/20260809100000_reconcile_dynamic_affix_canonical_intake_persistence.sql"), "utf8");
const rollbackProof = readFileSync(resolve(root, "scripts/sql/prove-adle-canonical-intake-persistence-local.sql"), "utf8");
const live = readFileSync(resolve(root, "lib/adle/loaders/canonical-intake-live.ts"), "utf8");

assert.match(live, /p_route_id: resolution\.routeId/);
assert.match(live, /p_route_version: resolution\.routeVersion/);
assert.match(migration, /drop function if exists public\.adle_persist_canonical_intake\([\s\S]*?date\s*\);/);
assert.match(migration, /drop function if exists public\.adle_persist_canonical_intake\([\s\S]*?date, text, text\s*\);/);
const argumentsBlock = migration.match(/create function public\.adle_persist_canonical_intake\(([\s\S]*?)\)\s*returns table/)?.[1];
assert(argumentsBlock, "reconciled canonical-intake function signature is missing");
assert.equal(argumentsBlock.match(/^\s*p_[a-z_]+\s+(?:uuid|text|date),?$/gm)?.length, 11, "reconciled canonical-intake function must expose exactly eleven arguments");
assert.match(migration, /Dynamic Affix candidate must request dynamic_affix_word_lab:v3/);
assert.match(migration, /v_route_id := 'dynamic_affix_word_lab';[\s\S]*v_route_version := 'v3'/);
assert.match(migration, /canonical_teaching_dictionary_suffix_profiles/);
assert.match(migration, /canonical_teaching_dictionary_suffix_members/);
assert.match(migration, /profile\.production_enabled = true/);
assert.match(migration, /member\.assignment_eligible = true/);
assert.match(migration, /Dynamic Prefix candidate requested an invalid route/);
assert.match(migration, /generic candidate requested an invalid route/);
assert.match(migration, /select \* into v_source[\s\S]*for update/);
assert.match(migration, /not found or v_source\.task_submission_id is null/);
assert.match(migration, /on conflict do nothing/);
assert.match(migration, /activated_at = coalesce\(/);
assert.match(migration, /update public\.adle_canonical_intake_candidate_demands[\s\S]*link_status = 'resolved'/);
assert.match(migration, /update public\.adle_canonical_intake_demands demand[\s\S]*lifecycle_status = 'activated'[\s\S]*notification_status = 'resolved'/);
assert.match(migration, /last_reconciliation_outcome = 'all_waiting_candidates_activated'/);
assert.match(migration, /update public\.adle_canonical_intake_reconciliation_queue[\s\S]*job_status = 'completed'/);
assert.match(migration, /'candidate_activated'/);
assert.match(migration, /'learningItemId', v_learning_item_id,[\s\S]*'inserted', v_inserted/);
assert.match(migration, /revoke all on function public\.adle_persist_canonical_intake\([\s\S]*from public, anon, authenticated/);
assert.match(migration, /grant execute on function public\.adle_persist_canonical_intake\([\s\S]*to service_role/);
assert.doesNotMatch(migration, /base_word|D4_MOR_BASE/i, "BW-0 must not introduce Base Word behaviour");

assert.match(rollbackProof, /^begin;/m);
assert.match(rollbackProof, /^rollback;/m);
assert.match(rollbackProof, /adle_persist_canonical_intake\([\s\S]*?'dynamic_prefix_word_lab', 'v2'/);
assert.match(rollbackProof, /adle_persist_canonical_intake\([\s\S]*?'dynamic_affix_word_lab', 'v3'/);
assert.match(rollbackProof, /adle_persist_canonical_intake\([\s\S]*?'adle_word_level', 'v1'/);
assert.match(rollbackProof, /Prefix replay was not idempotent/);
assert.match(rollbackProof, /Dynamic Affix replay was not idempotent/);
assert.match(rollbackProof, /Generic replay was not idempotent/);
assert.match(rollbackProof, /Candidate-demand link was not resolved/);
assert.match(rollbackProof, /Demand activation lifecycle was not completed/);
assert.match(rollbackProof, /Reconciliation queue was not completed/);
assert.match(rollbackProof, /candidate_activated event is missing/);
assert.match(rollbackProof, /temporaryProfileActivation/);
assert.doesNotMatch(rollbackProof, /insert\s+into\s+public\.adle_learning_items/i, "proof must persist learning items only through the RPC");
assert.doesNotMatch(rollbackProof, /base_word_lab|base_word_family/i, "BW-0 proof must not introduce Base Word route behaviour");

assert.match(guardedMigration, /supersede_spelling_canonical_mapping_admin/);
assert.match(guardedMigration, /mapping_status='superseded'/);
assert.match(guardedMigration, /replacement_mapping_id=v_new_id/);
assert.match(guardedMigration, /resolver_visibility_status='hidden'/);
console.log("adle-dynamic-affix-persistence-contract-regression: ok");
