import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname } from "node:path";

import { ADLE_ACTIVITY_REQUIREMENT_REGISTRY } from "../lib/adle/composable-lesson/activity-requirements";
import { COMPATIBILITY_BLOCKER_CODES } from "../lib/adle/composable-lesson/compatibility";
import {
  auditProductionReadiness,
  readinessAuditMarkdown,
} from "../lib/adle/composable-lesson/readiness-audit";
import { buildRepositoryReadinessInput } from "../lib/adle/composable-lesson/repository-readiness";
import { ADLE_CURRICULUM_ROUTE_REGISTRY } from "../lib/adle/curriculum-readiness/route-registry";

const GENERATED_NOTICE =
  "Generated by scripts/generate-adle-composable-architecture.ts. Do not edit by hand.";
const outputRoot = "docs/generated/adle-composable-lesson";

function stable(value: unknown): unknown {
  if (Array.isArray(value)) return value.map(stable);
  if (value && typeof value === "object") {
    return Object.fromEntries(
      Object.entries(value)
        .sort(([left], [right]) => left.localeCompare(right))
        .map(([key, entry]) => [key, stable(entry)]),
    );
  }
  return value;
}

function json(value: unknown): string {
  return `${JSON.stringify(stable(value), null, 2)}\n`;
}

const routes = [...ADLE_CURRICULUM_ROUTE_REGISTRY].sort((left, right) =>
  `${left.routeId}:${left.routeVersion}`.localeCompare(
    `${right.routeId}:${right.routeVersion}`,
  ),
);
const activities = [...ADLE_ACTIVITY_REQUIREMENT_REGISTRY].sort((left, right) =>
  left.kind.localeCompare(right.kind),
);
const readiness = auditProductionReadiness(
  buildRepositoryReadinessInput("repository/report"),
);
const blockers = [...COMPATIBILITY_BLOCKER_CODES]
  .sort()
  .map((code) => ({
    code,
    label: code.replaceAll("_", " "),
  }));

const routeActivityMarkdown = [
  "<!-- GENERATED FILE. DO NOT EDIT. -->",
  "",
  `> ${GENERATED_NOTICE}`,
  "",
  "# ADLE Route and Activity Reference",
  "",
  "## Routes",
  "",
  "| Route | Payload | State | Skills | Items | Activities |",
  "|---|---|---|---:|---|---|",
  ...routes.map(
    (route) =>
      `| ${route.routeId}:${route.routeVersion} | ${route.payloadKind} ${route.payloadVersions.join("/")} | ${route.implementationState} | ${route.supportedMicroSkillKeys.length || "fallback"} | ${route.intentionalItemCounts.join("/") || "variable"} | ${route.requiredActivities.join(", ")} |`,
  ),
  "",
  "## Activity requirements",
  "",
  "| Activity | Visibility | Evidence | Required facts |",
  "|---|---|---|---|",
  ...activities.map(
    (activity) =>
      `| ${activity.kind}:v${activity.requirementVersion} | ${activity.answerVisibility} | ${activity.evidenceMode} | ${activity.requiredFacts.map((fact) => `${fact.owner}.${fact.factKey}`).join(", ") || "none"} |`,
  ),
  "",
  "## Blockers",
  "",
  ...blockers.map((blocker) => `- \`${blocker.code}\`: ${blocker.label}.`),
  "",
].join("\n");

const readinessMarkdown = [
  "<!-- GENERATED FILE. DO NOT EDIT. -->",
  "",
  `> ${GENERATED_NOTICE}`,
  "",
  readinessAuditMarkdown(readiness),
].join("\n");

const outputs = new Map<string, string>([
  [
    `${outputRoot}/route-inventory.json`,
    json({ generatedNotice: GENERATED_NOTICE, routes }),
  ],
  [
    `${outputRoot}/activity-requirements.json`,
    json({
      generatedNotice: GENERATED_NOTICE,
      version: "adle_activity_requirements_v1",
      activities,
    }),
  ],
  [
    `${outputRoot}/blocker-reference.json`,
    json({ generatedNotice: GENERATED_NOTICE, blockers }),
  ],
  [
    `${outputRoot}/repository-readiness.json`,
    json({ generatedNotice: GENERATED_NOTICE, readiness }),
  ],
  [`${outputRoot}/route-and-activity-reference.md`, routeActivityMarkdown],
  [`${outputRoot}/repository-readiness.md`, readinessMarkdown],
]);

const check = process.argv.includes("--check");
const drift: string[] = [];
for (const [path, content] of outputs) {
  if (check) {
    if (!existsSync(path) || readFileSync(path, "utf8") !== content) {
      drift.push(path);
    }
    continue;
  }
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, content);
}

if (drift.length > 0) {
  console.error(`ADLE architecture inventory drift:\n${drift.join("\n")}`);
  process.exitCode = 1;
} else {
  console.log(
    check
      ? "ADLE architecture inventory drift check passed."
      : `Generated ${outputs.size} ADLE architecture inventory files.`,
  );
}
