import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname } from "node:path";

import { ADLE_ACTIVITY_REQUIREMENT_REGISTRY } from "../lib/adle/composable-lesson/activity-requirements";
import { COMPATIBILITY_BLOCKER_CODES } from "../lib/adle/composable-lesson/compatibility";
import { LESSON_ROUTE_RESOLUTION_BLOCKER_CODES } from "../lib/adle/composable-lesson/contracts";
import {
  GENERIC_LESSON_SNAPSHOT_COMPILER_VERSION,
  GENERIC_LESSON_SNAPSHOT_SCHEMA_VERSION,
  GENERIC_LESSON_SNAPSHOT_VALIDATOR_VERSION,
  GENERIC_SNAPSHOT_BLOCKER_CODES,
} from "../lib/adle/composable-lesson/generic-snapshot-contracts";
import {
  GENERIC_SNAPSHOT_TEMPLATE_REGISTRY,
  validateGenericSnapshotTemplateRegistry,
} from "../lib/adle/composable-lesson/generic-snapshot-registry";
import {
  GENERIC_SNAPSHOT_ACTIVITY_REQUIREMENTS,
  validateGenericSnapshotRequirementRegistry,
} from "../lib/adle/composable-lesson/generic-snapshot-requirements";
import {
  ADLE_NEW_ASSIGNMENT_ROUTE_IDS,
  ADLE_ROUTE_METADATA_SCHEMA_VERSION,
  ADLE_ROUTE_METADATA_SCHEMA_VERSION_V2,
  createPersistedRouteMetadata,
} from "../lib/adle/composable-lesson/persisted-route-metadata";
import {
  auditProductionReadiness,
  readinessAuditMarkdown,
} from "../lib/adle/composable-lesson/readiness-audit";
import { buildRepositoryReadinessInput } from "../lib/adle/composable-lesson/repository-readiness";
import { ADLE_CURRICULUM_ROUTE_REGISTRY } from "../lib/adle/curriculum-readiness/route-registry";
import {
  getActivityTemplateDefinition,
  listRegisteredActivityTemplateKeys,
} from "../lib/adle/activity-template-registry";
import {
  WORD_LAB_BLOCKER_CODES,
  WORD_LAB_COMPILER_VERSION,
  WORD_LAB_SNAPSHOT_SCHEMA_VERSION,
  WORD_LAB_VALIDATOR_VERSION,
} from "../lib/adle/word-lab/contracts";
import {
  WORD_LAB_RECIPE_REGISTRY,
  validateWordLabRecipeRegistry,
} from "../lib/adle/word-lab/recipe-registry";
import {
  SHARED_AFFIX_BLOCKER_CODES,
  SHARED_AFFIX_COMPILER_VERSION,
  SHARED_AFFIX_POLICY_VARIANTS,
  SHARED_AFFIX_PROFILE_VERSION,
  SHARED_AFFIX_SUPPORTED_TRANSFORMATION_TYPES,
} from "../lib/adle/morphology/shared-affix-contracts";
import {
  SHARED_AFFIX_PROFILE_REGISTRY,
  validateSharedAffixProfileRegistry,
} from "../lib/adle/morphology/shared-affix-profile-registry";
import {
  DYNAMIC_PREFIX_COMPILER_AUTHORITIES,
  DYNAMIC_PREFIX_COMPILER_BLOCKER_CODES,
  DYNAMIC_PREFIX_MIGRATED_PROFILE_KEYS,
} from "../lib/adle/morphology/dynamic-prefix-compiler-rollout";
import {
  DYNAMIC_AFFIX_COMPILER_AUTHORITIES,
  DYNAMIC_AFFIX_COMPILER_BLOCKER_CODES,
  DYNAMIC_AFFIX_MIGRATED_PROFILE_KEYS,
} from "../lib/adle/morphology/dynamic-affix-compiler-rollout";
import {
  DYNAMIC_AFFIX_TRANSFER_SELECTION_POLICY_VERSION,
} from "../lib/adle/morphology/dynamic-affix-transfer-selection";
import {
  DYNAMIC_AFFIX_ENVIRONMENT_INTEGRITY_FINGERPRINT_CONTRACT,
  DYNAMIC_AFFIX_SEMANTIC_FINGERPRINT_CONTRACT,
} from "../lib/adle/morphology/dynamic-affix-semantic-fingerprint";

const GENERATED_NOTICE =
  "Generated by scripts/generate-adle-composable-architecture.ts. Do not edit by hand.";
const outputRoot = "docs/generated/adle-composable-lesson";

function stable(value: unknown): unknown {
  if (Array.isArray(value)) return value.map(stable);
  if (value && typeof value === "object") {
    return Object.fromEntries(
      Object.entries(value)
        .sort(([left], [right]) => left.localeCompare(right))
        .map(([key, entry]) => [key, stable(entry)]),
    );
  }
  return value;
}

function json(value: unknown): string {
  return `${JSON.stringify(stable(value), null, 2)}\n`;
}

const routes = [...ADLE_CURRICULUM_ROUTE_REGISTRY].sort((left, right) =>
  `${left.routeId}:${left.routeVersion}`.localeCompare(
    `${right.routeId}:${right.routeVersion}`,
  ),
);
const activities = [...ADLE_ACTIVITY_REQUIREMENT_REGISTRY].sort((left, right) =>
  left.kind.localeCompare(right.kind),
);
const readiness = auditProductionReadiness(
  buildRepositoryReadinessInput("repository/report"),
);
const wordLabRecipes = [...WORD_LAB_RECIPE_REGISTRY].sort((left, right) =>
  `${left.identity.recipeKey}:v${left.identity.recipeVersion}`.localeCompare(
    `${right.identity.recipeKey}:v${right.identity.recipeVersion}`,
  ),
);
const blockers = [
  ...new Set([
    ...COMPATIBILITY_BLOCKER_CODES,
    ...LESSON_ROUTE_RESOLUTION_BLOCKER_CODES,
    ...GENERIC_SNAPSHOT_BLOCKER_CODES,
    ...WORD_LAB_BLOCKER_CODES,
    ...SHARED_AFFIX_BLOCKER_CODES,
    ...DYNAMIC_PREFIX_COMPILER_BLOCKER_CODES,
    ...DYNAMIC_AFFIX_COMPILER_BLOCKER_CODES,
  ]),
]
  .sort()
  .map((code) => ({
    code,
    label: code.replaceAll("_", " "),
  }));

const genericTemplateMappings = [...GENERIC_SNAPSHOT_TEMPLATE_REGISTRY]
  .sort((left, right) => left.templateKey.localeCompare(right.templateKey))
  .map((entry) => ({
    ...entry,
    requirements: GENERIC_SNAPSHOT_ACTIVITY_REQUIREMENTS.find(
      (candidate) => candidate.templateKey === entry.templateKey,
    )?.requirements ?? [],
  }));

const registryErrors = [
  ...validateGenericSnapshotTemplateRegistry(),
  ...validateGenericSnapshotRequirementRegistry(),
  ...validateWordLabRecipeRegistry(),
  ...validateSharedAffixProfileRegistry(),
];
for (const routeId of ["dynamic_prefix_word_lab", "dynamic_affix_word_lab"] as const) {
  const route = routes.find((entry) => entry.routeId === routeId);
  const declared = SHARED_AFFIX_PROFILE_REGISTRY.filter((entry) => entry.routeId === routeId)
    .map((entry) => entry.microSkillKey)
    .sort();
  if (!route || JSON.stringify(declared) !== JSON.stringify([...route.supportedMicroSkillKeys].sort())) {
    registryErrors.push(`shared_affix_route_profile_mismatch:${routeId}`);
  }
}
const prefixProfileKeys = SHARED_AFFIX_PROFILE_REGISTRY
  .filter((entry) => entry.routeId === "dynamic_prefix_word_lab")
  .map((entry) => entry.microSkillKey)
  .sort();
const prefixAuthorityKeys = DYNAMIC_PREFIX_COMPILER_AUTHORITIES
  .map((entry) => entry.microSkillKey)
  .sort();
if (JSON.stringify(prefixProfileKeys) !== JSON.stringify(prefixAuthorityKeys)) {
  registryErrors.push("dynamic_prefix_compiler_authority_profile_mismatch");
}
if (DYNAMIC_PREFIX_COMPILER_AUTHORITIES.some(
  (entry) => entry.authority !== "shared_migration",
)) {
  registryErrors.push("dynamic_prefix_shared_authority_drift");
}
const affixProfileKeys = SHARED_AFFIX_PROFILE_REGISTRY
  .filter((entry) => entry.routeId === "dynamic_affix_word_lab")
  .map((entry) => entry.microSkillKey)
  .sort();
const affixAuthorityKeys = DYNAMIC_AFFIX_COMPILER_AUTHORITIES
  .map((entry) => entry.microSkillKey)
  .sort();
if (JSON.stringify(affixProfileKeys) !== JSON.stringify(affixAuthorityKeys)) {
  registryErrors.push("dynamic_affix_compiler_authority_profile_mismatch");
}
if (DYNAMIC_AFFIX_COMPILER_AUTHORITIES.some((entry) => entry.authority !== "shared_migration")) {
  registryErrors.push("dynamic_affix_shared_authority_drift");
}
const usedPolicyVariants = {
  split: [...new Set(SHARED_AFFIX_PROFILE_REGISTRY.map((entry) => entry.policy.split.kind))].sort(),
  build: [...new Set(SHARED_AFFIX_PROFILE_REGISTRY.map((entry) => entry.policy.build.kind))].sort(),
  meaning: [...new Set(SHARED_AFFIX_PROFILE_REGISTRY.map((entry) => entry.policy.meaning.kind))].sort(),
  choiceOrder: [...new Set(SHARED_AFFIX_PROFILE_REGISTRY.map((entry) => entry.policy.choiceOrder.kind))].sort(),
};
for (const key of Object.keys(SHARED_AFFIX_POLICY_VARIANTS) as Array<keyof typeof SHARED_AFFIX_POLICY_VARIANTS>) {
  if (JSON.stringify(usedPolicyVariants[key]) !== JSON.stringify([...SHARED_AFFIX_POLICY_VARIANTS[key]].sort())) {
    registryErrors.push(`shared_affix_policy_variant_without_profile_coverage:${key}`);
  }
}
const runtimeKeys = listRegisteredActivityTemplateKeys();
const snapshotKeys = genericTemplateMappings.map((entry) => entry.templateKey);
if (JSON.stringify(runtimeKeys) !== JSON.stringify(snapshotKeys)) {
  registryErrors.push("runtime_and_snapshot_template_keys_disagree");
}
for (const mapping of genericTemplateMappings) {
  const runtime = getActivityTemplateDefinition(mapping.templateKey);
  if (!runtime) continue;
  if (runtime.rendererKind !== mapping.rendererKind) {
    registryErrors.push(`renderer_mismatch:${mapping.templateKey}`);
  }
  if (
    JSON.stringify([...runtime.supportedSectionKeys].sort()) !==
    JSON.stringify([...mapping.supportedSections].sort())
  ) {
    registryErrors.push(`section_mismatch:${mapping.templateKey}`);
  }
}
if (registryErrors.length > 0) {
  throw new Error(`ADLE generic snapshot registry invalid:\n${registryErrors.sort().join("\n")}`);
}

const snapshotVersions = [{
  snapshotSchemaVersion: GENERIC_LESSON_SNAPSHOT_SCHEMA_VERSION,
  route: "generic_composer:v1",
  recipe: "generic_first_exposure:v1",
  payload: "composed_daily_plan:1",
  compilerVersion: GENERIC_LESSON_SNAPSHOT_COMPILER_VERSION,
  validatorVersion: GENERIC_LESSON_SNAPSHOT_VALIDATOR_VERSION,
  writer: "persist_adle_generic_daily_plan_v2",
  reader: "resolveGenericLessonSnapshot",
  authoritativeStorage: "daily_assignments.compiled_lesson_snapshot",
  legacyFallback: "snapshot_absent_only",
}, {
  snapshotSchemaVersion: WORD_LAB_SNAPSHOT_SCHEMA_VERSION,
  route: "route-neutral; no production route activated",
  recipe: "fixture/candidate registry only",
  payload: "word_lab_snapshot_v1",
  compilerVersion: WORD_LAB_COMPILER_VERSION,
  validatorVersion: WORD_LAB_VALIDATOR_VERSION,
  writer: "not implemented in dark foundation",
  reader: "common Word Lab shell fixture only",
  authoritativeStorage: "not persisted; future route-neutral column",
  legacyFallback: "not applicable; live composer unchanged",
}];

const routeActivityMarkdown = [
  "<!-- GENERATED FILE. DO NOT EDIT. -->",
  "",
  `> ${GENERATED_NOTICE}`,
  "",
  "# ADLE Route and Activity Reference",
  "",
  "## Routes",
  "",
  "| Route | Recipe | Payload | Adapter | Renderer | State | Skills | Items | Activities |",
  "|---|---|---|---|---|---|---:|---|---|",
  ...routes.map(
    (route) =>
      `| ${route.routeId}:${route.routeVersion} | ${route.recipes.map((recipe) => `${recipe.recipeKey}:${recipe.recipeVersion}`).join(", ")} | ${route.payloadKind} ${route.payloadVersions.join("/")} | ${route.runtimeAdapterKey} | ${route.rendererKey} | ${route.implementationState} | ${route.supportedMicroSkillKeys.length || "fallback"} | ${route.intentionalItemCounts.join("/") || "variable"} | ${route.requiredActivities.join(", ")} |`,
  ),
  "",
  "## Dark common Word Lab recipes",
  "",
  "> This registry is not an activation switch. Only fixture and candidate recipes exist in the foundation stage.",
  "",
  "| Recipe | Status | Route | Family | Clusters | Microskills | Words | Activities |",
  "|---|---|---|---|---|---|---:|---|",
  ...wordLabRecipes.map((recipe) =>
    `| ${recipe.identity.recipeKey}:v${recipe.identity.recipeVersion} | ${recipe.identity.status} | ${recipe.compatibility.routeKey}:v${recipe.compatibility.routeVersion} | ${recipe.compatibility.familyKey} | ${recipe.compatibility.clusterKeys.join(", ") || "family default"} | ${recipe.compatibility.microSkillKeys?.join(", ") || "none"} | ${recipe.wordRequirements.lesson.min}-${recipe.wordRequirements.lesson.max} | ${recipe.activities.map((activity) => `${activity.kind}:v${activity.contractVersion}`).join(", ")} |`,
  ),
  "",
  "## Activity requirements",
  "",
  "| Activity | Visibility | Evidence | Required facts |",
  "|---|---|---|---|",
  ...activities.map(
    (activity) =>
      `| ${activity.kind}:v${activity.requirementVersion} | ${activity.answerVisibility} | ${activity.evidenceMode} | ${activity.requiredFacts.map((fact) => `${fact.owner}.${fact.factKey}`).join(", ") || "none"} |`,
  ),
  "",
  "## Shared affix compiler",
  "",
  "> Dynamic Prefix V2 has guarded shared-compiler authority for all five approved profiles. Dynamic Affix V3 has guarded authority for all ten approved profiles; its unset rollout mode remains legacy-authoritative.",
  "",
  "| Profile | Route | Position | Forms | Items | Split | Build | Meaning | Compiler authority |",
  "|---|---|---|---|---:|---|---|---|---|",
  ...SHARED_AFFIX_PROFILE_REGISTRY.map((profile) =>
      `| ${profile.microSkillKey} | ${profile.routeId}:${profile.routeVersion} | ${profile.position} | ${profile.forms.join(", ")} | ${(profile.prefixPedagogy?.policy ?? profile.policy).expectedAssignmentItemCount} | ${(profile.prefixPedagogy?.policy ?? profile.policy).split.kind} | ${(profile.prefixPedagogy?.policy ?? profile.policy).build.kind} | ${(profile.prefixPedagogy?.policy ?? profile.policy).meaning.kind} | ${DYNAMIC_PREFIX_COMPILER_AUTHORITIES.find((entry) => entry.microSkillKey === profile.microSkillKey)?.authority ?? DYNAMIC_AFFIX_COMPILER_AUTHORITIES.find((entry) => entry.microSkillKey === profile.microSkillKey)?.authority ?? "dark_no_writer"} |`,
  ),
  "",
  "## Blockers",
  "",
  ...blockers.map((blocker) => `- \`${blocker.code}\`: ${blocker.label}.`),
  "",
].join("\n");

const readinessMarkdown = [
  "<!-- GENERATED FILE. DO NOT EDIT. -->",
  "",
  `> ${GENERATED_NOTICE}`,
  "",
  readinessAuditMarkdown(readiness),
].join("\n");

const outputs = new Map<string, string>([
  [
    `${outputRoot}/route-inventory.json`,
    json({ generatedNotice: GENERATED_NOTICE, routes }),
  ],
  [
    `${outputRoot}/word-lab-foundation.json`,
    json({
      generatedNotice: GENERATED_NOTICE,
      activationAuthority: "none_dark_foundation",
      snapshotSchemaVersion: WORD_LAB_SNAPSHOT_SCHEMA_VERSION,
      compilerVersion: WORD_LAB_COMPILER_VERSION,
      validatorVersion: WORD_LAB_VALIDATOR_VERSION,
      recipes: wordLabRecipes,
      blockers: WORD_LAB_BLOCKER_CODES,
    }),
  ],
  [
    `${outputRoot}/shared-affix-profiles.json`,
    json({
      generatedNotice: GENERATED_NOTICE,
      activationAuthority: {
        dynamicPrefix: "all_five_shared_compiler_authority",
        dynamicAffix: "all_ten_guarded_shared_compiler_authority",
      },
      compilerVersion: SHARED_AFFIX_COMPILER_VERSION,
      profileVersion: SHARED_AFFIX_PROFILE_VERSION,
      profiles: SHARED_AFFIX_PROFILE_REGISTRY,
      dynamicPrefixCompilerRollout: {
        environmentVariable: "ADLE_DYNAMIC_PREFIX_COMPILER_MODE",
        defaultMode: "shadow",
        modes: ["shadow", "enforced_parity", "shared_authoritative"],
        owner: "ADLE composable lesson migration",
        migratedProfileKeys: DYNAMIC_PREFIX_MIGRATED_PROFILE_KEYS,
        authorities: DYNAMIC_PREFIX_COMPILER_AUTHORITIES,
        retirementGate: "seven production days; 50 successful migrated assignments; five per profile; zero blockers; green performance and rollback proof",
      },
      dynamicAffixCompilerRollout: {
        environmentVariable: "ADLE_DYNAMIC_AFFIX_COMPILER_MODE",
        defaultMode: "legacy_authoritative",
        modes: ["legacy_authoritative", "shadow", "enforced_parity", "shared_authoritative"],
        owner: "ADLE composable lesson migration",
        migratedProfileKeys: DYNAMIC_AFFIX_MIGRATED_PROFILE_KEYS,
        authorities: DYNAMIC_AFFIX_COMPILER_AUTHORITIES,
        retirementGate: "separate production observation; zero blockers or mismatch; green performance and rollback proof",
      },
      dynamicAffixTransferSelection: {
        policyVersion: DYNAMIC_AFFIX_TRANSFER_SELECTION_POLICY_VERSION,
        candidateAuthority: "all reviewed assignment-eligible Teaching Dictionary suffix-profile members",
        candidateOrderAuthority: "none; relation, insertion, UUID and timestamp order are ignored",
        coverageOrder: ["declared_suffix_forms", "meaning_sort_groups", "direct_changed_cleaver_contrast"],
        curriculumRank: ["declared_form_order", "declared_meaning_group_order", "direct_before_changed", "normalised_en_GB_word"],
        lessonOrder: ["authentic_oldest_first", "deterministically_selected_transfers"],
      },
      dynamicAffixFingerprintContracts: {
        environmentIntegrity: DYNAMIC_AFFIX_ENVIRONMENT_INTEGRITY_FINGERPRINT_CONTRACT,
        crossEnvironmentSemantic: DYNAMIC_AFFIX_SEMANTIC_FINGERPRINT_CONTRACT,
        selectedLessonOrderIsSemantic: true,
      },
      policyVariants: SHARED_AFFIX_POLICY_VARIANTS,
      supportedTransformations: SHARED_AFFIX_SUPPORTED_TRANSFORMATION_TYPES,
      parityRegression: "scripts/adle-dynamic-prefix-shared-authority-regression.ts",
      stagingProof: "scripts/adle-dynamic-prefix-shared-staging-proof.ts",
      dynamicAffixParityRegression: "scripts/adle-dynamic-affix-shared-authority-regression.ts",
      dynamicAffixTransferSelectionRegression: "scripts/adle-dynamic-affix-transfer-selection-regression.ts",
      dynamicAffixSemanticFingerprintRegression: "scripts/adle-dynamic-affix-semantic-fingerprint-regression.ts",
      dynamicAffixProfileFingerprintAudit: "scripts/adle-dynamic-affix-profile-fingerprint-audit.ts",
      dynamicAffixStagingProof: "scripts/adle-dynamic-affix-shared-staging-proof.ts",
    }),
  ],
  [
    `${outputRoot}/shared-affix-blockers.json`,
    json({
      generatedNotice: GENERATED_NOTICE,
      compilerVersion: SHARED_AFFIX_COMPILER_VERSION,
      sharedCompilerBlockers: SHARED_AFFIX_BLOCKER_CODES,
      dynamicPrefixRolloutBlockers: DYNAMIC_PREFIX_COMPILER_BLOCKER_CODES,
      dynamicAffixRolloutBlockers: DYNAMIC_AFFIX_COMPILER_BLOCKER_CODES,
    }),
  ],
  [
    `${outputRoot}/activity-requirements.json`,
    json({
      generatedNotice: GENERATED_NOTICE,
      version: "adle_activity_requirements_v1",
      activities,
    }),
  ],
  [
    `${outputRoot}/blocker-reference.json`,
    json({ generatedNotice: GENERATED_NOTICE, blockers }),
  ],
  [
    `${outputRoot}/route-metadata-contract.json`,
    json({
      generatedNotice: GENERATED_NOTICE,
      metadataSchemaVersion: ADLE_ROUTE_METADATA_SCHEMA_VERSION,
      acceptedMetadataSchemaVersions: [
        ADLE_ROUTE_METADATA_SCHEMA_VERSION,
        ADLE_ROUTE_METADATA_SCHEMA_VERSION_V2,
      ],
      activeWriterMetadataSchemaVersion: ADLE_ROUTE_METADATA_SCHEMA_VERSION,
      releaseAuthorityMetadataSchemaVersion: ADLE_ROUTE_METADATA_SCHEMA_VERSION_V2,
      authoritativeStorage: "daily_assignments.lesson_route_metadata",
      writers: ADLE_NEW_ASSIGNMENT_ROUTE_IDS.map((routeId) =>
        createPersistedRouteMetadata(routeId),
      ),
      blockerCodes: [...LESSON_ROUTE_RESOLUTION_BLOCKER_CODES],
      legacyFallback: "metadata_absent_only",
    }),
  ],
  [
    `${outputRoot}/repository-readiness.json`,
    json({ generatedNotice: GENERATED_NOTICE, readiness }),
  ],
  [
    `${outputRoot}/snapshot-version-inventory.json`,
    json({ generatedNotice: GENERATED_NOTICE, versions: snapshotVersions }),
  ],
  [
    `${outputRoot}/generic-template-snapshot-mapping.json`,
    json({
      generatedNotice: GENERATED_NOTICE,
      version: "adle_generic_snapshot_templates_v2",
      mappings: genericTemplateMappings,
    }),
  ],
  [`${outputRoot}/route-and-activity-reference.md`, routeActivityMarkdown],
  [`${outputRoot}/repository-readiness.md`, readinessMarkdown],
]);

const check = process.argv.includes("--check");
const drift: string[] = [];
for (const [path, content] of outputs) {
  if (check) {
    if (!existsSync(path) || readFileSync(path, "utf8") !== content) {
      drift.push(path);
    }
    continue;
  }
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, content);
}

if (drift.length > 0) {
  console.error(`ADLE architecture inventory drift:\n${drift.join("\n")}`);
  process.exitCode = 1;
} else {
  console.log(
    check
      ? "ADLE architecture inventory drift check passed."
      : `Generated ${outputs.size} ADLE architecture inventory files.`,
  );
}
