import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

import {
  ADLE_ACTIVITY_AUDIT_CONCLUSIONS,
  ADLE_ACTIVITY_CATALOGUE,
  ADLE_ACTIVITY_CATALOGUE_VERSION,
  ADLE_ACTIVITY_CONVERGENCE_BACKLOG,
  ADLE_ACTIVITY_IMPLEMENTATION_AUDIT,
  activityAuditCounts,
  type ActivityCatalogueEntry,
  type ActivityImplementationAuditRow,
} from "../lib/adle/activity-catalogue";

const GENERATED_NOTICE = "<!-- GENERATED FILE. DO NOT EDIT. -->\n\n> Generated by `scripts/generate-adle-activity-catalogue.ts` from `lib/adle/activity-catalogue.ts`.\n";

function escapeCell(value: string): string {
  return value.replaceAll("|", "\\|").replaceAll("\n", " ");
}

function list(values: readonly string[]): string {
  return values.length ? values.map((value) => `\`${value}\``).join(", ") : "None";
}

function yes(value: boolean): string {
  return value ? "Yes" : "No";
}

function activitySection(entry: ActivityCatalogueEntry): string {
  const modes = entry.supportedModes.map((mode) => `- \`${mode}\`: ${entry.modeDescriptions[mode]}`).join("\n");
  return `## ${entry.activityKey} — ${entry.displayName}

**Pedagogical purpose:** ${entry.pedagogicalPurpose}

**Interaction family:** \`${entry.interactionFamily}\`

**Best used for:** ${entry.whenToUse}

**Do not use when:** ${entry.whenNotToUse}

**Modes:**

${modes}

**Current users:** Routes ${list(entry.usedByRoutes)}. Micro-skills ${list(entry.usedByMicroSkills)}.

**Canonical implementation:** ${entry.canonicalComponent ? `\`${entry.canonicalComponent}\` in \`${entry.canonicalComponentPath}\`` : "No canonical implementation yet."}

**Architectural status:** \`${entry.status}\`

**Inputs:** Required: ${list(entry.requiredInputs)}. Optional: ${list(entry.optionalInputs)}.

**Capabilities:** Pointer ${yes(entry.supportsPointer)} · Keyboard ${yes(entry.supportsKeyboard)} · Reduced motion ${yes(entry.supportsReducedMotion)} · Audio ${yes(entry.supportsAudio)} · Captures attempt ${yes(entry.capturesAttempt)} · Evidence-bearing ${yes(entry.evidenceBearing)} · First Impression ${yes(entry.firstImpressionEligible)} · Review ${yes(entry.reviewEligible)}.

${entry.notes ? `**Notes:** ${entry.notes}\n` : ""}`;
}

export function renderActivityCatalogueMarkdown(): string {
  const counts = activityAuditCounts();
  return `${GENERATED_NOTICE}
# ADLE Activity Catalogue

Version: \`${ADLE_ACTIVITY_CATALOGUE_VERSION}\`
Authoritative base: \`${ADLE_ACTIVITY_AUDIT_CONCLUSIONS.authoritativeBaseSha}\`

This is the chooser for curriculum designers and future implementation tasks. It describes interaction capability, not route-specific teaching content.

## How to choose

1. Start with the learning action the child must perform.
2. Select an existing canonical activity below.
3. Select a supported mode rather than creating a new component.
4. If only a fallback or unresolved entry fits, follow the NEW_INTERACTION_REQUIRED rule in the convergence plan.

## At a glance

| Activity | Purpose | Best for | First Impression | Review | Status |
|---|---|---|---|---|---|
${ADLE_ACTIVITY_CATALOGUE.map((entry) => `| \`${entry.activityKey}\` | ${escapeCell(entry.pedagogicalPurpose)} | ${escapeCell(entry.whenToUse)} | ${yes(entry.firstImpressionEligible)} | ${yes(entry.reviewEligible)} | \`${entry.status}\` |`).join("\n")}

The catalogue currently has ${ADLE_ACTIVITY_CATALOGUE.length} governed concepts, ${counts.canonicalActivityConcepts} with canonical status, and ${counts.configuredModes} declared modes. Entries marked \`REQUIRES_ARCHITECTURE_DECISION\` are genuine platform gaps or extraction decisions, not permission for route-local UI.

${ADLE_ACTIVITY_CATALOGUE.map(activitySection).join("\n")}

## Authority relationship

${ADLE_ACTIVITY_AUDIT_CONCLUSIONS.authorityRelationship}

## Convergence programme status

- Group 4: \`${ADLE_ACTIVITY_AUDIT_CONCLUSIONS.group4Closeout.status}\` — ${ADLE_ACTIVITY_AUDIT_CONCLUSIONS.group4Closeout.summary}
- Group 5: \`${ADLE_ACTIVITY_AUDIT_CONCLUSIONS.group5Closeout.status}\` — ${ADLE_ACTIVITY_AUDIT_CONCLUSIONS.group5Closeout.summary}
- Former proposed Group 6: \`${ADLE_ACTIVITY_AUDIT_CONCLUSIONS.formerGroup6.status}\` — ${ADLE_ACTIVITY_AUDIT_CONCLUSIONS.formerGroup6.summary}
- Group 7: \`${ADLE_ACTIVITY_AUDIT_CONCLUSIONS.group7Closeout.status}\` — ${ADLE_ACTIVITY_AUDIT_CONCLUSIONS.group7Closeout.summary}
- Next workstream: \`${ADLE_ACTIVITY_AUDIT_CONCLUSIONS.nextConvergenceGroup.status}\` — ${ADLE_ACTIVITY_AUDIT_CONCLUSIONS.nextConvergenceGroup.summary}
`;
}

function auditDetails(row: ActivityImplementationAuditRow): string {
  return `### ${row.implementationName}

- File: \`${row.filePath}\`
- Concept / family: \`${row.activityConcept}\` / \`${row.interactionFamily}\`
- Routes: ${list(row.currentRouteUsages)}
- Micro-skills: ${list(row.currentMicroSkillUsages)}
- Registry/template keys: ${list(row.registryTemplateKeys)}
- Props/config differences: ${row.propsConfigDifferences}
- Visual differences: ${row.visualDifferences}
- Behavioural differences: ${row.behaviouralDifferences}
- Persistence/evidence differences: ${row.persistenceEvidenceDifferences}
- Canonical candidate: ${row.canonicalCandidate ? `\`${row.canonicalCandidate}\`` : "None"}
- Classification: \`${row.classification}\`
- Recommended action: ${row.recommendedAction}
- Migration risk: \`${row.migrationRisk}\`
- Historical replay dependency: ${yes(row.historicalReplayDependency)}
- Evidence: ${row.evidence}
- Notes: ${row.notes || "None."}
`;
}

export function renderImplementationAuditMarkdown(): string {
  const counts = activityAuditCounts();
  return `${GENERATED_NOTICE}
# ADLE Activity Implementation Audit Matrix

Authoritative base SHA: \`${ADLE_ACTIVITY_AUDIT_CONCLUSIONS.authoritativeBaseSha}\`

Scope: named child-facing activity components, shared learner-interaction primitives, embedded specialist activity functions, development components representing intended learner interactions, and the dispatch/shell components that own them. Pure data compilers, server actions, persistence helpers, sound/motion utilities, and non-ADLE course UI are excluded.

## Starting state

- Audit worktree: ${ADLE_ACTIVITY_AUDIT_CONCLUSIONS.startingState.auditWorktree}
- Protected occupied checkout: ${ADLE_ACTIVITY_AUDIT_CONCLUSIONS.startingState.protectedOccupiedCheckout}

Existing runtime/architecture registries:

${ADLE_ACTIVITY_AUDIT_CONCLUSIONS.startingState.runtimeRegistries.map((item) => `- ${item}`).join("\n")}

Architecture documents inspected:

${ADLE_ACTIVITY_AUDIT_CONCLUSIONS.startingState.architectureDocuments.map((item) => `- \`${item}\``).join("\n")}

## Quantified result

| Measure | Count |
|---|---:|
| Discovered implementations | ${counts.totalImplementations} |
| Canonical implementations | ${counts.CANONICAL} |
| Canonical mode/adapters | ${counts.CANONICAL_MODE} |
| Thin curriculum adapters | ${counts.THIN_ADAPTER} |
| Development references | ${counts.DEVELOPMENT_REFERENCE} |
| Compatibility only | ${counts.COMPATIBILITY_ONLY} |
| Duplicates to migrate | ${counts.DUPLICATE_TO_MIGRATE} |
| Dead or unreferenced | ${counts.DEAD_OR_UNREFERENCED} |
| Requires architecture decision | ${counts.REQUIRES_ARCHITECTURE_DECISION} |

## Matrix

| Implementation | File | Concept | Routes | Template keys | Candidate | Classification | Risk | Historical replay | Action |
|---|---|---|---|---|---|---|---|---|---|
${ADLE_ACTIVITY_IMPLEMENTATION_AUDIT.map((row) => `| ${escapeCell(row.implementationName)} | \`${row.filePath}\` | \`${escapeCell(row.activityConcept)}\` | ${escapeCell(row.currentRouteUsages.join(", ") || "none")} | ${escapeCell(row.registryTemplateKeys.join(", ") || "none")} | ${escapeCell(row.canonicalCandidate ?? "none")} | \`${row.classification}\` | ${row.migrationRisk} | ${yes(row.historicalReplayDependency)} | ${escapeCell(row.recommendedAction)} |`).join("\n")}

## Cleaver findings

${ADLE_ACTIVITY_AUDIT_CONCLUSIONS.cleaverBoundary}

## Reflection findings

${ADLE_ACTIVITY_AUDIT_CONCLUSIONS.reflectionBoundary}

## Spell / Recall findings

${ADLE_ACTIVITY_AUDIT_CONCLUSIONS.spellRecallBoundary}

## Convergence closeout status

- Group 3 status: \`${ADLE_ACTIVITY_AUDIT_CONCLUSIONS.group3Closeout.status}\`
- Group 4 status: \`${ADLE_ACTIVITY_AUDIT_CONCLUSIONS.group4Closeout.status}\` — ${ADLE_ACTIVITY_AUDIT_CONCLUSIONS.group4Closeout.summary}
- Group 5 status: \`${ADLE_ACTIVITY_AUDIT_CONCLUSIONS.group5Closeout.status}\` — ${ADLE_ACTIVITY_AUDIT_CONCLUSIONS.group5Closeout.summary}
- Former proposed Group 6: \`${ADLE_ACTIVITY_AUDIT_CONCLUSIONS.formerGroup6.status}\` — ${ADLE_ACTIVITY_AUDIT_CONCLUSIONS.formerGroup6.summary}
- Group 7 status: \`${ADLE_ACTIVITY_AUDIT_CONCLUSIONS.group7Closeout.status}\` — ${ADLE_ACTIVITY_AUDIT_CONCLUSIONS.group7Closeout.summary}
- Next workstream: \`${ADLE_ACTIVITY_AUDIT_CONCLUSIONS.nextConvergenceGroup.status}\` — ${ADLE_ACTIVITY_AUDIT_CONCLUSIONS.nextConvergenceGroup.summary}

### Group 3 closeout detail

- Status: \`${ADLE_ACTIVITY_AUDIT_CONCLUSIONS.group3Closeout.status}\`
- Owner manual acceptance: ${ADLE_ACTIVITY_AUDIT_CONCLUSIONS.group3Closeout.ownerAcceptedOn}
- Result: ${ADLE_ACTIVITY_AUDIT_CONCLUSIONS.group3Closeout.summary}
- Acceptance fixes: ${ADLE_ACTIVITY_AUDIT_CONCLUSIONS.group3Closeout.acceptanceFixes.join(" ")}
- Preserved invariants: ${ADLE_ACTIVITY_AUDIT_CONCLUSIONS.group3Closeout.invariants}
- Next step: ${ADLE_ACTIVITY_AUDIT_CONCLUSIONS.group3Closeout.nextStep}

### Group 7 closeout detail

- Status: \`${ADLE_ACTIVITY_AUDIT_CONCLUSIONS.group7Closeout.status}\`
- Owner manual acceptance: ${ADLE_ACTIVITY_AUDIT_CONCLUSIONS.group7Closeout.ownerAcceptedOn}
- Production deployment: ${ADLE_ACTIVITY_AUDIT_CONCLUSIONS.group7Closeout.deployedOn}
- Result: ${ADLE_ACTIVITY_AUDIT_CONCLUSIONS.group7Closeout.summary}
- Preserved invariants: ${ADLE_ACTIVITY_AUDIT_CONCLUSIONS.group7Closeout.invariants}
- Next step: ${ADLE_ACTIVITY_AUDIT_CONCLUSIONS.group7Closeout.nextStep}

## Genuine gaps

${ADLE_ACTIVITY_AUDIT_CONCLUSIONS.genuineGaps.map((gap) => `- ${gap}`).join("\n")}

## Full row evidence

${ADLE_ACTIVITY_IMPLEMENTATION_AUDIT.map(auditDetails).join("\n").trimEnd()}
`;
}

export function renderConvergenceBacklogMarkdown(): string {
  const first = ADLE_ACTIVITY_AUDIT_CONCLUSIONS.firstImpressionImplications;
  const review = ADLE_ACTIVITY_AUDIT_CONCLUSIONS.reviewImplications;
  return `${GENERATED_NOTICE}
# ADLE Activity Convergence and Governance Plan

This is a migration backlog, not authority to refactor, activate routes, change evidence, migrate assignments, or alter Model C releases.

## Ordered backlog

${ADLE_ACTIVITY_CONVERGENCE_BACKLOG.map((item) => `### ${item.priority} — ${item.title}

- Current implementations: ${list(item.currentImplementations)}
- Target: ${item.targetCanonicalImplementation}
- Intended modes: ${list(item.intendedModes)}
- Routes affected: ${list(item.routesAffected)}
- Regression requirements: ${item.regressionRequirements.join("; ")}
- Learner/runtime risk: \`${item.learnerRuntimeRisk}\`
- Model C release change required: ${yes(item.modelCReleaseChangeRequired)}
- Release boundary: ${item.releaseBoundary}
- Consolidation opportunity: ${item.consolidationOpportunity}
`).join("\n")}

## Exact canonical boundaries

### Cleaver family

${ADLE_ACTIVITY_AUDIT_CONCLUSIONS.cleaverBoundary}

### Reflection family

${ADLE_ACTIVITY_AUDIT_CONCLUSIONS.reflectionBoundary}

### Spell / Recall family

${ADLE_ACTIVITY_AUDIT_CONCLUSIONS.spellRecallBoundary}

### Convergence closeout status

- Group 3 status: \`${ADLE_ACTIVITY_AUDIT_CONCLUSIONS.group3Closeout.status}\`
- Group 4 status: \`${ADLE_ACTIVITY_AUDIT_CONCLUSIONS.group4Closeout.status}\` — ${ADLE_ACTIVITY_AUDIT_CONCLUSIONS.group4Closeout.summary}
- Group 5 status: \`${ADLE_ACTIVITY_AUDIT_CONCLUSIONS.group5Closeout.status}\` — ${ADLE_ACTIVITY_AUDIT_CONCLUSIONS.group5Closeout.summary}
- Former proposed Group 6: \`${ADLE_ACTIVITY_AUDIT_CONCLUSIONS.formerGroup6.status}\` — ${ADLE_ACTIVITY_AUDIT_CONCLUSIONS.formerGroup6.summary}
- Group 7 status: \`${ADLE_ACTIVITY_AUDIT_CONCLUSIONS.group7Closeout.status}\` — ${ADLE_ACTIVITY_AUDIT_CONCLUSIONS.group7Closeout.summary}
- Next workstream: \`${ADLE_ACTIVITY_AUDIT_CONCLUSIONS.nextConvergenceGroup.status}\` — ${ADLE_ACTIVITY_AUDIT_CONCLUSIONS.nextConvergenceGroup.summary}

#### Group 3 closeout detail

- Status: \`${ADLE_ACTIVITY_AUDIT_CONCLUSIONS.group3Closeout.status}\`
- Owner manual acceptance: ${ADLE_ACTIVITY_AUDIT_CONCLUSIONS.group3Closeout.ownerAcceptedOn}
- Result: ${ADLE_ACTIVITY_AUDIT_CONCLUSIONS.group3Closeout.summary}
- Acceptance fixes: ${ADLE_ACTIVITY_AUDIT_CONCLUSIONS.group3Closeout.acceptanceFixes.join(" ")}
- Preserved invariants: ${ADLE_ACTIVITY_AUDIT_CONCLUSIONS.group3Closeout.invariants}
- Next step: ${ADLE_ACTIVITY_AUDIT_CONCLUSIONS.group3Closeout.nextStep}

#### Group 7 closeout detail

- Status: \`${ADLE_ACTIVITY_AUDIT_CONCLUSIONS.group7Closeout.status}\`
- Owner manual acceptance: ${ADLE_ACTIVITY_AUDIT_CONCLUSIONS.group7Closeout.ownerAcceptedOn}
- Production deployment: ${ADLE_ACTIVITY_AUDIT_CONCLUSIONS.group7Closeout.deployedOn}
- Result: ${ADLE_ACTIVITY_AUDIT_CONCLUSIONS.group7Closeout.summary}
- Preserved invariants: ${ADLE_ACTIVITY_AUDIT_CONCLUSIONS.group7Closeout.invariants}
- Next step: ${ADLE_ACTIVITY_AUDIT_CONCLUSIONS.group7Closeout.nextStep}

## Genuine platform gaps

${ADLE_ACTIVITY_AUDIT_CONCLUSIONS.genuineGaps.map((gap) => `- ${gap}`).join("\n")}

## Future new-activity rule

${ADLE_ACTIVITY_AUDIT_CONCLUSIONS.newActivityRule.map((rule, index) => `${index + 1}. ${rule}`).join("\n")}

A genuinely new interaction must declare \`NEW_INTERACTION_REQUIRED\` and record the pedagogical requirement, why no catalogue activity works, why configuration is insufficient, and why extending an existing abstraction is inappropriate.

## First Impression shell implications

Target sequence:

${first.targetSequence.map((step, index) => `${index + 1}. ${step}`).join("\n")}

Canonical route adoption:

${first.canonicalRoutes.map((route) => `- ${route}`).join("\n")}

Still bespoke:

${first.bespokePieces.map((piece) => `- ${piece}`).join("\n")}

## Review-template implications

Review-eligible: ${list(review.eligible)}

Not review-eligible: ${list(review.notEligible)}

${review.distinctions.map((item) => `- ${item}`).join("\n")}
`;
}

const outputs = new Map<string, string>([
  ["docs/adle/ACTIVITY_CATALOGUE.md", renderActivityCatalogueMarkdown()],
  ["docs/adle/ACTIVITY_IMPLEMENTATION_AUDIT.md", renderImplementationAuditMarkdown()],
  ["docs/adle/ACTIVITY_CONVERGENCE_BACKLOG.md", renderConvergenceBacklogMarkdown()],
]);

export function checkOrWriteGeneratedActivityCatalogue(check: boolean): string[] {
  const mismatches: string[] = [];
  for (const [relativePath, content] of outputs) {
    const path = join(process.cwd(), relativePath);
    if (check) {
      let current = "";
      try { current = readFileSync(path, "utf8"); } catch { /* Missing is a drift mismatch. */ }
      if (current !== content) mismatches.push(relativePath);
    } else {
      mkdirSync(join(process.cwd(), "docs/adle"), { recursive: true });
      writeFileSync(path, content, "utf8");
    }
  }
  return mismatches;
}

if (process.argv[1]?.endsWith("generate-adle-activity-catalogue.ts")) {
  const check = process.argv.includes("--check");
  const mismatches = checkOrWriteGeneratedActivityCatalogue(check);
  if (mismatches.length) {
    console.error(`ADLE Activity Catalogue drift: ${mismatches.join(", ")}`);
    process.exitCode = 1;
  } else {
    console.log(check ? "PASS: ADLE Activity Catalogue generated artifacts are current" : "WROTE: ADLE Activity Catalogue generated artifacts");
  }
}
