import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname } from "node:path";

import { ADLE_ACTIVITY_REQUIREMENT_REGISTRY } from "../lib/adle/composable-lesson/activity-requirements";
import { COMPATIBILITY_BLOCKER_CODES } from "../lib/adle/composable-lesson/compatibility";
import { LESSON_ROUTE_RESOLUTION_BLOCKER_CODES } from "../lib/adle/composable-lesson/contracts";
import {
  GENERIC_LESSON_SNAPSHOT_COMPILER_VERSION,
  GENERIC_LESSON_SNAPSHOT_SCHEMA_VERSION,
  GENERIC_LESSON_SNAPSHOT_VALIDATOR_VERSION,
  GENERIC_SNAPSHOT_BLOCKER_CODES,
} from "../lib/adle/composable-lesson/generic-snapshot-contracts";
import {
  GENERIC_SNAPSHOT_TEMPLATE_REGISTRY,
  validateGenericSnapshotTemplateRegistry,
} from "../lib/adle/composable-lesson/generic-snapshot-registry";
import {
  GENERIC_SNAPSHOT_ACTIVITY_REQUIREMENTS,
  validateGenericSnapshotRequirementRegistry,
} from "../lib/adle/composable-lesson/generic-snapshot-requirements";
import {
  ADLE_NEW_ASSIGNMENT_ROUTE_IDS,
  ADLE_ROUTE_METADATA_SCHEMA_VERSION,
  createPersistedRouteMetadata,
} from "../lib/adle/composable-lesson/persisted-route-metadata";
import {
  auditProductionReadiness,
  readinessAuditMarkdown,
} from "../lib/adle/composable-lesson/readiness-audit";
import { buildRepositoryReadinessInput } from "../lib/adle/composable-lesson/repository-readiness";
import { ADLE_CURRICULUM_ROUTE_REGISTRY } from "../lib/adle/curriculum-readiness/route-registry";
import {
  getActivityTemplateDefinition,
  listRegisteredActivityTemplateKeys,
} from "../lib/adle/activity-template-registry";

const GENERATED_NOTICE =
  "Generated by scripts/generate-adle-composable-architecture.ts. Do not edit by hand.";
const outputRoot = "docs/generated/adle-composable-lesson";

function stable(value: unknown): unknown {
  if (Array.isArray(value)) return value.map(stable);
  if (value && typeof value === "object") {
    return Object.fromEntries(
      Object.entries(value)
        .sort(([left], [right]) => left.localeCompare(right))
        .map(([key, entry]) => [key, stable(entry)]),
    );
  }
  return value;
}

function json(value: unknown): string {
  return `${JSON.stringify(stable(value), null, 2)}\n`;
}

const routes = [...ADLE_CURRICULUM_ROUTE_REGISTRY].sort((left, right) =>
  `${left.routeId}:${left.routeVersion}`.localeCompare(
    `${right.routeId}:${right.routeVersion}`,
  ),
);
const activities = [...ADLE_ACTIVITY_REQUIREMENT_REGISTRY].sort((left, right) =>
  left.kind.localeCompare(right.kind),
);
const readiness = auditProductionReadiness(
  buildRepositoryReadinessInput("repository/report"),
);
const blockers = [
  ...new Set([
    ...COMPATIBILITY_BLOCKER_CODES,
    ...LESSON_ROUTE_RESOLUTION_BLOCKER_CODES,
    ...GENERIC_SNAPSHOT_BLOCKER_CODES,
  ]),
]
  .sort()
  .map((code) => ({
    code,
    label: code.replaceAll("_", " "),
  }));

const genericTemplateMappings = [...GENERIC_SNAPSHOT_TEMPLATE_REGISTRY]
  .sort((left, right) => left.templateKey.localeCompare(right.templateKey))
  .map((entry) => ({
    ...entry,
    requirements: GENERIC_SNAPSHOT_ACTIVITY_REQUIREMENTS.find(
      (candidate) => candidate.templateKey === entry.templateKey,
    )?.requirements ?? [],
  }));

const registryErrors = [
  ...validateGenericSnapshotTemplateRegistry(),
  ...validateGenericSnapshotRequirementRegistry(),
];
const runtimeKeys = listRegisteredActivityTemplateKeys();
const snapshotKeys = genericTemplateMappings.map((entry) => entry.templateKey);
if (JSON.stringify(runtimeKeys) !== JSON.stringify(snapshotKeys)) {
  registryErrors.push("runtime_and_snapshot_template_keys_disagree");
}
for (const mapping of genericTemplateMappings) {
  const runtime = getActivityTemplateDefinition(mapping.templateKey);
  if (!runtime) continue;
  if (runtime.rendererKind !== mapping.rendererKind) {
    registryErrors.push(`renderer_mismatch:${mapping.templateKey}`);
  }
  if (
    JSON.stringify([...runtime.supportedSectionKeys].sort()) !==
    JSON.stringify([...mapping.supportedSections].sort())
  ) {
    registryErrors.push(`section_mismatch:${mapping.templateKey}`);
  }
}
if (registryErrors.length > 0) {
  throw new Error(`ADLE generic snapshot registry invalid:\n${registryErrors.sort().join("\n")}`);
}

const snapshotVersions = [{
  snapshotSchemaVersion: GENERIC_LESSON_SNAPSHOT_SCHEMA_VERSION,
  route: "generic_composer:v1",
  recipe: "generic_first_exposure:v1",
  payload: "composed_daily_plan:1",
  compilerVersion: GENERIC_LESSON_SNAPSHOT_COMPILER_VERSION,
  validatorVersion: GENERIC_LESSON_SNAPSHOT_VALIDATOR_VERSION,
  writer: "persist_adle_generic_daily_plan_v2",
  reader: "resolveGenericLessonSnapshot",
  authoritativeStorage: "daily_assignments.compiled_lesson_snapshot",
  legacyFallback: "snapshot_absent_only",
}];

const routeActivityMarkdown = [
  "<!-- GENERATED FILE. DO NOT EDIT. -->",
  "",
  `> ${GENERATED_NOTICE}`,
  "",
  "# ADLE Route and Activity Reference",
  "",
  "## Routes",
  "",
  "| Route | Recipe | Payload | Adapter | Renderer | State | Skills | Items | Activities |",
  "|---|---|---|---|---|---|---:|---|---|",
  ...routes.map(
    (route) =>
      `| ${route.routeId}:${route.routeVersion} | ${route.recipes.map((recipe) => `${recipe.recipeKey}:${recipe.recipeVersion}`).join(", ")} | ${route.payloadKind} ${route.payloadVersions.join("/")} | ${route.runtimeAdapterKey} | ${route.rendererKey} | ${route.implementationState} | ${route.supportedMicroSkillKeys.length || "fallback"} | ${route.intentionalItemCounts.join("/") || "variable"} | ${route.requiredActivities.join(", ")} |`,
  ),
  "",
  "## Activity requirements",
  "",
  "| Activity | Visibility | Evidence | Required facts |",
  "|---|---|---|---|",
  ...activities.map(
    (activity) =>
      `| ${activity.kind}:v${activity.requirementVersion} | ${activity.answerVisibility} | ${activity.evidenceMode} | ${activity.requiredFacts.map((fact) => `${fact.owner}.${fact.factKey}`).join(", ") || "none"} |`,
  ),
  "",
  "## Blockers",
  "",
  ...blockers.map((blocker) => `- \`${blocker.code}\`: ${blocker.label}.`),
  "",
].join("\n");

const readinessMarkdown = [
  "<!-- GENERATED FILE. DO NOT EDIT. -->",
  "",
  `> ${GENERATED_NOTICE}`,
  "",
  readinessAuditMarkdown(readiness),
].join("\n");

const outputs = new Map<string, string>([
  [
    `${outputRoot}/route-inventory.json`,
    json({ generatedNotice: GENERATED_NOTICE, routes }),
  ],
  [
    `${outputRoot}/activity-requirements.json`,
    json({
      generatedNotice: GENERATED_NOTICE,
      version: "adle_activity_requirements_v1",
      activities,
    }),
  ],
  [
    `${outputRoot}/blocker-reference.json`,
    json({ generatedNotice: GENERATED_NOTICE, blockers }),
  ],
  [
    `${outputRoot}/route-metadata-contract.json`,
    json({
      generatedNotice: GENERATED_NOTICE,
      metadataSchemaVersion: ADLE_ROUTE_METADATA_SCHEMA_VERSION,
      authoritativeStorage: "daily_assignments.lesson_route_metadata",
      writers: ADLE_NEW_ASSIGNMENT_ROUTE_IDS.map((routeId) =>
        createPersistedRouteMetadata(routeId),
      ),
      blockerCodes: [...LESSON_ROUTE_RESOLUTION_BLOCKER_CODES],
      legacyFallback: "metadata_absent_only",
    }),
  ],
  [
    `${outputRoot}/repository-readiness.json`,
    json({ generatedNotice: GENERATED_NOTICE, readiness }),
  ],
  [
    `${outputRoot}/snapshot-version-inventory.json`,
    json({ generatedNotice: GENERATED_NOTICE, versions: snapshotVersions }),
  ],
  [
    `${outputRoot}/generic-template-snapshot-mapping.json`,
    json({
      generatedNotice: GENERATED_NOTICE,
      version: "adle_generic_snapshot_templates_v2",
      mappings: genericTemplateMappings,
    }),
  ],
  [`${outputRoot}/route-and-activity-reference.md`, routeActivityMarkdown],
  [`${outputRoot}/repository-readiness.md`, readinessMarkdown],
]);

const check = process.argv.includes("--check");
const drift: string[] = [];
for (const [path, content] of outputs) {
  if (check) {
    if (!existsSync(path) || readFileSync(path, "utf8") !== content) {
      drift.push(path);
    }
    continue;
  }
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, content);
}

if (drift.length > 0) {
  console.error(`ADLE architecture inventory drift:\n${drift.join("\n")}`);
  process.exitCode = 1;
} else {
  console.log(
    check
      ? "ADLE architecture inventory drift check passed."
      : `Generated ${outputs.size} ADLE architecture inventory files.`,
  );
}
