/* Reviewed package JSON is validated before any guarded staging write. */
/* eslint-disable @typescript-eslint/no-explicit-any */
import { createHash, randomUUID } from "node:crypto";
import { readFileSync } from "node:fs";
import { createClient } from "@supabase/supabase-js";

const PROFILE = "D4_MOR_COMPOUND_WORDS_CLOSED_COMPOUNDS";
const PACKAGE = "data/adle/candidates/d4-mor-remaining-profiles/v1/closed-compounds-dictionary-pool-review.json";
const CONTENT = "data/adle/candidates/d4-mor-remaining-profiles/v1/closed-compounds.json";
const required = (name: string) => { const value = process.env[name]; if (!value) throw new Error(`Missing ${name}`); return value; };
const hash = (value: string) => createHash("sha256").update(value).digest("hex");

async function main() {
  if (!process.argv.includes("--apply") || process.env.ADLE_CLOSED_COMPOUND_ACCEPT_STAGING !== "approved-seven-word-pool") throw new Error("Use --apply with ADLE_CLOSED_COMPOUND_ACCEPT_STAGING=approved-seven-word-pool.");
  const db = createClient(required("NEXT_PUBLIC_SUPABASE_URL"), process.env.SUPABASE_SERVICE_ROLE_KEY || required("SB_SERVICE_ROLE_KEY"), { auth: { autoRefreshToken: false, persistSession: false } });
  if (!new URL(required("NEXT_PUBLIC_SUPABASE_URL")).hostname.includes("jlhotktspjvffslvuyfz")) throw new Error("Refusing non-staging host.");
  const raw = readFileSync(PACKAGE, "utf8"); const content = JSON.parse(readFileSync(CONTENT, "utf8")); const pkg = JSON.parse(raw); const words = pkg.approvedPoolProposal as Array<any>;
  if (pkg.status !== "human_approved_pending_guarded_staging_dictionary_release" || words.length !== 7 || !["bedroom", "breakthrough", "football", "playground", "rainbow", "sunshine", "weekend"].every((word) => words.some((entry) => entry.word === word))) throw new Error("Approved seven-word package is invalid.");
  const prohibited = ["adle_learning_items", "daily_assignments", "assignment_items", "adle_assignment_attempt_events", "adle_child_learning_reflections", "adle_review_bundles"] as const;
  const before = Object.fromEntries(await Promise.all(prohibited.map(async (table) => { const result = await db.from(table).select("id", { count: "exact", head: true }); if (result.error) throw result.error; return [table, result.count ?? 0]; })));
  const existing = await db.from("canonical_teaching_dictionary_words").select("id,normalised_word,display_word,frequency_band,age_band,complexity_band,row_status,review_status").in("normalised_word", words.map((word) => word.word)); if (existing.error || existing.data?.length !== 7) throw new Error(`Missing canonical words: ${existing.error?.message ?? "expected seven"}`);
  const ids = new Map(existing.data.map((word) => [word.normalised_word, word.id])); const allIds = [...ids.values()];
  const [metadata, dictation] = await Promise.all([db.from("canonical_teaching_dictionary_word_metadata").select("canonical_word_id,syllables,phoneme_hint,stress_pattern,has_schwa,row_status,review_status").in("canonical_word_id", allIds).eq("row_status", "active").eq("review_status", "approved_for_first_exposure"), db.from("canonical_teaching_dictionary_dictation_sentences").select("canonical_word_id,dictation_sentence,dictation_target_token_index,audio_text,row_status,review_status").in("canonical_word_id", allIds).eq("row_status", "active").eq("review_status", "approved_for_first_exposure")]);
  if (metadata.error || dictation.error) throw new Error(metadata.error?.message ?? dictation.error?.message);
  const meta = new Map((metadata.data ?? []).map((row) => [row.canonical_word_id, row])); const sentences = new Map((dictation.data ?? []).map((row) => [row.canonical_word_id, row]));
  for (const entry of words) { const canonical = existing.data.find((word) => word.normalised_word === entry.word)!; const m = meta.get(canonical.id); const d = sentences.get(canonical.id); if (canonical.row_status !== "active" || canonical.review_status !== "approved_for_first_exposure" || !canonical.frequency_band || !canonical.age_band || !canonical.complexity_band || !m?.syllables || !m.phoneme_hint || !m.stress_pattern || typeof m.has_schwa !== "boolean" || d?.row_status !== "active" || d.review_status !== "approved_for_first_exposure" || d.audio_text !== d.dictation_sentence || d.dictation_sentence !== entry.dictation || d.dictation_target_token_index !== entry.targetTokenIndex || `${entry.firstWord}${entry.secondWord}` !== canonical.display_word) throw new Error(`Dictionary facts do not validate for ${entry.word}`); }
  const existingProfile = await db.from("canonical_teaching_dictionary_compound_profiles").select("id").eq("micro_skill_key", PROFILE).eq("row_status", "active"); if (existingProfile.error) throw existingProfile.error; if ((existingProfile.data ?? []).length) throw new Error("An active closed-compound profile already exists.");
  const packageSha = hash(raw); const batchId = randomUUID(); const source = { package_sha256: packageSha, profile: PROFILE, production_enabled: false, learner_writes: 0 };
  const batch = await db.from("canonical_teaching_dictionary_import_batches").insert({ id: batchId, source_folder_path: PACKAGE, source_folder_sha256: packageSha, validator_version: "adle_closed_compound_staging_import_v1", validation_summary: { errors: 0 }, row_counts: { profiles: 1, compound_facts: 7 }, readiness_summary: source, import_mode: "admin_import", batch_status: "validated", source_metadata: source, imported_by: "ADLE guarded closed-compound staging importer", imported_at: new Date().toISOString() }).select("id").single(); if (batch.error) throw batch.error;
  const profile = await db.from("canonical_teaching_dictionary_compound_profiles").insert({ import_batch_id: batchId, micro_skill_key: PROFILE, compound_type: "closed", intro_content: { ...content.reviewedIntroduction, summary: "Two words join together. The space closes up. They make one new word.", examples: [{ firstWord: "sun", secondWord: "flower", word: "sunflower" }] }, reflection_prompt_key: content.reflection.promptKey, reflection_prompt_text: content.reflection.promptText, production_enabled: false, row_status: "active", review_status: "approved_for_first_exposure", source_sheet: "closed-compounds-dictionary-pool-review.json", source_row_number: 1, source_row_hash: packageSha, source_metadata: source, source_category: "internal_reviewed_seed", source_name: "Closed compound approved staging pool", source_licence: "internal", source_use_note: "Staging-only profile; production disabled.", confidence: "high", reviewed_by: "Katie Sanderson", reviewed_at: new Date().toISOString() }).select("id").single(); if (profile.error) throw profile.error;
  const factRows = words.map((entry, index) => { const p1 = { id: "part_1", kind: "base", sourceText: entry.firstWord, surfaceText: entry.firstWord, gloss: entry.firstWordMeaning, displayRange: { start: 0, end: entry.firstWord.length } }; const p2 = { id: "part_2", kind: "base", sourceText: entry.secondWord, surfaceText: entry.secondWord, gloss: entry.secondWordMeaning, displayRange: { start: entry.firstWord.length, end: entry.word.length } }; const join = { afterPartId: "part_1", beforePartId: "part_2", joinType: "none", surfaceText: "", displayRange: { start: entry.firstWord.length, end: entry.firstWord.length } }; return { import_batch_id: batchId, canonical_word_id: ids.get(entry.word), micro_skill_key: PROFILE, compound_type: "closed", first_word: entry.firstWord, second_word: entry.secondWord, first_word_meaning: entry.firstWordMeaning, second_word_meaning: entry.secondWordMeaning, child_friendly_definition: entry.definition, teaching_split_parts: [p1, p2], teaching_split_joins: [join], true_morphology_parts: [p1, p2], true_morphology_joins: [join], true_morphology_transformations: [], transformation_notes: "Closed compound: retain both complete base words with no written space.", true_morphology_provenance: { package_sha256: packageSha, approved_review_artifact: PACKAGE }, assignment_eligible: true, transfer_eligible: true, row_status: "active", review_status: "approved_for_first_exposure", source_sheet: "closed-compounds-dictionary-pool-review.json", source_row_number: index + 2, source_row_hash: hash(JSON.stringify(entry)), source_metadata: source, source_category: "internal_reviewed_seed", source_name: "Closed compound approved staging pool", source_licence: "internal", source_use_note: "Explicit compound fact; never inferred at runtime.", confidence: "high", reviewed_by: "Katie Sanderson", reviewed_at: new Date().toISOString() }; });
  const inserted = await db.from("canonical_teaching_dictionary_compound_facts").insert(factRows); if (inserted.error) throw inserted.error;
  const after = Object.fromEntries(await Promise.all(prohibited.map(async (table) => { const result = await db.from(table).select("id", { count: "exact", head: true }); if (result.error) throw result.error; return [table, result.count ?? 0]; })));
  if (JSON.stringify(before) !== JSON.stringify(after)) throw new Error("Prohibited learner/runtime writes detected.");
  console.log(JSON.stringify({ status: "imported", batchId, profileId: profile.data.id, compoundFacts: 7, productionEnabled: false, learnerWrites: 0 }));
}
main().catch((error) => { console.error(error instanceof Error ? error.message : String(error)); process.exitCode = 1; });
