#!/usr/bin/env node
import { createHash } from "node:crypto";
import { execFileSync } from "node:child_process";
import { readFileSync } from "node:fs";
import { basename, resolve } from "node:path";

import { fingerprintSnapshotValue } from "../lib/adle/composable-lesson/canonical-fingerprint";
import { canonicalUtcTimestampMilliseconds } from "../lib/adle/review-policy/canonical-timestamp";

const CONFIRMATION = "PROVE_ADLE_C2B2_SCHEDULER_PERSISTENCE_LOCALLY";
const C2B6_CONFIRMATION = "PROVE_ADLE_C2B6_CONTROLLED_OPT_IN_LOCALLY";
const C2B7_CONFIRMATION = "PROVE_ADLE_C2B7_CANARY_HOTFIX_LOCALLY";
const FR2_CONFIRMATION = "PROVE_ADLE_FR2_RETIREMENT_PERSISTENCE_LOCALLY";
const FR3_CONFIRMATION = "PROVE_ADLE_FR3_FINAL_RUNG_RUNTIME_LOCALLY";
if (!process.argv.slice(2).includes(CONFIRMATION)) {
  throw new Error(`Refusing disposable C2B.2 proof without: -- ${CONFIRMATION}`);
}

const root = process.cwd();
const container = process.env.ADLE_PRODUCTION_SHAPED_DB_CONTAINER?.trim()
  || "supabase_db_scarletts-spells-adle-prodshape-20260827";
const sourceDatabase = process.env.ADLE_PRODUCTION_SHAPED_DB_NAME?.trim() || "postgres";
const proofDatabase = `adle_c2b2_${process.pid}`;
const migrationName = "20260831120000_add_adle_c2b2_scheduler_persistence.sql";
const migrationPath = resolve(root, "supabase/migrations", migrationName);
const c2b6MigrationName = "20260901120000_add_adle_c2b6_controlled_opt_in.sql";
const c2b7MigrationName = "20260901130000_normalize_adle_c2b6_review_completion_milliseconds.sql";
const fr2MigrationName = "20260901140000_add_adle_fr2_retirement_persistence.sql";
const fr3MigrationName = "20260902120000_integrate_adle_fr3_final_rung_runtime.sql";
const proveFR3 = process.argv.slice(2).includes(FR3_CONFIRMATION);
const proveFR2 = proveFR3 || process.argv.slice(2).includes(FR2_CONFIRMATION);
const proveC2B7 = proveFR2 || process.argv.slice(2).includes(C2B7_CONFIRMATION);
const proveC2B6 = proveC2B7 || process.argv.slice(2).includes(C2B6_CONFIRMATION);
const maxBuffer = 192 * 1024 * 1024;

function docker(args: string[], input?: string | Buffer): string {
  return execFileSync("docker", args, {
    ...(input === undefined ? {} : { input }),
    encoding: "utf8",
    maxBuffer,
  });
}

function psql(database: string, sql: string): string {
  return docker([
    "exec", "-i", container, "psql", "-U", "postgres", "-d", database,
    "-v", "ON_ERROR_STOP=1", "-At",
  ], sql);
}

function recordMigration(database: string, file: string) {
  const version = file.split("_")[0]!;
  const name = basename(file, ".sql").slice(version.length + 1);
  psql(database, `
    insert into supabase_migrations.schema_migrations(version,name)
    values ('${version}','${name}') on conflict(version) do nothing;
  `);
}

const sourceVersion = psql(
  sourceDatabase,
  "select coalesce(max(version),'') from supabase_migrations.schema_migrations;",
).trim();
if (sourceVersion !== "20260827120000") {
  throw new Error(`Expected production-shaped local source through 20260827120000, got ${sourceVersion}`);
}

docker(["exec", container, "dropdb", "-U", "postgres", "--if-exists", proofDatabase]);
try {
  docker(["exec", container, "createdb", "-U", "postgres", "-T", "template0", proofDatabase]);
  psql(
    proofDatabase,
    `drop schema public cascade;
     create schema extensions;
     create extension pgcrypto with schema extensions;
     create extension "uuid-ossp" with schema extensions;`,
  );
  const schemaDump = docker([
    "exec", container, "pg_dump", "-U", "postgres", "-d", sourceDatabase,
    "--schema-only", "--no-owner", "--no-privileges", "--schema=public",
    "--schema=auth", "--schema=supabase_migrations",
  ]);
  psql(proofDatabase, schemaDump);
  psql(proofDatabase, "grant usage on schema public to anon, authenticated, service_role;");

  const ledgerDump = docker([
    "exec", container, "pg_dump", "-U", "postgres", "-d", sourceDatabase,
    "--data-only", "--inserts", "--no-owner", "--no-privileges",
    "--table=supabase_migrations.schema_migrations",
  ]);
  psql(proofDatabase, ledgerDump);

  const policyData = docker([
    "exec", container, "pg_dump", "-U", "postgres", "-d", sourceDatabase,
    "--data-only", "--no-owner", "--no-privileges",
    "--table=public.adle_review_policy_versions",
  ]);
  psql(proofDatabase, policyData);

  psql(proofDatabase, `
    insert into supabase_migrations.schema_migrations(version,name) values
      ('20260421','add_false_positive_to_misspelling_instances'),
      ('20260707120000','fix_teaching_dictionary_display_word_data_quality'),
      ('20260731200000','add_adle_generic_snapshot_persistence_v2'),
      ('20260804234500','add_adle_canonical_intake_supabase_scheduler')
    on conflict(version) do nothing;
    create schema if not exists cron;
    create table cron.job(
      jobid bigint generated by default as identity primary key,
      schedule text, command text, nodename text default 'localhost',
      nodeport integer default 5432, database text default current_database(),
      username text default current_user, active boolean default true,
      jobname text unique
    );
    insert into cron.job(schedule,command,active,jobname) values(
      '*/5 * * * *','select public.adle_dispatch_canonical_intake_safety_sweep();',
      true,'adle-canonical-intake-production-safety-sweep-v1'
    );
  `);

  const forwardMigrations = [
    "20260807130000_add_canonical_misspelling_intake.sql",
    "20260807173000_add_editable_writing_issue_reason_drafts.sql",
    "20260828120000_make_parent_approval_occurrence_complete.sql",
    "20260828130000_authorize_exact_id_canonical_intake_handoff.sql",
    "20260828140000_reconcile_downstream_spelling_authority.sql",
    "20260828150000_materialize_r8e_stage_f_historical_occurrence_sources.sql",
    "20260828160000_complete_governed_blocked_word_auto_resume.sql",
  ];
  for (const name of forwardMigrations) {
    psql(proofDatabase, readFileSync(resolve(root, "supabase/migrations", name), "utf8"));
    recordMigration(proofDatabase, name);
  }
  psql(proofDatabase, `
    revoke all on function public.persist_adle_composed_daily_plan_v1(uuid,uuid,date,jsonb,jsonb,jsonb) from public,anon,authenticated;
    grant execute on function public.persist_adle_composed_daily_plan_v1(uuid,uuid,date,jsonb,jsonb,jsonb) to service_role;
    revoke all on function public.persist_adle_generic_daily_plan_v2(uuid,uuid,date,jsonb,jsonb,jsonb,jsonb) from public,anon,authenticated;
    grant execute on function public.persist_adle_generic_daily_plan_v2(uuid,uuid,date,jsonb,jsonb,jsonb,jsonb) to service_role;
    revoke all on function public.persist_adle_base_word_family_pilot_v1(uuid,uuid,date,jsonb,jsonb) from public,anon,authenticated;
    grant execute on function public.persist_adle_base_word_family_pilot_v1(uuid,uuid,date,jsonb,jsonb) to service_role;
    revoke all on function public.persist_adle_base_word_family_pilot_v2(uuid,uuid,date,jsonb,jsonb,jsonb,uuid,uuid,text,text) from public,anon,authenticated;
    grant execute on function public.persist_adle_base_word_family_pilot_v2(uuid,uuid,date,jsonb,jsonb,jsonb,uuid,uuid,text,text) to service_role;
    revoke all on function public.complete_adle_word_lab_v1(uuid,uuid,uuid,date,text,text,uuid[],jsonb,jsonb,jsonb) from public,anon,authenticated;
    grant execute on function public.complete_adle_word_lab_v1(uuid,uuid,uuid,date,text,text,uuid[],jsonb,jsonb,jsonb) to service_role;
    revoke all on function public.adle_generic_lesson_snapshot_is_structurally_valid(jsonb) from public,anon;
    grant execute on function public.adle_generic_lesson_snapshot_is_structurally_valid(jsonb) to service_role,authenticated;
    revoke all on function public.adle_generic_lesson_snapshot_is_structurally_valid_v2(jsonb) from public,anon;
    grant execute on function public.adle_generic_lesson_snapshot_is_structurally_valid_v2(jsonb) to service_role,authenticated;
    revoke all on function public.adle_lesson_snapshot_is_structurally_valid(jsonb) from public,anon;
    grant execute on function public.adle_lesson_snapshot_is_structurally_valid(jsonb) to service_role,authenticated;
  `);
  if (Number(psql(
    proofDatabase,
    "select count(*) from supabase_migrations.schema_migrations;",
  ).trim()) !== 109) {
    throw new Error("Disposable C2B.2 ancestry did not reach the 109-migration E7A baseline");
  }
  const retirementMigration = "20260829133000_retire_verified_adle_legacy_database_functions.sql";
  psql(
    proofDatabase,
    readFileSync(resolve(root, "supabase/migrations", retirementMigration), "utf8"),
  );
  recordMigration(proofDatabase, retirementMigration);

  psql(proofDatabase, `
    insert into public.canonical_teaching_dictionary_import_batches (
      id, source_folder_path, import_mode, batch_status
    ) values (
      'c2b2f000-0000-4000-8000-000000000001',
      'disposable/c2b2-preexisting', 'local_dev_import', 'applied'
    );
    insert into public.canonical_teaching_dictionary_words (
      id, import_batch_id, row_status, source_sheet, source_row_number,
      source_row_hash, word_key, normalised_word, display_word,
      source_category, confidence, review_status
    ) values (
      'c2b2f000-0000-4000-8000-000000000002',
      'c2b2f000-0000-4000-8000-000000000001', 'active', 'proof', 2,
      repeat('f',64), 'c2b2-preexisting', 'c2b2preexisting', 'c2b2preexisting',
      'internal_reviewed_seed', 'high', 'approved_for_first_exposure'
    );
    insert into auth.users (
      instance_id, id, aud, role, email, encrypted_password,
      email_confirmed_at, raw_app_meta_data, raw_user_meta_data, created_at, updated_at
    ) values (
      '00000000-0000-0000-0000-000000000000',
      'c2b2f000-0000-4000-8000-000000000003',
      'authenticated', 'authenticated', 'c2b2-preexisting@example.test', '',
      timezone('utc',now()), '{}'::jsonb, '{}'::jsonb,
      timezone('utc',now()), timezone('utc',now())
    );
    insert into public.children (id,parent_user_id,first_name) values (
      'c2b2f000-0000-4000-8000-000000000004',
      'c2b2f000-0000-4000-8000-000000000003', 'Preexisting'
    );
    insert into public.adle_review_bundles (
      id,child_id,source_ref,interval_index,next_due_on,
      schedule_policy_version,bundle_status,row_status
    ) values (
      'c2b2f000-0000-4000-8000-000000000005',
      'c2b2f000-0000-4000-8000-000000000004', 'preexisting', 1,
      '2099-02-01', 'review_policy_v1_2026-07-04', 'active', 'active'
    );
    insert into public.adle_review_schedule_words (
      id,child_id,canonical_word_id,bundle_id,membership_status,taught_on,
      row_status,word_schedule_version,word_interval_index,word_next_due_on,
      word_schedule_policy_version,word_schedule_transition_count
    ) values (
      'c2b2f000-0000-4000-8000-000000000006',
      'c2b2f000-0000-4000-8000-000000000004',
      'c2b2f000-0000-4000-8000-000000000002',
      'c2b2f000-0000-4000-8000-000000000005', 'scheduled', '2099-01-01',
      'active', 'adle_review_per_word_schedule_v1', 1, '2099-02-01',
      'review_policy_v1_2026-07-04', 7
    );
  `);
  const beforeRow = psql(proofDatabase, `
    select to_jsonb(word) - array['created_at','updated_at']::text[]
    from public.adle_review_schedule_words word
    where id='c2b2f000-0000-4000-8000-000000000006';
  `).trim();

  const migration = readFileSync(migrationPath, "utf8");
  psql(proofDatabase, migration);
  const afterRowWithoutNewFields = psql(proofDatabase, `
    select to_jsonb(word)
      - array['created_at','updated_at','consecutive_independent_failures','failure_episode_id']::text[]
    from public.adle_review_schedule_words word
    where id='c2b2f000-0000-4000-8000-000000000006';
  `).trim();
  if (afterRowWithoutNewFields !== beforeRow) {
    throw new Error("C2B.2 migration changed a pre-existing current-policy schedule row");
  }
  const postMigrationFacts = JSON.parse(psql(proofDatabase, `
    select jsonb_build_object(
      'preexistingTargetFieldsNull', (
        select consecutive_independent_failures is null and failure_episode_id is null
        from public.adle_review_schedule_words
        where id='c2b2f000-0000-4000-8000-000000000006'
      ),
      'targetScheduleRowsBeforeFixture', (
        select count(*) from public.adle_review_schedule_words
        where word_schedule_version='adle_review_per_word_schedule_v2'
      ),
      'currentPolicyStillActive', (
        select is_active from public.adle_review_policy_versions
        where schedule_policy_version='review_policy_v1_2026-07-04'
      ),
      'targetPolicyActive', (
        select is_active from public.adle_review_policy_versions
        where schedule_policy_version='ADLE_SPACED_REVIEW_REGRESSION_V1'
      ),
      'targetPolicyDefault', (
        select is_default_for_new_schedules from public.adle_review_policy_versions
        where schedule_policy_version='ADLE_SPACED_REVIEW_REGRESSION_V1'
      )
    );
  `).trim()) as Record<string, boolean | number>;
  if (postMigrationFacts.preexistingTargetFieldsNull !== true
    || postMigrationFacts.targetScheduleRowsBeforeFixture !== 0
    || postMigrationFacts.currentPolicyStillActive !== true
    || postMigrationFacts.targetPolicyActive !== false
    || postMigrationFacts.targetPolicyDefault !== false) {
    throw new Error(`C2B.2 post-migration boundary failed: ${JSON.stringify(postMigrationFacts)}`);
  }

  const fixtureOutput = psql(
    proofDatabase,
    readFileSync(resolve(root, "scripts/sql/prove-adle-c2b2-scheduler-persistence-local.sql"), "utf8"),
  );
  const receiptLine = fixtureOutput.split("\n").find((line) => line.startsWith("C2B2_SQL_RECEIPT:"));
  if (!receiptLine) throw new Error(`C2B.2 SQL proof returned no receipt:\n${fixtureOutput}`);
  const receipt = JSON.parse(receiptLine.slice("C2B2_SQL_RECEIPT:".length));
  let c2b6Receipt: unknown = null;
  let c2b7Receipt: unknown = null;
  let fr2Receipt: unknown = null;
  let fr3Receipt: unknown = null;
  let fr2PreexistingSchedulesStable = false;
  if (proveC2B6) {
    const c2b6Migration = readFileSync(resolve(root, "supabase/migrations", c2b6MigrationName), "utf8");
    psql(proofDatabase, c2b6Migration);
    recordMigration(proofDatabase, c2b6MigrationName);
    const c2b6Output = psql(
      proofDatabase,
      readFileSync(resolve(root, "scripts/sql/prove-adle-c2b6-controlled-opt-in-local.sql"), "utf8"),
    );
    const c2b6Line = c2b6Output.split("\n").find((line) => line.startsWith("C2B6_SQL_RECEIPT:"));
    if (!c2b6Line) throw new Error(`C2B.6 SQL proof returned no receipt:\n${c2b6Output}`);
    c2b6Receipt = JSON.parse(c2b6Line.slice("C2B6_SQL_RECEIPT:".length));
    if (proveC2B7) {
      const c2b7Migration = readFileSync(resolve(root, "supabase/migrations", c2b7MigrationName), "utf8");
      psql(proofDatabase, c2b7Migration);
      recordMigration(proofDatabase, c2b7MigrationName);

      const microsecond = "2026-09-01T12:04:44.123456+00:00";
      const occurredAt = canonicalUtcTimestampMilliseconds(microsecond);
      const parityEnvelope = {
        scheduleWordId: "00000000-0000-4000-8000-000000000703",
        transitionKind: "REVIEW_OUTCOME_APPLIED",
        sourceReviewOutcomeEventId: "00000000-0000-4000-8000-000000000704",
        sourceControlledGraduationReceiptId: null,
        idempotencyKey: "review-outcome:00000000-0000-4000-8000-000000000704",
        expectedStateRevision: 0,
        occurredAt,
      };
      const envelopeJson = JSON.stringify(parityEnvelope);
      const sqlFacts = JSON.parse(psql(proofDatabase, `
        select jsonb_build_object(
          'normalizedTimestamp', jsonb_build_object(
            'value', date_trunc('milliseconds','${microsecond}'::timestamptz)
          )->>'value',
          'sqlFingerprint', public.adle_canonical_json_sha256_v1(
            $c2b7$${envelopeJson}$c2b7$::jsonb
          ),
          'prepareUsesCanonicalMilliseconds', position(
            'date_trunc(''milliseconds'',clock_timestamp())'
            in regexp_replace(pg_get_functiondef(
              'public.prepare_adle_review_finalization_c2b6(uuid,text)'::regprocedure
            ), '\\s+', ' ', 'g')
          ) > 0
        );
      `).trim()) as {
        normalizedTimestamp: string;
        sqlFingerprint: string;
        prepareUsesCanonicalMilliseconds: boolean;
      };
      const tsFingerprint = fingerprintSnapshotValue(parityEnvelope);
      if (sqlFacts.normalizedTimestamp !== occurredAt
        || sqlFacts.sqlFingerprint !== tsFingerprint
        || sqlFacts.prepareUsesCanonicalMilliseconds !== true) {
        throw new Error(`C2B.7 timestamp/fingerprint parity failed: ${JSON.stringify({
          occurredAt, tsFingerprint, ...sqlFacts,
        })}`);
      }
      c2b7Receipt = {
        canonicalMicrosecondInput: microsecond,
        canonicalMillisecondOutput: occurredAt,
        tsFingerprint,
        sqlFingerprint: sqlFacts.sqlFingerprint,
        fingerprintsIdentical: true,
        prepareUsesCanonicalMilliseconds: true,
      };
    }
  }
  if (proveFR2) {
    const schedulesBefore = psql(proofDatabase, `
      select coalesce(jsonb_agg(
        to_jsonb(word) - array['updated_at']::text[] order by word.id
      ), '[]'::jsonb)
      from public.adle_review_schedule_words word;
    `).trim();
    const fr2Migration = readFileSync(resolve(root, "supabase/migrations", fr2MigrationName), "utf8");
    psql(proofDatabase, fr2Migration);
    recordMigration(proofDatabase, fr2MigrationName);
    const schedulesAfter = psql(proofDatabase, `
      select coalesce(jsonb_agg(
        to_jsonb(word)
          - array['updated_at','pre_retirement_check_outcome_event_id']::text[]
        order by word.id
      ), '[]'::jsonb)
      from public.adle_review_schedule_words word;
    `).trim();
    const fr2Boundary = JSON.parse(psql(proofDatabase, `
      select jsonb_build_object(
        'newLineageNull', not exists (
          select 1 from public.adle_review_schedule_words
          where pre_retirement_check_outcome_event_id is not null
        ),
        'receiptRows', (
          select count(*) from public.adle_review_retirement_decision_receipts
        ),
        'targetActive', (
          select is_active from public.adle_review_policy_versions
          where schedule_policy_version='ADLE_SPACED_REVIEW_REGRESSION_V1'
        ),
        'targetDefault', (
          select is_default_for_new_schedules
          from public.adle_review_policy_versions
          where schedule_policy_version='ADLE_SPACED_REVIEW_REGRESSION_V1'
        )
      );
    `).trim()) as {
      newLineageNull: boolean;
      receiptRows: number;
      targetActive: boolean;
      targetDefault: boolean;
    };
    fr2PreexistingSchedulesStable = schedulesBefore === schedulesAfter;
    if (!fr2PreexistingSchedulesStable
      || !fr2Boundary.newLineageNull
      || fr2Boundary.receiptRows !== 0
      || fr2Boundary.targetActive
      || fr2Boundary.targetDefault) {
      throw new Error(`FR.2 additive boundary failed: ${JSON.stringify({
        fr2PreexistingSchedulesStable, ...fr2Boundary,
      })}`);
    }
    const fr2Output = psql(
      proofDatabase,
      readFileSync(resolve(root, "scripts/sql/prove-adle-fr2-retirement-persistence-local.sql"), "utf8"),
    );
    const fr2Line = fr2Output.split("\n").find((line) => line.startsWith("FR2_SQL_RECEIPT:"));
    if (!fr2Line) throw new Error(`FR.2 SQL proof returned no receipt:\n${fr2Output}`);
    fr2Receipt = JSON.parse(fr2Line.slice("FR2_SQL_RECEIPT:".length));
    if (proveFR3) {
      const schedulesBeforeFR3 = psql(proofDatabase, `
        select coalesce(jsonb_agg(to_jsonb(word) order by word.id), '[]'::jsonb)
        from public.adle_review_schedule_words word;
      `).trim();
      const fr3Migration = readFileSync(resolve(root, "supabase/migrations", fr3MigrationName), "utf8");
      psql(proofDatabase, fr3Migration);
      recordMigration(proofDatabase, fr3MigrationName);
      const schedulesAfterFR3 = psql(proofDatabase, `
        select coalesce(jsonb_agg(to_jsonb(word) order by word.id), '[]'::jsonb)
        from public.adle_review_schedule_words word;
      `).trim();
      if (schedulesBeforeFR3 !== schedulesAfterFR3) {
        throw new Error("FR.3 migration changed schedule rows");
      }
      const fr3Output = psql(
        proofDatabase,
        readFileSync(resolve(root, "scripts/sql/prove-adle-fr3-final-rung-runtime-local.sql"), "utf8"),
      );
      const fr3Line = fr3Output.split("\n").find((line) => line.startsWith("FR3_SQL_RECEIPT:"));
      if (!fr3Line) throw new Error(`FR.3 SQL proof returned no receipt:\n${fr3Output}`);
      fr3Receipt = JSON.parse(fr3Line.slice("FR3_SQL_RECEIPT:".length));
    }
  }
  const migrationFingerprint = createHash("sha256").update(migration).digest("hex");
  console.log(JSON.stringify({
    status: "PASS",
    sourceSchema: `production-shaped through ${sourceVersion}`,
    forwardMigrationsAppliedBeforeC2B2: forwardMigrations.map((name) => name.slice(0, 14)),
    c2b2Migration: migrationName,
    c2b2MigrationSha256: migrationFingerprint,
    preexistingCurrentRowByteStable: true,
    noTargetScheduleBackfill: true,
    ...postMigrationFacts,
    fixture: receipt,
    ...(proveC2B6 ? {
      c2b6Migration: c2b6MigrationName,
      c2b6MigrationSha256: createHash("sha256").update(readFileSync(
        resolve(root, "supabase/migrations", c2b6MigrationName),
      )).digest("hex"),
      c2b6Fixture: c2b6Receipt,
    } : {}),
    ...(proveC2B7 ? {
      c2b7Migration: c2b7MigrationName,
      c2b7MigrationSha256: createHash("sha256").update(readFileSync(
        resolve(root, "supabase/migrations", c2b7MigrationName),
      )).digest("hex"),
      c2b7Fixture: c2b7Receipt,
    } : {}),
    ...(proveFR2 ? {
      fr2Migration: fr2MigrationName,
      fr2MigrationSha256: createHash("sha256").update(readFileSync(
        resolve(root, "supabase/migrations", fr2MigrationName),
      )).digest("hex"),
      fr2PreexistingSchedulesStable,
      fr2Fixture: fr2Receipt,
    } : {}),
    ...(proveFR3 ? {
      fr3Migration: fr3MigrationName,
      fr3MigrationSha256: createHash("sha256").update(readFileSync(
        resolve(root, "supabase/migrations", fr3MigrationName),
      )).digest("hex"),
      fr3Fixture: fr3Receipt,
    } : {}),
    disposableDatabaseDropped: true,
  }, null, 2));
} finally {
  docker(["exec", container, "dropdb", "-U", "postgres", "--if-exists", proofDatabase]);
}
