import assert from "node:assert/strict";
import { parseWordSkillCandidates, parsePairDecisions, candidatePreviewAssociations, reviewPairReadiness } from "../lib/writing-engine/whole-writing/knowledge-review";
import { publishedAssociationsToPhaseB } from "../lib/writing-engine/whole-writing/knowledge";
import { adaptExplicitReviewedAssociations } from "../lib/adle/word-skill-relationships/adapters";
import { readCanonicalWordSkillRelationships } from "../lib/adle/word-skill-relationships/authority";

const word = "00000000-0000-0000-0000-000000000001";
const candidate = { canonicalWordId: word, microSkillKey: "skill", relationshipRole: "demonstrates", sourceReference: "synthetic", licenceReference: "original fixture", method: "batch_ai_candidate" };
const candidates = parseWordSkillCandidates(JSON.stringify([{ ...candidate, decision: "approved", reviewedBy: "spoof" }]));
assert.equal("decision" in candidates[0], false);
assert.equal("reviewedBy" in candidates[0], false);
for (const input of ["null", "{}", "[]", "invalid", JSON.stringify([candidate, candidate]), JSON.stringify([{ ...candidate, relationshipRole: "guessed" }]), JSON.stringify([{ ...candidate, method: "automatic_approval" }]), JSON.stringify([{ ...candidate, licenceReference: " " }])]) assert.throws(() => parseWordSkillCandidates(input));
const form = new FormData(); form.set("decision_0", "approved");
assert.deepEqual(parsePairDecisions(form, 1), ["approved"]);
assert.throws(() => parsePairDecisions(form, 2));
form.append("decision_0", "rejected"); assert.throws(() => parsePairDecisions(form, 1));
const words = [{ canonicalWordId: word, normalisedWord: "synthetic", state: "active" as const, identityStable: true }];
const microSkills = ["skill", "other"].map(microSkillKey => ({ microSkillKey, state: "active" as const, identityStable: true }));
const proposal = candidatePreviewAssociations("package", candidates);
const read = (rows: typeof proposal) => readCanonicalWordSkillRelationships({ words, microSkills, facts: adaptExplicitReviewedAssociations(rows) });
let result = read(proposal);
assert.equal(result.relationships.length, 1);
assert.equal(reviewPairReadiness(result, "package", candidates[0], 0).ready, true);
assert.equal(candidatePreviewAssociations("package", candidates, ["rejected"]).length, 0);
const conflict = { ...proposal[0], associationId: "existing-negative", relationshipRole: "negative_only" as const };
result = read([...proposal, conflict]);
assert.equal(result.relationships.length, 0);
assert.equal(reviewPairReadiness(result, "package", candidates[0], 0).ready, false);
assert.ok(reviewPairReadiness(result, "package", candidates[0], 0).reasons.includes("IRRECONCILABLE_ACTIVE_ROLES"));
const contrast = parseWordSkillCandidates(JSON.stringify([{ ...candidate, relationshipRole: "contrast_only" }]));
result = read(candidatePreviewAssociations("contrast", contrast));
assert.equal(result.relationships.length, 0);
assert.equal(reviewPairReadiness(result, "contrast", contrast[0], 0).ready, true);
const published = { id: "pair", release_id: "release", canonical_word_id: word, micro_skill_key: "skill", relationship_role: "demonstrates" as const, source_reference: "synthetic", licence_reference: "original" };
const releases = new Map([["release", { release_key: "synthetic", reviewed_by: "reviewer" }]]);
assert.equal(read(publishedAssociationsToPhaseB([published], releases, new Set())).relationships.length, 1);
assert.equal(read(publishedAssociationsToPhaseB([published], releases, new Set(["release"]))).relationships.length, 0);
assert.equal(read(proposal).relationships.some(r => r.microSkillKey === "other"), false);
console.log("Word–skill review regression passed: candidate boundary, pair decisions, conflicts, non-positive roles and withdrawal.");
