"use client";

import { useEffect, useMemo, useState } from "react";

import { CoverShutter, DiffReveal, HearWordButton, SnapRail, SplitHandle } from "@/components/adle/activities/shared";
import type { BaseWordFamilyLessonSnapshotV1, BaseWordFamilySnapshotWord } from "@/lib/adle/morphology/base-word-family-payload";
import { baseWordFamilyResumeKey, normaliseBaseWordFamilyResume, type BaseWordFamilyResumeState } from "@/lib/adle/morphology/base-word-family-resume";
import { WordLabScene } from "./word-lab-scene";

const INITIAL: BaseWordFamilyResumeState = {
  stage: "intro", familyIndex: 0, cleaveIndex: 0, cleaveStep: 0, cleaveMisses: {}, buildIndex: 0,
  controlledIndex: 0, dictationIndex: 0, controlledAttempts: {}, controlledChecked: {}, sentenceAttempts: {}, sentenceChecked: false, reflectionText: "",
};

type Part = { id: string; surfaceText: string; gloss?: string; kind?: string };
function parts(word: BaseWordFamilySnapshotWord): Part[] { return word.parts.filter((part): part is Part => !!part && typeof part === "object" && typeof (part as Part).id === "string" && typeof (part as Part).surfaceText === "string"); }
function splitPoints(word: BaseWordFamilySnapshotWord): number[] { let position = 0; return parts(word).slice(0, -1).map((part) => (position += part.surfaceText.length)); }

export function BaseWordFamilyGuidedLesson(props: {
  previewId?: string; assignmentId?: string; payload: BaseWordFamilyLessonSnapshotV1;
  onPreviewComplete?: (reflection: string) => void;
  onComplete?: (input: { reflection: string; controlledAttempts: Record<string, string>; sentenceAttempts: Record<string, string> }) => void;
}) {
  const [state, setState] = useState<BaseWordFamilyResumeState>(INITIAL);
  const [hydrated, setHydrated] = useState(false);
  const key = baseWordFamilyResumeKey(props.assignmentId ?? props.previewId ?? "base-word-family", props.payload.contentVersion);
  const update = (patch: Partial<BaseWordFamilyResumeState>) => setState((current) => ({ ...current, ...patch }));
  useEffect(() => { try { const saved = window.localStorage.getItem(key); const restored = saved ? normaliseBaseWordFamilyResume(JSON.parse(saved), props.payload) : null; if (restored) setState(restored); } catch { /* Resume is optional. */ } setHydrated(true); }, [key, props.payload]);
  useEffect(() => { if (!hydrated) return; try { window.localStorage.setItem(key, JSON.stringify(state)); } catch { /* Resume is optional. */ } }, [hydrated, key, state]);
  if (!hydrated) return <div role="status" aria-live="polite" className="brand-card rounded-3xl p-8 text-center text-sm text-[color:var(--mid)]">Preparing the base-word Word Lab…</div>;
  const guidedWords = props.payload.familySections.flatMap((section) => section.guidedWords);
  const independent = props.payload.independentWords[state.stage === "controlled" ? state.controlledIndex : state.dictationIndex];
  const phase = state.stage === "intro" ? 0 : state.stage === "families" ? 1 : state.stage === "cleave" ? 2 : state.stage === "word_sums" ? 4 : state.stage === "controlled" ? 5 : 5;
  return <WordLabScene beat={{ id: "base-word-family", activityId: state.stage, state: "guideSilent", goal: "Find the familiar base word.", waitFor: "the next step", onComplete: "done" }} phase={phase} muted={false} onMutedChange={() => undefined} silent={state.stage === "controlled" || state.stage === "dictation"}>
    {state.stage === "intro" ? <Intro payload={props.payload} onNext={() => update({ stage: "families" })} /> : null}
    {state.stage === "families" ? <FamilyReveal section={props.payload.familySections[state.familyIndex]} number={state.familyIndex + 1} total={props.payload.familySections.length} onNext={() => update({ stage: "cleave", cleaveIndex: state.familyIndex, cleaveStep: 0 })} /> : null}
    {state.stage === "cleave" ? <Cleave word={guidedWords.find((word) => word.canonicalWordId === props.payload.authenticTargets[state.cleaveIndex].canonicalWordId)!} step={state.cleaveStep} misses={state.cleaveMisses} onMiss={(id, misses) => update({ cleaveMisses: { ...state.cleaveMisses, [id]: misses } })} onNext={(nextStep) => { const currentWord = guidedWords.find((word) => word.canonicalWordId === props.payload.authenticTargets[state.cleaveIndex].canonicalWordId)!; if (nextStep < splitPoints(currentWord).length) update({ cleaveStep: nextStep }); else if (state.cleaveIndex + 1 < props.payload.authenticTargets.length) update({ stage: "families", familyIndex: state.cleaveIndex + 1, cleaveStep: 0 }); else update({ stage: "word_sums", buildIndex: 0 }); }} /> : null}
    {state.stage === "word_sums" ? <WordBuilder words={guidedWords} index={state.buildIndex} onNext={() => state.buildIndex + 1 < guidedWords.length ? update({ buildIndex: state.buildIndex + 1 }) : update({ stage: "controlled" })} /> : null}
    {state.stage === "controlled" ? <Controlled word={independent} index={state.controlledIndex} total={props.payload.independentWords.length} attempt={state.controlledAttempts[independent.canonicalWordId] ?? ""} checked={state.controlledChecked[independent.canonicalWordId] === true} onAttempt={(attempt) => update({ controlledAttempts: { ...state.controlledAttempts, [independent.canonicalWordId]: attempt } })} onChecked={() => update({ controlledChecked: { ...state.controlledChecked, [independent.canonicalWordId]: true } })} onNext={() => state.controlledIndex + 1 < props.payload.independentWords.length ? update({ controlledIndex: state.controlledIndex + 1 }) : update({ stage: "dictation", dictationIndex: 0 })} /> : null}
    {state.stage === "dictation" ? <Dictation word={independent} index={state.dictationIndex} total={props.payload.independentWords.length} value={state.sentenceAttempts[independent.canonicalWordId] ?? ""} checked={state.sentenceChecked} onValue={(value) => update({ sentenceAttempts: { ...state.sentenceAttempts, [independent.canonicalWordId]: value } })} onCheck={() => update({ sentenceChecked: true })} onNext={() => state.dictationIndex + 1 < props.payload.independentWords.length ? update({ dictationIndex: state.dictationIndex + 1, sentenceChecked: false }) : update({ stage: "reflect", sentenceChecked: false })} /> : null}
    {state.stage === "reflect" ? <Reflection prompt={props.payload.reflectionPrompt} value={state.reflectionText} completionLabel={props.onComplete ? "Finish Word Lab" : "Finish preview"} onValue={(reflectionText) => update({ reflectionText })} onComplete={() => { props.onPreviewComplete?.(state.reflectionText); props.onComplete?.({ reflection: state.reflectionText, controlledAttempts: state.controlledAttempts, sentenceAttempts: state.sentenceAttempts }); }} /> : null}
  </WordLabScene>;
}

function Intro(props: { payload: BaseWordFamilyLessonSnapshotV1; onNext: () => void }) { return <section className="grid gap-5 text-center"><p className="text-xs font-black uppercase tracking-[.2em] text-cyan-200">Base-word strategy</p><h1 className="text-3xl font-black text-white">A familiar base can help you spell bigger words.</h1><p className="mx-auto max-w-2xl text-lg leading-8 text-cyan-50">Today we will look for a base word that stays inside a longer word. Knowing one spelling can help with many related words.</p><div className="grid gap-3 sm:grid-cols-2">{props.payload.authenticTargets.map((target) => <article key={target.canonicalWordId} className="rounded-2xl bg-white p-4 text-slate-950"><p className="text-xs font-black uppercase tracking-[.16em] text-slate-500">A word from your writing</p><p className="mt-1 text-2xl font-black">{props.payload.familySections.flatMap((section) => section.guidedWords).find((word) => word.canonicalWordId === target.canonicalWordId)?.displayWord}</p></article>)}</div><button type="button" onClick={props.onNext} className="mx-auto min-h-12 rounded-full bg-cyan-300 px-7 font-black text-slate-950">Meet the word families</button></section>; }

function FamilyReveal(props: { section: BaseWordFamilyLessonSnapshotV1["familySections"][number]; number: number; total: number; onNext: () => void }) { const [revealed, setRevealed] = useState(false); const target = props.section.guidedWords.find((word) => props.section.authenticTargetWordIds.includes(word.canonicalWordId))!; return <section className="grid gap-5 text-center"><p className="text-xs font-black uppercase tracking-[.2em] text-cyan-200">Family {props.number} of {props.total}</p><h2 className="text-3xl font-black text-white">Tap the word to meet its family</h2><button type="button" onClick={() => setRevealed(true)} aria-expanded={revealed} className="mx-auto rounded-2xl bg-amber-100 px-7 py-5 text-3xl font-black text-amber-950 focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-cyan-300">{target.displayWord}</button>{revealed ? <><p className="text-lg text-cyan-50">The familiar base is <strong>{props.section.baseWord.displayWord}</strong>: {props.section.baseMeaning}.</p><div className="grid gap-3 sm:grid-cols-2">{props.section.guidedWords.map((word, index) => <article key={word.canonicalWordId} className="rounded-2xl bg-white p-4 text-left text-slate-950 motion-safe:animate-[fade-in_300ms_ease-out_both]" style={{ animationDelay: `${index * 90}ms` }}><p className="text-xl font-black">{word.displayWord}</p><p className="mt-1 text-sm font-semibold text-slate-600">{word.childFriendlyMeaning}</p></article>)}</div><button type="button" onClick={props.onNext} className="mx-auto min-h-12 rounded-full bg-cyan-300 px-7 font-black text-slate-950">Cleave out the base</button></> : <p className="text-cyan-50">Tap to see the related words jump out.</p>}</section>; }

function Cleave(props: { word: BaseWordFamilySnapshotWord; step: number; misses: Record<string, number>; onMiss: (id: string, misses: number) => void; onNext: (nextStep: number) => void }) { const points = splitPoints(props.word); const point = points[props.step]; const key = `${props.word.canonicalWordId}:${point}`; const before = props.word.displayWord.slice(0, point); const after = props.word.displayWord.slice(point); return <section className="grid gap-4 text-center"><p className="text-xs font-black uppercase tracking-[.2em] text-cyan-200">Find the word parts</p><h2 className="text-3xl font-black text-white">Cleave after the part that comes before <span className="text-amber-200">{after}</span>.</h2><SplitHandle word={props.word.displayWord} splitPoints={[point]} misses={props.misses[key] ?? 0} correct={false} missMessage="Try again. Look for the edge of a meaningful word part." repeatedMissMessage={`The split is ${before} | ${after}.`} correctHeading={`Yes — ${before} and ${after} are separate word parts.`} correctExplanation={props.word.wordSum} continueLabel={props.step + 1 < points.length ? "Find the other edge of the base" : "Build words from meanings"} onMiss={(misses) => props.onMiss(key, misses)} onCorrect={() => undefined} onContinue={() => props.onNext(props.step + 1)} /></section>; }

function WordBuilder(props: { words: BaseWordFamilySnapshotWord[]; index: number; onNext: () => void }) { const word = props.words[props.index]; const allParts = useMemo(() => [...new Map(props.words.flatMap(parts).map((part) => [part.surfaceText, part])).values()], [props.words]); const expectedParts = parts(word); const distractors = allParts.filter((part) => !expectedParts.some((expected) => expected.surfaceText === part.surfaceText)).slice(0, 3); const tiles = [...expectedParts, ...distractors].map((part, index) => ({ id: `${word.canonicalWordId}:${part.surfaceText}:${index}`, text: part.surfaceText, role: part.kind === "prefix" ? "prefix" as const : part.kind === "suffix" ? "suffix" as const : "base" as const, gloss: part.gloss })); const expectedIds = expectedParts.map((part, index) => `${word.canonicalWordId}:${part.surfaceText}:${index}`); const [done, setDone] = useState(false); return <section className="grid gap-5 text-center"><p className="text-xs font-black uppercase tracking-[.2em] text-cyan-200">Build {props.index + 1} of {props.words.length}</p><h2 className="text-3xl font-black text-white">Which word means “{word.childFriendlyMeaning}”?</h2><SnapRail tiles={tiles} expectedIds={expectedIds} label={`Build ${word.displayWord} from word parts`} onComplete={() => setDone(true)} onInvalid={() => undefined} />{done ? <><p className="rounded-2xl bg-emerald-100 p-4 font-black text-emerald-950">{word.wordSum} — {word.childFriendlyMeaning}</p><button type="button" onClick={props.onNext} className="mx-auto min-h-12 rounded-full bg-cyan-300 px-7 font-black text-slate-950">{props.index + 1 < props.words.length ? "Build the next word" : "Practise six words"}</button></> : null}</section>; }

function Controlled(props: { word: BaseWordFamilySnapshotWord; index: number; total: number; attempt: string; checked: boolean; onAttempt: (value: string) => void; onChecked: () => void; onNext: () => void }) { return <section className="grid gap-4"><p className="text-center text-sm font-black uppercase tracking-[.2em] text-cyan-200">Word to remember {props.index + 1} of {props.total}</p><CoverShutter key={props.word.canonicalWordId} word={props.word.displayWord} splitPoints={[]} initialAttempt={props.attempt} initialState={props.checked ? "check" : props.attempt ? "write" : "look"} muted={false} onStateChange={(_, attempt) => attempt && props.onAttempt(attempt)} onComplete={(attempt) => { props.onAttempt(attempt); props.onChecked(); }} />{props.checked ? <button type="button" onClick={props.onNext} className="min-h-12 rounded-full bg-cyan-300 font-black text-slate-950">Continue</button> : null}</section>; }
function Dictation(props: { word: BaseWordFamilySnapshotWord; index: number; total: number; value: string; checked: boolean; onValue: (value: string) => void; onCheck: () => void; onNext: () => void }) { return <section className="grid gap-4"><p className="text-center text-sm font-black uppercase tracking-[.2em] text-cyan-200">Sentence {props.index + 1} of {props.total}</p><div className="flex justify-center"><HearWordButton word={props.word.audioText} label="Play sentence" muted={false} kind="dictation" /></div><label className="text-sm font-semibold text-cyan-50">Write the whole sentence<textarea autoFocus spellCheck={false} autoComplete="off" autoCapitalize="sentences" value={props.value} onChange={(event) => props.onValue(event.target.value)} className="mt-2 min-h-28 w-full rounded-2xl bg-white p-4 text-lg text-slate-950 focus:outline-none focus:ring-4 focus:ring-cyan-300/30" /></label>{!props.checked ? <button type="button" disabled={!props.value.trim()} onClick={props.onCheck} className="min-h-12 rounded-full bg-cyan-300 font-black text-slate-950 disabled:opacity-40">Check sentence</button> : <><DiffReveal attempt={props.value} expected={props.word.dictationSentence} mode="sentence" /><button type="button" onClick={props.onNext} className="min-h-12 rounded-full bg-cyan-300 font-black text-slate-950">{props.index + 1 < props.total ? "Next sentence" : "Reflect"}</button></>}</section>; }
function Reflection(props: { prompt: string; value: string; completionLabel: string; onValue: (value: string) => void; onComplete: () => void }) { return <section className="grid gap-5"><h2 className="text-center text-3xl font-black text-white">What did you notice?</h2><label className="text-base font-black text-white">{props.prompt}<textarea autoFocus required maxLength={2000} value={props.value} onChange={(event) => props.onValue(event.target.value)} className="mt-2 min-h-32 w-full rounded-2xl bg-white p-4 text-lg font-normal text-slate-950 focus:outline-none focus:ring-4 focus:ring-cyan-300/30" /></label><button type="button" disabled={!props.value.trim()} onClick={props.onComplete} className="min-h-12 rounded-full bg-cyan-300 font-black text-slate-950 disabled:opacity-40">{props.completionLabel}</button></section>; }
