"use client";

import { useEffect, useState } from "react";
import type { GuideBeatV1 } from "@/lib/adle/morphology/payload";
import { speakAuthoredNarration } from "@/components/adle/activities/shared/narration";

export function LessonGuide(props: { beat: GuideBeatV1; phaseCue: string; muted: boolean; onMutedChange: (muted: boolean) => void; silent?: boolean; help?: string }) {
  const [primed, setPrimed] = useState(false);
  const line = props.help ?? props.beat.say ?? "Take your time and work with the word.";
  useEffect(() => { if (primed && !props.muted && !props.silent && line) speakAuthoredNarration(props.beat.narration ?? line, "guide"); }, [line, primed, props.muted, props.silent, props.beat.narration]);
  return <aside className="flex h-full flex-col justify-between gap-5 rounded-3xl border border-cyan-300/20 bg-slate-950/75 p-5 text-white shadow-[0_20px_70px_rgba(8,47,73,.25)]"><div><div className={`mx-auto grid h-24 w-24 place-items-center rounded-full border-2 border-cyan-300/50 bg-gradient-to-br from-cyan-200 to-blue-400 shadow-[0_0_35px_rgba(103,232,249,.35)] ${props.silent ? "opacity-70" : "motion-safe:animate-[pulse_3s_ease-in-out_infinite]"}`} aria-label="Prefix Scout"><svg viewBox="0 0 80 80" role="img" aria-hidden="true" className="h-16 w-16"><path d="M18 54V27l22-13 22 13v27L40 67z" fill="#0f172a" opacity=".9"/><circle cx="31" cy="37" r="5" fill="#cffafe"/><circle cx="49" cy="37" r="5" fill="#cffafe"/><path d="M29 51c7 6 15 6 22 0" fill="none" stroke="#cffafe" strokeWidth="4" strokeLinecap="round"/><path d="M40 14v53" stroke="#67e8f9" strokeWidth="3" opacity=".55"/></svg></div><p className="mt-3 text-center text-xs font-black uppercase tracking-[0.25em] text-cyan-200">Prefix Scout</p></div><div className="min-h-28 rounded-2xl bg-white/8 p-4"><p className="text-lg font-semibold leading-snug">{props.silent ? "Listen, remember, and write." : line}</p><p className="mt-2 text-xs font-bold uppercase tracking-wide text-cyan-200">{props.silent ? "Quiet recall" : props.phaseCue}</p></div><div className="flex flex-wrap gap-2"><button type="button" onClick={() => { setPrimed(true); if (!props.muted && !props.silent) speakAuthoredNarration(props.beat.narration ?? line, "guide"); }} disabled={props.silent} className="min-h-11 flex-1 rounded-full border border-white/20 px-3 text-sm font-bold disabled:opacity-40">Hear guide</button><button type="button" onClick={() => props.onMutedChange(!props.muted)} className="min-h-11 rounded-full border border-white/20 px-4 text-sm font-bold" aria-pressed={props.muted}>{props.muted ? "Sound off" : "Sound on"}</button></div></aside>;
}
