"use client";

import { useEffect, useMemo, useState } from "react";
import { completeAdleLessonPartAction } from "@/app/learn/week/adle/actions";
import { BinSort, CoverShutter, DiffReveal, FlipToggle, HearWordButton, SnapRail, SplitHandle } from "@/components/adle/activities/shared";
import type { AdleSessionItem } from "@/lib/adle/loaders/daily-plan-surface";
import {
  morphologyResumeKey,
  normaliseMorphologyLessonResume,
  readMorphologyResume,
  writeMorphologyResume,
  type MorphologyLessonResumeState,
  type MorphologyLessonStage,
} from "@/lib/adle/morphology/resume";
import type { MorphologyLessonPayloadV1, MorphologyWordSnapshot } from "@/lib/adle/morphology/payload";
import { normaliseSessionWord } from "@/lib/adle/session-correctness";
import { WordLabScene } from "./word-lab-scene";

type Stage = MorphologyLessonStage;
type LessonState = MorphologyLessonResumeState;
const INITIAL: LessonState = { stage: "learn", introIndex: 0, discoverIndex: 0, splitMisses: 0, splitCorrect: false, splitDone: false, controlledIndex: 0, dictationIndex: 0, controlledAttempts: {}, controlledChecked: {}, sentenceAttempts: {}, checkedSentence: false, guidedBindings: [], muted: false, helpLevel: 0, reflectionText: "" };
const GUIDED_BINDINGS = ["guided-strip-unhappy", "guided-meaning-unfair", "guided-meaning-unkind", "guided-meaning-unlock", "guided-meaning-untidy", "guided-build-untidy"] as const;

function attemptsJson(entries: Record<string, string>): string { return JSON.stringify(Object.entries(entries).map(([key, attemptText]) => ({ key, attemptText }))); }
function bindingItem(items: readonly AdleSessionItem[], binding: string): AdleSessionItem | undefined { return items.find((item) => item.promptData.pilotActivityId === binding); }

export function MorphologyGuidedLesson(props: { childId: string; assignmentId: string; items: AdleSessionItem[]; payload: MorphologyLessonPayloadV1; onPreviewComplete?: (reflectionText: string) => void }) {
  const [state, setState] = useState<LessonState>(INITIAL); const [hydrated, setHydrated] = useState(false); const key = morphologyResumeKey(props.assignmentId, props.payload.contentVersion);
  useEffect(() => {
    const frame = window.requestAnimationFrame(() => {
      const restored = readMorphologyResume<unknown>(key, props.payload.contentVersion);
      const normalised = normaliseMorphologyLessonResume(restored, props.payload.words.lesson.map((word) => word.canonicalWordId), GUIDED_BINDINGS);
      if (normalised) setState(normalised);
      setHydrated(true);
    });
    return () => window.cancelAnimationFrame(frame);
  }, [key, props.payload.contentVersion, props.payload.words.lesson]);
  useEffect(() => { if (hydrated) writeMorphologyResume(key, props.payload.contentVersion, state); }, [hydrated, key, props.payload.contentVersion, state]);
  const beat = useMemo(() => state.stage === "learn" ? props.payload.guide.beats.filter((candidate) => candidate.activityId === "introduction")[state.introIndex] ?? props.payload.guide.beats[0] : props.payload.guide.beats.find((candidate) => candidate.activityId === activityId(state.stage)) ?? props.payload.guide.beats[0], [props.payload.guide.beats, state.introIndex, state.stage]);
  const phase = state.stage === "learn" ? 0 : state.stage === "discover" ? 1 : state.stage === "split" ? 2 : state.stage === "match" ? 3 : state.stage === "build" ? 4 : 5;
  const update = (patch: Partial<LessonState>) => setState((current) => ({ ...current, ...patch }));
  const completeBinding = (binding: string) => update({ guidedBindings: [...new Set([...state.guidedBindings, binding])] });
  const help = state.stage === "split" && state.splitMisses >= 2 ? beat.onRepeatedMisconception : state.helpLevel === 0 ? undefined : state.helpLevel === 1 ? beat.onHelpRequest ?? beat.onMisconception ?? beat.onSlip : beat.onRepeatedMisconception ?? beat.onMisconception ?? beat.onHelpRequest;
  if (!hydrated) return <div className="brand-card rounded-3xl p-8 text-center text-sm text-[color:var(--mid)]">Preparing the Word Lab…</div>;
  return <WordLabScene beat={beat} phase={phase} muted={state.muted} onMutedChange={(muted) => update({ muted })} silent={state.stage === "dictation" || state.stage === "controlled"} help={help} onHelp={() => update({ helpLevel: Math.min(2, state.helpLevel + 1) })}>
    {state.stage === "learn" ? <LearnIntroduction payload={props.payload} index={state.introIndex} onNext={() => state.introIndex < 2 ? update({ introIndex: state.introIndex + 1, helpLevel: 0 }) : update({ stage: "discover", helpLevel: 0 })} /> : null}
    {state.stage === "discover" ? <Discovery key={state.discoverIndex} payload={props.payload} index={state.discoverIndex} onNext={() => state.discoverIndex < 2 ? update({ discoverIndex: state.discoverIndex + 1, helpLevel: 0 }) : update({ stage: "split", helpLevel: 0 })} /> : null}
    {state.stage === "split" ? <SplitBuild word={props.payload.words.anchor} misses={state.splitMisses} correct={state.splitCorrect} splitDone={state.splitDone} muted={state.muted} missMessage={beat.onSlip} repeatedMissMessage={beat.onRepeatedMisconception} onMiss={(splitMisses) => update({ splitMisses })} onCorrect={() => update({ splitCorrect: true })} onRebuild={() => update({ splitDone: true })} onComplete={() => { completeBinding("guided-strip-unhappy"); update({ stage: "match", helpLevel: 0 }); }} /> : null}
    {state.stage === "match" ? <BinSort items={props.payload.words.lesson.map((word) => ({ id: word.displayWord, text: word.displayWord, destination: word.effect }))} bins={[{ id: "not", label: "NOT", description: "un- changes the meaning to not" }, { id: "reverse", label: "REVERSE", description: "un- reverses an action" }]} incorrectMessage={beat.onMisconception} repeatedIncorrectMessage={beat.onRepeatedMisconception} onComplete={() => update({ guidedBindings: [...new Set([...state.guidedBindings, ...props.payload.words.lesson.map((word) => `guided-meaning-${word.displayWord}`)])], stage: "build", helpLevel: 0 })} /> : null}
    {state.stage === "build" ? <PrefixBuild payload={props.payload} beat={beat} muted={state.muted} onComplete={() => { completeBinding("guided-build-untidy"); update({ stage: "controlled", helpLevel: 0 }); }} /> : null}
    {state.stage === "controlled" ? <Controlled word={props.payload.words.lesson[state.controlledIndex]} attempt={state.controlledAttempts[props.payload.words.lesson[state.controlledIndex].canonicalWordId] ?? ""} checked={state.controlledChecked[props.payload.words.lesson[state.controlledIndex].canonicalWordId] === true} muted={state.muted} onAttempt={(attempt) => update({ controlledAttempts: { ...state.controlledAttempts, [props.payload.words.lesson[state.controlledIndex].canonicalWordId]: attempt } })} onChecked={() => update({ controlledChecked: { ...state.controlledChecked, [props.payload.words.lesson[state.controlledIndex].canonicalWordId]: true } })} onNext={() => state.controlledIndex < 3 ? update({ controlledIndex: state.controlledIndex + 1, helpLevel: 0 }) : update({ stage: "dictation", helpLevel: 0 })} /> : null}
    {state.stage === "dictation" ? <Dictation payload={props.payload} index={state.dictationIndex} value={state.sentenceAttempts[props.payload.words.lesson[state.dictationIndex].canonicalWordId] ?? ""} checked={state.checkedSentence} muted={state.muted} onValue={(value) => update({ sentenceAttempts: { ...state.sentenceAttempts, [props.payload.words.lesson[state.dictationIndex].canonicalWordId]: value } })} onCheck={() => update({ checkedSentence: true })} onNext={() => state.dictationIndex < 3 ? update({ dictationIndex: state.dictationIndex + 1, checkedSentence: false }) : update({ stage: "reflect" })} /> : null}
    {state.stage === "reflect" ? <ReflectionForm state={state} payload={props.payload} childId={props.childId} assignmentId={props.assignmentId} items={props.items} onReflectionText={(reflectionText) => update({ reflectionText })} onPreviewComplete={props.onPreviewComplete} /> : null}
  </WordLabScene>;
}

function activityId(stage: Stage): string { return stage === "learn" ? "introduction" : stage === "split" ? "strip-build" : stage === "match" ? "meaning-match" : stage === "build" ? "build-word" : stage === "controlled" ? "controlled-spelling" : stage === "reflect" ? "reflection" : stage; }
function LearnIntroduction(props: { payload: MorphologyLessonPayloadV1; index: number; onNext: () => void }) { const activity = props.payload.activities.find((candidate) => candidate.type === "introduction")!; const screen = activity.introScreens![props.index]; return <section className="grid gap-5 text-center" aria-labelledby={`intro-${screen.id}`}><div><p className="text-xs font-black uppercase tracking-[.2em] text-cyan-200">Learn {props.index + 1} of 3</p><h1 id={`intro-${screen.id}`} className="mt-2 text-3xl font-black text-white">{screen.title}</h1></div><div className="mx-auto grid max-w-3xl gap-3">{screen.paragraphs.map((paragraph) => <p key={paragraph} className="text-lg leading-8 text-cyan-50">{paragraph}</p>)}</div>{screen.model ? <div className="mx-auto flex flex-wrap items-center justify-center gap-3 rounded-3xl border border-cyan-300/20 bg-slate-950/45 p-5" aria-label={`${screen.model.prefix} plus ${screen.model.base} makes ${screen.model.result}`}><span className="rounded-2xl bg-cyan-100 px-4 py-3 text-xl font-black text-cyan-950">{screen.model.prefix}</span><span aria-hidden="true" className="text-2xl text-cyan-200">+</span><span className="rounded-2xl bg-amber-100 px-4 py-3 text-xl font-black text-amber-950">{screen.model.base}</span><span aria-hidden="true" className="text-2xl text-cyan-200">→</span><span className="rounded-2xl bg-emerald-100 px-4 py-3 text-xl font-black text-emerald-950">{screen.model.result}</span></div> : null}{screen.wordCards ? <div className="grid gap-3 sm:grid-cols-2">{screen.wordCards.map((card) => <article key={`${card.base}-${card.derived}`} className="rounded-2xl bg-white p-4 text-left text-slate-950"><p className="text-xl font-black"><span className="text-amber-700">{card.base}</span><span aria-hidden="true" className="mx-2 text-slate-400">→</span><span className="text-cyan-800">{card.derived}</span></p><p className="mt-1 text-sm font-semibold text-slate-600">{card.meaning}</p></article>)}</div> : null}<button type="button" onClick={props.onNext} className="mx-auto min-h-12 rounded-full bg-cyan-300 px-7 font-black text-slate-950">{screen.ctaLabel}</button></section>; }
function Discovery(props: { payload: MorphologyLessonPayloadV1; index: number; onNext: () => void }) { const words = [props.payload.words.anchor, props.payload.words.lesson.find((word) => word.displayWord === "unkind")!, props.payload.words.lesson.find((word) => word.displayWord === "unlock")!]; const word = words[props.index]; const base = word.parts.find((part) => part.role === "base")?.text ?? ""; const [joined, setJoined] = useState(false); return <div className="grid gap-5 text-center"><p className="text-sm font-bold uppercase tracking-[.2em] text-cyan-200">Touch the prefix to move it</p><FlipToggle prefix="un" base={base} baseMeaning={word.baseMeaning} derivedMeaning={word.derivedMeaning} onChange={(value) => setJoined(value)} />{joined ? <button type="button" onClick={props.onNext} className="mx-auto min-h-12 rounded-full bg-cyan-300 px-6 font-black text-slate-950">{props.index < 2 ? "Try another word" : "Explore the join"}</button> : null}</div>; }
function SplitBuild(props: { word: MorphologyWordSnapshot; misses: number; correct: boolean; splitDone: boolean; muted: boolean; missMessage?: string; repeatedMissMessage?: string; onMiss: (misses: number) => void; onCorrect: () => void; onRebuild: () => void; onComplete: () => void }) { return <div className="grid gap-6">{!props.splitDone ? <SplitHandle word={props.word.displayWord} splitPoints={props.word.splitPoints} misses={props.misses} correct={props.correct} muted={props.muted} missMessage={props.missMessage} repeatedMissMessage={props.repeatedMissMessage} onMiss={props.onMiss} onCorrect={props.onCorrect} onContinue={props.onRebuild} /> : <SnapRail tiles={props.word.parts.map((part) => ({ id: part.id, text: part.text, role: part.role, gloss: part.gloss }))} expectedIds={props.word.parts.map((part) => part.id)} label="Rebuild unhappy" muted={props.muted} onComplete={props.onComplete} />}</div>; }
function PrefixBuild(props: { payload: MorphologyLessonPayloadV1; beat: MorphologyLessonPayloadV1["guide"]["beats"][number]; muted: boolean; onComplete: () => void }) { const activity = props.payload.activities.find((candidate) => candidate.type === "prefix_choice")!; const [message, setMessage] = useState(""); const [misses, setMisses] = useState(0); const choices = activity.prefixChoices ?? []; return <div className="grid gap-4"><SnapRail tiles={choices.map((choice) => ({ id: choice.text, text: choice.label, role: "prefix" as const, gloss: choice.meaning ?? undefined }))} expectedIds={["un"]} fixedTiles={[{ id: "tidy", text: "tidy", role: "base" }]} fixedTilesPosition="after" label="Choose a prefix for tidy" muted={props.muted} onComplete={props.onComplete} onInvalid={(ids) => { const choice = choices.find((candidate) => candidate.text === ids[0]); const nextMisses = misses + 1; setMisses(nextMisses); setMessage(choice?.status === "valid_alternative" ? `${choice.outcome} means ${choice.meaning}. ${props.beat.onPartial ?? "We need a word meaning not tidy."}` : nextMisses > 1 ? props.beat.onRepeatedMisconception ?? "Choose un- to make untidy." : props.beat.onMisconception ?? "That prefix does not make the word we need with tidy."); }} /><p aria-live="polite" className="min-h-6 text-center font-semibold text-cyan-100">{message}</p></div>; }
function Controlled(props: { word: MorphologyWordSnapshot; attempt: string; checked: boolean; muted: boolean; onAttempt: (attempt: string) => void; onChecked: () => void; onNext: () => void }) { return <div className="grid gap-4"><p className="text-center text-sm font-black uppercase tracking-[.2em] text-cyan-200">Word to remember {props.word.displayWord === "unfair" ? "1" : props.word.displayWord === "unkind" ? "2" : props.word.displayWord === "unlock" ? "3" : "4"} of 4</p><CoverShutter key={props.word.canonicalWordId} word={props.word.displayWord} splitPoints={props.word.splitPoints} initialAttempt={props.attempt} initialState={props.checked ? "check" : props.attempt ? "write" : "look"} muted={props.muted} onStateChange={(_, attempt) => attempt && props.onAttempt(attempt)} onComplete={(attempt) => { props.onAttempt(attempt); props.onChecked(); }} />{props.checked ? <button type="button" onClick={props.onNext} className="min-h-12 rounded-full bg-cyan-300 font-black text-slate-950">Continue</button> : null}</div>; }
function Dictation(props: { payload: MorphologyLessonPayloadV1; index: number; value: string; checked: boolean; muted: boolean; onValue: (value: string) => void; onCheck: () => void; onNext: () => void }) { const activity = props.payload.activities.find((candidate) => candidate.type === "sentence_dictation")!; const sentence = activity.sentences![props.index]; return <div className="grid gap-4"><p className="text-center text-sm font-black uppercase tracking-[.2em] text-cyan-200">Sentence {props.index + 1} of 4</p><div className="flex justify-center"><HearWordButton word={sentence.sentence} label="Play sentence" muted={props.muted} /></div><label className="text-sm font-semibold text-cyan-50">Write the whole sentence<textarea autoFocus spellCheck={false} autoComplete="off" autoCapitalize="sentences" value={props.value} onChange={(event) => props.onValue(event.target.value)} className="mt-2 min-h-28 w-full rounded-2xl bg-white p-4 text-lg text-slate-950 focus:outline-none focus:ring-4 focus:ring-cyan-300/30" /></label>{!props.checked ? <button type="button" disabled={!props.value.trim()} onClick={props.onCheck} className="min-h-12 rounded-full bg-cyan-300 font-black text-slate-950 disabled:opacity-40">Check sentence</button> : <><DiffReveal attempt={props.value} expected={sentence.sentence} mode="sentence" /><button type="button" onClick={props.onNext} className="min-h-12 rounded-full bg-cyan-300 font-black text-slate-950">{props.index < 3 ? "Next sentence" : "See what you discovered"}</button></>}</div>; }

function ReflectionForm(props: { state: LessonState; payload: MorphologyLessonPayloadV1; childId: string; assignmentId: string; items: AdleSessionItem[]; onReflectionText: (value: string) => void; onPreviewComplete?: (reflectionText: string) => void }) {
  const reflection = props.payload.activities.find((activity) => activity.type === "reflection")!;
  const dictation = props.payload.activities.find((activity) => activity.type === "sentence_dictation")!;
  const controlledMisses = props.payload.words.lesson.filter((word) => normaliseSessionWord(props.state.controlledAttempts[word.canonicalWordId] ?? "") !== normaliseSessionWord(word.displayWord)).map((word) => ({ label: word.displayWord, detail: `You wrote “${props.state.controlledAttempts[word.canonicalWordId] || "nothing"}”.` }));
  const sentenceMisses = (dictation.sentences ?? []).filter((sentence) => (props.state.sentenceAttempts[sentence.canonicalWordId] ?? "").trim() !== sentence.sentence).map((sentence) => ({ label: sentence.targetWord, detail: `Compare “${props.state.sentenceAttempts[sentence.canonicalWordId] || "nothing"}” with “${sentence.sentence}”.` }));
  const misses = [...controlledMisses, ...sentenceMisses];
  const ready = props.state.reflectionText.trim().length > 0;
  return <form action={props.onPreviewComplete ? undefined : completeAdleLessonPartAction} onSubmit={props.onPreviewComplete ? (event) => { event.preventDefault(); props.onPreviewComplete?.(props.state.reflectionText); } : undefined} className="grid w-full gap-5">
    <input type="hidden" name="mode" value="child"/><input type="hidden" name="childId" value={props.childId}/><input type="hidden" name="assignmentId" value={props.assignmentId}/><input type="hidden" name="attempts" value={attemptsJson(props.state.controlledAttempts)}/><input type="hidden" name="dictationSentenceAttempts" value={attemptsJson(props.state.sentenceAttempts)}/><input type="hidden" name="dictationAttempts" value="[]"/><input type="hidden" name="probeAttempts" value="[]"/><input type="hidden" name="guidedAttempts" value={attemptsJson(Object.fromEntries(props.state.guidedBindings.map((binding) => [bindingItem(props.items, binding)?.id ?? binding, ""])))}/>
    <section className="rounded-3xl border border-white/15 bg-white/[.07] p-4 text-left" aria-labelledby="remember-recap-heading"><p className="text-xs font-black uppercase tracking-[.18em] text-cyan-200">Remember recap</p><h2 id="remember-recap-heading" className="mt-1 text-xl font-black text-white">{misses.length ? "A few things to look at again" : "You remembered the targets"}</h2>{misses.length ? <ul className="mt-3 grid gap-2">{misses.map((miss, index) => <li key={`${miss.label}-${index}`} className="rounded-2xl bg-amber-50 p-3 text-sm text-amber-950"><span className="font-black">{miss.label}:</span> {miss.detail}</li>)}</ul> : <p className="mt-2 text-sm text-cyan-50">Use your reflection to explain the pattern you noticed.</p>}</section>
    <label className="text-left text-base font-black text-white">{reflection.promptText}<textarea name="learningReflection" required maxLength={2000} autoFocus value={props.state.reflectionText} onChange={(event) => props.onReflectionText(event.target.value)} className="mt-2 min-h-32 w-full rounded-2xl bg-white p-4 text-lg font-normal text-slate-950 focus:outline-none focus:ring-4 focus:ring-cyan-300/30" /></label>
    {ready ? <><div className="grid gap-3 sm:grid-cols-2"><div className="rounded-2xl bg-cyan-100 p-4 text-center text-cyan-950"><p className="font-black">NOT</p><p>{props.payload.words.lesson.filter((word) => word.effect === "not").map((word) => word.displayWord).join(" · ")}</p></div><div className="rounded-2xl bg-amber-100 p-4 text-center text-amber-950"><p className="font-black">REVERSE</p><p>{props.payload.words.lesson.filter((word) => word.effect === "reverse").map((word) => word.displayWord).join(" · ")}</p></div></div><button type="submit" className="min-h-14 rounded-full bg-cyan-300 px-8 text-lg font-black text-slate-950">Finish the Word Lab</button></> : <p className="text-center text-sm font-semibold text-cyan-100">Write one thing you noticed to finish the Word Lab.</p>}
  </form>;
}
